.github/CODEOWNERS
Initially marks all files as owned by the forms-devs team, as we go forward this will likely be more granular
Closes #2
=> Add initial codeowners

README.md, bin/setup
By default Rails provides a setup file which can be used for initial setup and update tasks. Previouslty we weren't really using this, so this PR moves some of our setup tasks into this file. 
Tem members and contributors can now run `bin/setup` when first cloning the repo or when pulling changes to make sure that their dependencies, FE assets and database are up to date.
=> Move setup steps into Rails setup script

.env.development, .env.test, Gemfile, Gemfile.lock, README.md, app/controllers/form_controller.rb, app/controllers/page_controller.rb, app/models/form.rb, app/models/page.rb, app/models/page_old.rb, app/views/form/show.html.erb, app/views/page/show.html.erb, config/application.rb, config/locales/en.yml, config/routes.rb, spec/models/form_spec.rb, spec/models/page_spec.rb, spec/requests/forms/pages_spec.rb, spec/requests/forms_spec.rb, spec/requests/page_spec.rb
We want to be able to access a form (e.g. `/2` for a form with an ID of 2) which then redirects you to the first page. This involves:
- Setting up the routing to more accurately map the end result
- Setting up the form/page models with relationships
- Creating the route on the form controller to map to the first page
- Creating the page controller to display the question text for the first page
This requires a [corresponding set of changes required in the forms API](https://github.com/alphagov/forms-api/pull/29).
=> Load the start page for a form when accessing it

.env.development, Gemfile, Gemfile.lock, app/controllers/form_controller.rb, app/controllers/page_controller.rb, app/lib/question_register.rb, app/models/page.rb, app/models/question/address.rb, app/models/question/application_question.rb, app/models/question/date.rb, app/models/question/email.rb, app/models/question/national_insurance_number.rb, app/models/question/phone_number.rb, app/models/question/question_base.rb, app/models/question/single_line.rb, app/views/form/check_your_answers.html.erb, app/views/form/submitted.html.erb, app/views/page/show.html.erb, app/views/question/_address.html.erb, app/views/question/_date.html.erb, app/views/question/_email.html.erb, app/views/question/_national_insurance_number.html.erb, app/views/question/_phone_number.html.erb, app/views/question/_single_line.html.erb, config/routes.rb, spec/requests/page_spec.rb
Add forms to runner
This pull request adds forms to the pages in the runner.
It allows users to enter information so that it can be submitted by notify at the end of the jounrey.
Because it was hard to add forms without considering how validation, saving data in the session and CYA would work. The basics of these features have also been added.
The general approach is to create a question model and a partial to represent it in the form. This gives good control and flexibility over creating new question types and validating them. Partials might not be the best way to handle views - it might be interesting to invert things and give questions full control over the form they are presented in.
All current page types have been added, but the validation for email address, postcode and NINO hasn't …
=> 41 allow form completers to submit their answers

Procfile.dev, config/puma.rb, cypress.config.js
forms-admin is running on port 3000 so if a developer tries to spin
up all three services there will be a clash in ports being used.
=> Switch server port from 3000 to 3001

Gemfile.lock
This deprecation warning was flagged in this github issue
https://github.com/rubygems/rubygems/issues/5234
I fixed this by running `bundle update --bundler`
`Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.`
When running any ruby commands you should no longer see these warnings.
Relates to https://github.com/alphagov/forms-admin/pull/95
=> Fix annoying deprecation warning

.github/workflows/deploy.yml, README.md, app/models/form.rb, app/models/page.rb, manifest.yml, spec/models/form_spec.rb, spec/models/page_spec.rb, spec/requests/check_your_answers_spec.rb, spec/requests/errors_spec.rb, spec/requests/forms_spec.rb, spec/requests/page_spec.rb
Reverts alphagov/forms-runner#83 - the deploy was failing with an error saying an env var wasn't supplied. Will revert to debug.
=> Revert "api_key"

app/controllers/form_controller.rb, app/controllers/forms/check_your_answers_controller.rb, app/controllers/forms/page_controller.rb, app/controllers/forms/submitted_controller.rb, app/lib/context.rb, app/views/layouts/application.html.erb, config/locales/en.yml, spec/lib/context_spec.rb, spec/lib/event_logger_spec.rb, spec/requests/check_your_answers_spec.rb, spec/requests/forms_spec.rb, spec/requests/page_spec.rb
Reads a form's privacy policy URL and displays it in the footer if it's present.
Trello card: https://trello.com/c/aZtUyjei/16-add-link-to-privacy-information-to-forms-runner-in-footer-of-every-form-pageneeds-dev-review
=> Add privacy policy link

Gemfile, Gemfile.lock, app/lib/redis_config.rb, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/session_store.rb, spec/fixtures/vcap_example.json, spec/lib/redis_config_spec.rb, spec/spec_helper.rb
Add a few security measures to protect users sessions in the runner:
- set `force_ssl=true` in production, this sets secure=true on cookies, so they are only ever transported over ssl, also HSTS
- set TTL on Redis session keys to 20hours. This means sessions will expire after 20hours of no requests to the server from the users browser. Cookies are still session based, so are not kept around after the browser closes.
- cleans up the config of redis and tries to prevent accidental misconfiguration of the session store
There are a few other session based things which we might consider doing - I'm also documenting current behaviour in a sample session and I'll bring a few of them up for review.
=> Fix sessions

app/services/notify_service.rb
Forms can't be submitted without raising an error:
https://sentry.io/organizations/govuk-forms/issues/3548258202/?project=6576261&query=is%3Aunresolved
This happens because `Time.now.zone` was called instead of
`Time.zone.now`. The first returns a string - e.g 'UTC', which then
throws method unknown when the `strftime` call is made.
This seems a sharp corner of ruby `Time` and rubocop bullied us into
making the error in the first place.
=> Fix: Submission timestamp issue

app/views/question/_address.html.erb
The govuk-form-builder gem doesn't support adding a hint to the address component, so Rails turns this into an invalid 'hint' attribute.
I've removed that attribute and added the hint text to the markup.
Trello card: https://trello.com/c/YcZBtTWC/103-fix-html-parsing-error-on-address-input
=> Fix HTML parsing error in address input

app/assets/stylesheets/application.scss, app/controllers/help_controller.rb, app/views/help/accessibility_statement.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml, config/routes.rb, spec/requests/help_spec.rb, spec/requests/page_spec.rb
Adds a static accessibility page to the runner and links to it in the footer. 
Note that the content isn't quite final yet, but functionally this should be complete and can be merged if approved.
Trello card: https://trello.com/c/v2RiiRfw/353-add-a-static-accessibility-statement-to-forms-runner-and-a-link-to-it-in-footer-of-every-form-page-content-to-change-after-inter
=> Add accessibility statement page

spec/requests/forms_spec.rb
In this PR: https://github.com/alphagov/forms-api/pull/69 we're changing the type of next_page from string to int - this PR reflects those changes in the test data in this repo.
=> change type of next_page from string to int in tests

app/assets/config/manifest.js, app/views/layouts/application.html.erb
- Uses the correct Rails import statements to import the favicon / apple icons / facebook meta image
- Adds the images to the manifest.js so that they're precompiled
- Removes the Rails blank default favicon from the public folder
These changes were previously made in the Admin app: https://github.com/alphagov/forms-admin/pull/120
Trello card: https://trello.com/c/T1w27bgy/105-fix-missing-favicons
=> Fix missing favicons

app/lib/context.rb, app/views/forms/submitted/submitted.html.erb, spec/lib/context_spec.rb, spec/lib/event_logger_spec.rb, spec/requests/check_your_answers_spec.rb, spec/requests/forms_spec.rb, spec/requests/page_spec.rb, spec/views/forms/submitted/submitted.html.erb_spec.rb
Form users need to know what happens after they submit the form. If a form admin has added copy to the forms "What happens next" step then that copy will now be show to the form user once they have submitted their form
related to https://trello.com/c/4mCMqpda/356-add-what-happens-next-to-the-confirmation-page-should-have
=> Add "What happens next" to the submitted confirmation page

app/controllers/form_controller.rb, app/controllers/forms/check_your_answers_controller.rb, app/controllers/forms/page_controller.rb, app/controllers/forms/privacy_page_controller.rb, app/controllers/forms/submitted_controller.rb, app/views/forms/privacy_page/show.html.erb, app/views/help/cookies.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/lib/event_logger_spec.rb, spec/requests/forms_spec.rb
Adds a new privacy page, containing both a link to the existing user-generated privacy policy, and our own privacy information.
Trello card: https://trello.com/c/wFxazV7I/144-add-privacy-page-to-the-runner
=> Add privacy page

app/services/notify_service.rb, config/initializers/submission.rb, spec/rails_helper.rb, spec/services/notify_service_spec.rb
https://trello.com/c/XNOhXuOY/128-bug-submission-time-in-the-processing-email-is-off-by-an-hour
Submission emails show the time of submission in UTC zone - which the server uses. This commit changes the timezone to use a zone specified in the config and defaults to London. It also adds tests to the submission code.
=> Make submission time in emails use local timezone

app/controllers/form_controller.rb, app/controllers/forms/check_your_answers_controller.rb, app/controllers/forms/page_controller.rb, app/lib/context.rb, app/lib/step_factory.rb, app/models/step.rb, app/views/forms/page/show.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/lib/context_spec.rb, spec/lib/event_logger_spec.rb, spec/requests/check_your_answers_spec.rb, spec/requests/errors_spec.rb, spec/requests/forms_spec.rb, spec/requests/page_spec.rb
We decided to add the form slug to the run
Relates to https://trello.com/c/J5E6JuuY/92-use-human-readable-url-paths-for-forms-instead-of-id-based-paths
=> Add form_slug to urls

app/controllers/forms/page_controller.rb, spec/requests/page_spec.rb
the back link did not include the form slug in it and the tests that were written were not detecting this and returning false positive. The reason it was returning a false positive was because the get request in the redirect was included a message with a path to the redirect which happened to be the correct path but the page being rendered after the redirect did not include it.
=> Fix pages back link bug

app/controllers/forms/submit_answers_controller.rb, app/services/notify_service.rb, spec/services/notify_service_spec.rb
We wanted to help organisations identify whether a submitted form came from a preview or from an actual form. This was a quick fix because we didn't have any research on what our users needed from previews but we did know that some people were still accessing the preview form, filling it and submitting it to the form submission email inbox. It was difficult to tell from the email if it was real or not.
refers to https://trello.com/c/0IVH9W4B/179-consider-if-we-should-add-test-form-to-the-subject-line-of-emails-sent-from-the-preview-form
=> Add "TEST FORM" to submission email if in preview

Dockerfile
Even to run the local dev setup the `rails assets:precompile` needs to have been run so remove the condition within the Dockerfile.
Make it simpler to run forms locally.
=> Always precompile assets when building image

app/lib/question_register.rb, app/models/question/number.rb, app/views/question/_number.html.erb, config/locales/en.yml, spec/lib/question_register_spec.rb, spec/models/question/long_text_spec.rb, spec/models/question/number_spec.rb, spec/requests/base_spec.rb, spec/services/notify_service_spec.rb
Adds a new number input type. This can be any whole or decimal number greater than or equal to 0.
Trello card: https://trello.com/c/tyDQQZ6A/222-add-number-answer-to-a-question-in-the-runner-and-api
=> Add number answer type

spec/models/question/number_spec.rb
Addresses some post-merge feedback on #158 - removes some redundant calls to `validate`, which is already included in rspec's `be_valid` check.
=> Remove redundant calls to validate

app/services/notify_service.rb, spec/services/notify_service_spec.rb
This seems to escape all markdown characters without having to replace any of the users data. We do need to test this technique with multi-Line question types because it might not work as expected when extra new line breaks are involved'
=> Wrap answers in a three back tick block

app/controllers/forms/check_your_answers_controller.rb, app/helpers/application_helper.rb, app/views/question/_address.html.erb, app/views/question/_date.html.erb, app/views/question/_email.html.erb, app/views/question/_long_text.html.erb, app/views/question/_national_insurance_number.html.erb, app/views/question/_number.html.erb, app/views/question/_phone_number.html.erb, app/views/question/_single_line.html.erb, config/locales/en.yml, spec/helpers/application_helper_spec.rb, spec/lib/question_register_spec.rb, spec/models/question/date_spec.rb, spec/models/question/email_spec.rb, spec/models/question/long_text_spec.rb, spec/models/question/national_insurance_number_spec.rb, spec/models/question/phone_number_spec.rb, spec/models/question/single_line_spec.rb, spec/services/notify_service_spec.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
Lets the form filler know that the question they're looking at is optional, without needing the form creator to explicitly add this to the label.
Trello card: https://trello.com/c/0Fp3VrLT/90-epic-build-optional-questions
=> Add optional text suffix

app/controllers/forms/check_your_answers_controller.rb, app/helpers/application_helper.rb, app/models/question/long_text.rb, app/models/question/question_base.rb, app/services/notify_service.rb, app/views/forms/check_your_answers/show.html.erb, spec/services/notify_service_spec.rb, spec/support/shared_examples/question_models.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
Long text is a new answer type which adds a couple of complications:
- playing back long text answers in the CYA screen
- submitting text with line breaks via notify
Answers with line breaks need to show paragraphs on the check your answer
screen. This commit breaks text into paragraphs and removes leading/trailing
space. It condenses multiple newlines into single newlines.
Notify interprets submissions as markdown and doesn't offer a way to safely
escape markdown formatting.
This commit fixes both of these issues.
=> Escape long answers

app/controllers/forms/page_controller.rb, app/lib/event_logger.rb, app/services/log_event_service.rb, spec/lib/event_logger_spec.rb, spec/requests/page_spec.rb, spec/services/log_event_service_spec.rb
https://trello.com/c/DmZWSCEK/249-form-runner-log-events-for-when-a-user-completes-skips-optional-question
Adding a log for when users skip or complete an optional question. This has been broken into two parts, one that adds a log key for a question being optional or not, and another for when a question is skipped, currently only possible if it's optional. 
The log used to show up like this - `[page_save] {"url":"http://localhost:3001/preview-form/1/test/7","method":"POST","form":"test","question_text":"phone num"}`
And now will show up like this if it's an optional question that isn't skipped - `[optional_save] {"url":"http://localhost:3001/preview-form/1/test/7","method":"POST","form":"test","question_text":"phone num","optional_question":"true","skipped_question":"false"}`
And like …
=> 249 form runner log events for when a user completes skips optional question

config/environments/production.rb
Our Puma server is not configured for TLS despite the `config.force_ssl = true`. Instead if the request has `X-Forwarded-Proto: https` set then Puma will not redirect to `https` and serve the request. Whenever a request comes via a level 7 router such as an ALB or the PaaS Router it sets the header based on the original client protocol.
On AWS the ALB sends a healthcheck to /ping directly and we cannot set the headers. Stop redirecting /ping to https so we can use it as a healthcheck for now.
with @alice-carr
We have built and deployed this to AWS dev account and the ECS task is passing the healthchecks.
=> Do not redirect to HTTPS for /ping

Gemfile.lock, app/models/question/address.rb, spec/models/question/address_spec.rb, spec/services/notify_service_spec.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
Fixes a bug with address validation where if an address question was optional the user could enter invalid input.
Also includes a couple of minor linting fixes from elsewhere that rubocop picked up.
Trello card: https://trello.com/c/TZsyB7DK/284-addresses-arent-validated-when-theyre-optional
=> Validate optional address fields if any fields have been filled in 

Dockerfile
Do not copy the public assets into /public but instead copy them into /app/public which is where Rails expects them to be. We should revisit to make sure we only copy what we actually need between the build and final stages.
Forms-Runner running from the docker image was unable to find the precompiled public assets because they were being copied into the wrong directory. This copies the public assets and puts them under the `/app` working directory. We should revisit before going live to make sure we only copy the necessary files between build and final stages.
I have deployed this to dev environment and it works as expected to return the 404 page:
https://submit.dev.forms.service.gov.uk/
I have also run this with `docker-compose` and it works as expected.
I'll look at forms-admin and …
=> Copy Assets Into Correct Directory

Gemfile, Gemfile.lock, package.json, yarn.lock
- Updates GOV.UK Frontend to v4.4.0
- Updates the component and form builder gems to the corresponding version (3.3.0)
- Sets the govuk-frontend npm package to update bug fixes but not minor versions
=> Update GOV.UK Frontend to v4.4.0

app/lib/event_logger.rb, app/lib/step_factory.rb, app/models/page.rb, app/models/step.rb, config/environments/production.rb, spec/lib/event_logger_spec.rb, spec/requests/page_spec.rb
Adds page numbers to the existing log events. 
Trello card: https://trello.com/c/gdivugjM/322-log-the-question-number
=> Add page numbers to page save log events

app/lib/question_register.rb, app/models/page.rb, app/models/question/question_base.rb, app/models/question/selection.rb, app/models/step.rb, app/views/question/_selection.html.erb, config/locales/en.yml, spec/models/page_spec.rb, spec/models/question/selection_spec.rb, spec/support/shared_examples/question_models.rb, spec/views/question/_selection.html.erb_spec.rb
Adds a question type for selections, which can be either checkboxes or radios depending on the value of `answer_settings.allow_multiple_answers`.
Trello card: https://trello.com/c/VLYnibtv/225-add-selection-question-type-to-runner
=> Add selection list answer type

app/controllers/forms/check_your_answers_controller.rb, app/lib/step_factory.rb, app/models/check_your_answers_step.rb, config/routes.rb, spec/lib/context_spec.rb, spec/lib/step_factory_spec.rb, spec/requests/check_your_answers_spec.rb, spec/requests/page_spec.rb
Sentry reports errors thrown by the pages controller when URLs for form pages contain invalid page URLs or trailing characters. This happens a lot because of bots looking for well known exploitable URLS.
The sentry issue can be found here:
https://sentry.io/organizations/govuk-forms/issues/3551642298/?project=6576261&query=is%3Aunresolved&referrer=issue-stream
This PR includes a failing test and a fix. 
The fix adds a regex constraint on the route which connects requests to the forms/page_controller. By restricting the page_id to being a string of digits or "check_your_answers" we can stop the controller action being called when given invalid urls. This causes the standard 404 route to match, returning a 404.
Only the get page route has been modified. If we find the other page_id requests …
=> Sentry stop 404 for malicious get requests to from pages

app/models/question/selection.rb, spec/lib/step_factory_spec.rb, spec/models/page_spec.rb, spec/models/question/selection_spec.rb, spec/requests/page_spec.rb, spec/views/question/_selection.html.erb_spec.rb
Renames the 'allow multiple answers' field to match the way it's presented in the admin design. This requires negating it - `allow_multiple_answers`  and `only_one_option` are opposites.
Trello card: https://trello.com/c/9AKruIBG/321-add-selection-question-type-to-admin-radio-buttons-only
=> Rename and negate 'allow multiple answers'

app/lib/form_context.rb, app/lib/journey.rb, spec/lib/context_spec.rb, spec/lib/form_context_spec.rb
https://sentry.io/organizations/govuk-forms/issues/3670884315/?environment=local&project=6576261&query=is%3Aunresolved&referrer=issue-stream
https://trello.com/c/wyCLgyHJ/342-unknownattributeerror-when-changing-question-types
Form creators changing questions between some answer types can cause an
UnknownAttributeError for form fillers.
Steps to reproduce
- create a long text answer in admin
- preview the form and add text to the long text answer (so data is
stored in Redis as text)
- change the long text question to a number in admin
- preview the page
Expected Behaviour
The new page should be loaded without an error, with the text I saved
earlier either preserved or deleted
Actual behaviour
The page throws an UnknownAttributeError because the runner attempts to
load the saved answer as …
=> Fix attribute error

.gitignore, app/controllers/forms/check_your_answers_controller.rb, app/controllers/forms/submit_answers_controller.rb, app/services/notify_service.rb, app/views/forms/check_your_answers/show.html.erb, spec/services/notify_service_spec.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
This PR is part of a set, the other being in forms-deploy https://github.com/alphagov/forms-deploy/pull/54
Trello card: https://trello.com/c/R9jqd9GT/341-e2e-add-checking-notify-has-received-and-sent-off-the-completed-submitted-form
The idea is to check that submitting a form correctly triggers a Notify email, which is successfully delivered.
The changes on the runner side are to provide the reference to Notify as part of the `notify_service`, and also to display the reference as a hidden field on the check your answers page, so that the e2e tests can obtain it.
=> Add hidden field for notify reference

app/lib/question_register.rb, app/models/question/organisation_name.rb, app/views/question/_organisation_name.erb, config/locales/en.yml, spec/lib/context_spec.rb, spec/lib/question_register_spec.rb, spec/models/question/organisation_name_spec.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
Implements a new 'organisation name' answer type in the runner. This input is almost identical to the single line of text, but contains an autocomplete attribute. Because they're so similar, I _could_ have used the existing single line of text model/view for this, but:
- Separate models and views makes it easier for validation rules and messages to diverge
- We might merge the single line of text and longer text fields as part of the [text ticket in the same epic](https://trello.com/c/hiSdqQBI/394-text-implementation-of-autofill-work-in-production)
- This means less logic in the view
Trello card: https://trello.com/c/jRKIbnBl/369-org-name-implementation-of-autofill-work-in-production
- …
=> Add organisation name answer type

app/lib/question_register.rb, app/models/question/text.rb, app/views/question/_text.html.erb, config/locales/en.yml, spec/lib/question_register_spec.rb, spec/models/question/text_spec.rb
Co-authored-by: Samuel Culley <SamJamCul@users.noreply.github.com>
Adds text question type, which does the same thing as the current 'single_line' and 'long_text' inputs depending on what 'input_type' is set to in the API.
We've made a small change to the validation for long_text  - it now accepts input of 4999 characters or fewer instead of 5000 characters or fewer. This matches the validation message and is also consitent with the 499 we use for single_line inputs.
Trello card:https://trello.com/c/hiSdqQBI/375-text-implementation-of-autofill-work-in-production
=> Add text question type

app/models/question/date.rb, app/views/question/_date.html.erb, config/locales/en.yml, spec/models/question/date_spec.rb, spec/views/question/_date.html.erb_spec.rb
Co-authored-by: Samuel Culley <SamJamCul@users.noreply.github.com>
Adds appropriate autocomplete attributes when the date is set as a date of birth. Also validates that dates of birth aren't in the future.
Trello card: https://trello.com/c/sDrOCmAp/383-dob-implementation-of-autofill-work-in-production
=> Add date of birth with autocomplete attributes

app/models/question/date.rb, spec/views/question/_date.html.erb_spec.rb
Visiting a question page with an existing date field (i.e. one without an answer settings field) will result in an error, since the date question type expects the input type to be present.
This PR adds a check for this. This should be a temporary solution - the proper solution is to migrate the existing date (and address) fields. There is a ticket for this in the backlog which should be done in the next sprint.
=> Fix bug with existing dates

config/initializers/sentry.rb
Disable Sentry Transactions
Sentry Transactions can be used to monitor application performance by
sampling transaction data. We are not using this aspect of Sentry and
have decided to turn it off.
Setting this to `0.0` or removing it all together will disable transaction data: https://docs.sentry.io/platforms/ruby/guides/rails/configuration/options/#tracing-options
I've opted to set it to `0.0` so there is some on-going record for the future that we have intentionally disabled this feature.
=> Disable Sentry Transactions

.gitignore, config/initializers/sentry.rb
Use SENTRY_ENVIRONMENT for new AWS Environments
Rather than using `PAAS_ENVIRONMENT` to derive the sentry environment
use `SENTRY_ENVIRONMENT` and remove `PAAS_ENVIRONMENT` once we've
migrated.
I presume this will be updated as we move further to use the `Settings.` config setup but this allows us to enable Sentry on AWS without using soon to be deprecated env var `PAAS_ENVIRONMENT`
=> Update env vars

app/models/question/address.rb, app/views/question/_address.html.erb, config/locales/en.yml, spec/models/question/address_spec.rb, spec/views/question/_address.html.erb_spec.rb
Uses the new autofill settings on the address input type to determine whether the UK address or international address fields should be displayed to a form filler. Includes validation specific to each address type.
Trello card: https://trello.com/c/zdoo448d/382-address-implementation-of-autofill-work-in-production
Related PRs:
- Admin: https://github.com/alphagov/forms-admin/pull/270
- API: https://github.com/alphagov/forms-api/pull/168
=> Address autofill

app/mailers/form_submission_mailer.rb, config/settings.yml, spec/config/settings_spec.rb, spec/mailers/form_submission_mailer_spec.rb
This PR changes the form submission email request thats sent to notify.  Form submission emails should use our no-reply email address so form processors teams do not accidentally reply to our email with users data in them. All other emails at this stage will still have a reply to set to our default team email address 
Trello card: https://trello.com/c/hNv5h7Ct/443-add-no-reply-email-address
=> Add email-reply-to

app/views/question/_name.html.erb
Resolves some divergences with the design - namely:
- Removes the 'Optional' text on the optional name inputs, in line with design system guidance
- If a name question is set to full name, and there's no title, it will now use the question text as the label rather than have a reedundant 'full name' label.
Trello card: https://trello.com/c/nPbS36yK/483-autofill-cleanup-tasks
=> Autofill cleanup task

app/models/question/date.rb, spec/models/question/date_spec.rb
This method is a rails method that was being called on a Struct rather than a Date object
fixes https://sentry.io/organizations/govuk-forms/issues/3907609448/?project=6576261&query=is%3Aunresolved&referrer=issue-stream
Trello card:
=> Fix undefined method `future?'  for date answer types

app/controllers/forms/base_controller.rb, app/models/form.rb, spec/requests/base_spec.rb, spec/requests/check_your_answers_spec.rb, spec/requests/errors_spec.rb, spec/requests/page_spec.rb
The runner only needs a read-only view of the form currently being served along with the pages of the form. Currently, two API requests are made whenever a form page is served - one to fetch the form and one to fetch the pages.
A new route has been added to the API to return the form including pages. This commit uses this endpoint to fetch the complete form.
Trello card:
=> Use new live_form route in API

config/locales/en.yml
A few small content changes to two error messages because:
- parentheses are allowed in a phone number but are not mentioned in the relevant error message
- the formatting error message is clearer as a description rather than an instruction (and this aligns with design system guidance)
- there's a closing quote that should be an opening quote
- there was a missing positive contraction
Trello card: https://trello.com/c/sYlADvRO/555-couple-of-tiny-error-message-fixes
=> Update content of two error messages

app/services/form_submission_service.rb, spec/services/form_submission_service_spec.rb
We need to validate that when a form filler submits their
answer for a form, before attempting to call GOVUK Notify,
we check that the form actually has a submission email.
This should be very rare because live forms should have
a submission email before they are made live. The only real
use case where a submission email maybe blank is when a
the form creator is previewing a form and they haven't completed
the add submission email task before they previewed the form. Rather than attempting to call GOVUK Notify without
a submission email and for it to raise an unhandled error we
can instead ignore the call to the mailer and process
the request as though the submission email address was provided
(After all, this is just a preview form so it shouldn't really
matter but if the form creator …
=> Ensure a form has a submission email and steps before sending submission email

.github/workflows/deploy.yml
Allows us to deploy a branch to the PaaS dev server. We already have this for admin. 
This github action isn't likely to last very long since we're switching over to AWS soon, where I think we can already do arbitrary deploys. I'm planning to use this to test the changes in https://github.com/alphagov/forms-runner/pull/281.
Trello card: https://trello.com/c/Q6RLPY64/409-allow-manual-deploys-to-dev-environment
=> Allow manual deploys of arbitrary branch to CI

app/controllers/forms/base_controller.rb, app/models/form.rb, app/views/layouts/application.html.erb, config/routes.rb, spec/helpers/application_helper_spec.rb, spec/requests/check_your_answers_spec.rb, spec/requests/forms/base_controller_spec.rb, spec/requests/forms/submit_answers_controller_spec.rb, spec/requests/page_spec.rb
Trello card: https://trello.com/c/YajCpcgm/557-enable-form-preview-for-draft-and-live-forms
See: https://github.com/alphagov/forms-admin/pull/339
=> Fix preview draft live links

Dockerfile, Gemfile, Gemfile.lock
This removes the edge repository from the alpine install steps in Dockerfile.
We do this to make the build more stable and to match the PRs against admin and runner.
Trello card:
=> Remove alpine edge repository from Dockerfile

app/components/main_component/_index.scss, app/components/main_component/view.rb, app/controllers/application_controller.rb, app/controllers/forms/page_controller.rb, app/frontend/entrypoints/application.scss, app/views/layouts/application.html.erb, spec/components/main_component/main_component_preview.rb, spec/components/main_component/view_spec.rb
The watermarks can be a bit busy on some pages at some screen sizes.
This commit pulls the watermark logic and styles into a new component and sets the sizes there.
Trello card: https://trello.com/c/RwwdXK95/690-change-size-of-preview-watermarks
=> Adjust preview watermark sizes

.github/workflows/rubyonrails.yml, spec/components/form_header_component/form_header_component_preview.rb, spec/components/form_header_component/view_spec.rb, spec/components/main_component/main_component_preview.rb, spec/components/main_component/view_spec.rb, spec/components/preview_component/preview_component_preview.rb, spec/components/preview_component/view_spec.rb, spec/helpers/application_helper_spec.rb, spec/lib/context_spec.rb, spec/requests/application_controller_spec.rb, spec/requests/errors_controller_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/requests/heartbeat_controller_spec.rb
There were a couple of issues with our specs in this repo
- spec filenames didn't match the filenames for the code they were testing
- specs main rspec descriptions where using strings rather than the class name that they were testing
- specs folder failed a number of rubocop errors
- rubocop was only checking files in the `app` folder as part of CI. This meant that when locally developing, we had to remember to only scan the app folder otherwise we would end up having to fix failed linting not related to our own code.
Trello card: https://trello.com/c/RKCviWz0/683-change-rubocop-settings-for-the-runner-to-include-specs-dir
=> Refactor specs

app/components/form_header_component/view.rb, app/controllers/forms/check_your_answers_controller.rb, app/controllers/forms/page_controller.rb, app/lib/context.rb, app/views/layouts/application.html.erb
Context.form was extremely confusing because when you looked at `current_context.form`, one may assume that it would return the form that the user is filling in. Instead it would just return the form id. Not only was this confusing but also it meant that for other form attributes we ended up created attributes in the context to play back the same attributes we had in the form already. There will be more refactors but I wanted to try keep them small and targetted.
Trello card:
=> Refactor Context form method uses form object and not just id

app/components/form_header_component/view.rb, app/controllers/forms/submit_answers_controller.rb, app/lib/context.rb, app/lib/event_logger.rb, app/services/form_submission_service.rb, app/services/log_event_service.rb, app/views/errors/repeat_submission.html.erb, app/views/forms/check_your_answers/show.html.erb, app/views/forms/page/show.html.erb, app/views/forms/privacy_page/show.html.erb, app/views/forms/submitted/submitted.html.erb, spec/components/form_header_component/view_spec.rb, spec/requests/forms/submit_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb
See individual commit messages:
- Use forms name rather than context.form_name
- Use forms start_page rather then context.form_start_page
- refactor form submission service (mostly renaming vars to help clarify what is being passed in and what a dev can expect
Trello card:
=> Use form's name/start page instead of context & refactor calls to form_submission_service

app/lib/context.rb, app/lib/step_factory.rb
Step Factory doesn't need that form submission email and context has a copy of the form data stored in  `form`. So there no real reason to use the submission_email method in context to get this info
Trello card:
=> Remove submission_email from Context

app/controllers/forms/check_your_answers_controller.rb, app/lib/context.rb, app/services/form_submission_service.rb, spec/services/form_submission_service_spec.rb
Its confusing to read `current_context.steps` and not realise that steps is actually the Question/answers that a user has completed and not all questions for a form.
Trello card:
=> Rename context steps method to complete_steps

spec/lib/hosting_environment_spec.rb
We no longer receive the following deprecation warning when running rspec.
```
Deprecation Warnings:
Using 'stub' from rspec-mocks' old ':should' syntax without explicitly enabling the syntax is deprecated. Use the new ':expect' syntax or explicitly enable ':should' instead.
Called from /Users/gds/forms-runner/spec/lib/hosting_environment_spec.rb:31:in `block (4 levels) in <top (required)>'.
If you need more of the backtrace for any of these deprecations to identify where to make the necessary changes, you can configure `config.raise_errors_for_deprecations!`, and it will turn the deprecation warnings into errors, giving you the full backtrace.
1 deprecation warning total
```
Trello card:
=> Address rspec depreciation warning about using stub

app/controllers/forms/base_controller.rb, app/controllers/forms/page_controller.rb, app/lib/context.rb, app/lib/journey.rb, app/lib/step_factory.rb, app/models/step.rb, spec/factories/models/pages.rb, spec/lib/context_spec.rb, spec/lib/event_logger_spec.rb, spec/requests/forms/base_controller_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/views/question/_address.html.erb_spec.rb, spec/views/question/_date.html.erb_spec.rb, spec/views/question/_name.html.erb_spec.rb, spec/views/question/_selection.html.erb_spec.rb
Adds basic routing support to forms-runner, by updating the next_page logic. A user should now be able to be routed to the goto page of the routing condition if they select a specific answer. They should be able to change their answer and continue through the form as expected. 
"Check your answers" page works by playing back the journey the user would have had to have gone through along with their answers. This means no changes were needed to support basic routing These "completed_steps" is also what is also used and played back to the submit form service email so again no changes were needed.
Trello card: https://trello.com/c/EZ67GrJQ/562-runner-changes-to-nextpage-logic-for-simple-routing
=> 562 runner changes to nextpage logic for simple routing

app/lib/step_factory.rb, app/models/page.rb, app/models/step.rb, spec/factories/models/pages.rb, spec/requests/forms/page_controller_spec.rb, spec/views/question/_address.html.erb_spec.rb, spec/views/question/_date.html.erb_spec.rb, spec/views/question/_name.html.erb_spec.rb, spec/views/question/_selection.html.erb_spec.rb
Suggest reviewing each commit made. 
- Simplify the params that we pass into Steps model
- Commit to show how to replicate the error we saw in AWS where existing live forms with missing routing_conditions raised an error
- Fix the error by handling the error within the Step model. If pages has routing_conditions method use it otherwise return an empty array which is what newer pages with not routing_conditions will return.
Trello card:
=> Fix missing routing conditions method

Gemfile, Gemfile.lock, README.md, app/controllers/application_controller.rb, config/settings.yml, spec/requests/application_controller_spec.rb, spec/requests/errors_controller_spec.rb
Uses the `settings` configuration files instead of the `SERVICE_UNAVAILABLE` env var to enable the service unavailable page.
forms-admin already uses the settings files for this, so this brings to two apps into alignemnt.
Trello card: None, but helps with https://trello.com/c/P9CEz21c/840-test-and-update-holding-page
=> Use settings instead of env to enable maintenance page

app/controllers/forms/page_controller.rb, app/lib/journey.rb, app/views/errors/goto_page_before_routing_page.html.erb, config/locales/errors.yml, spec/lib/journey_spec.rb, spec/requests/forms/page_controller_spec.rb
Blocks users from previewing or submitting a page when the page's route points to an earlier question in the form.
- shows an error page when this happens
- also resolves the underlying infinite loop issue in `journey.rb` that can cause the server to hang/crash if the user follows a looping route.
Trello card: https://trello.com/c/igNu5fny/819-block-users-from-previewing-a-draft-form-that-causes-endless-looping
=> Add before_action for goto_page_before_routing_page error

Dockerfile
Fixes an issue with x86 and ARM architectures supporting different versions of the [Alpine nodejs package](https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.17&repo=&arch=&maintainer=).
x86 architectures support 18.16.1 (so our Github action passed) but our build uses ARM, which currently only supports 18.16.0. Pinning to the minor version supports both, and should make build-breaking updates slightly less frequent.
=> Pin node to minor version 18.16 in Dockerfile

app/components/form_header_component/_index.scss, app/components/form_header_component/view.rb, app/lib/hosting_environment.rb, config/locales/en.yml, spec/components/form_header_component/view_spec.rb, spec/lib/hosting_environment_spec.rb
- Displays a tag with the name of the environment on non-production environments
- Unlike the [associated admin PR](https://github.com/alphagov/forms-admin/pull/508), we aren't adding a coloured border-bottom to the header. This is because we already use this border colour for denoting whether the form is in live, preview-live, or preview-draft mode.
- Adds a custom `app-header` CSS class to the header, so we can add our own styles without any risk of name collision with govuk-frontend styles
The tag colours for each environment are:
-  Pink for local
-  Green for dev
-  Yellow for staging
-  Blue for user research
Trello card: https://trello.com/c/DFOs5YuI/858-display-which-environment-a-user-is-accessing …
=> Add environment tags

config/locales/errors.yml
https://trello.com/c/kdBnaSzQ/84-change-the-content-for-the-maintenance-page-to-be-generic
This PR is to change the content for the maintenance page to be generic.
paired with @alice-carr
=> revert text on maintenance page

app/controllers/forms/page_controller.rb
This exception handling was created before we had a BaseController which PageController inherits from now.
[BaseController now handles the exception](https://github.com/alphagov/forms-runner/blob/94fcc37b2e924225ea2d3f36a1ef2288bc8749c2/app/controllers/forms/base_controller.rb#L10C5-L12C8) from any controller that inherits from it.
This will stop us randomly raising errors in sentry
Trello card: https://trello.com/c/KXVDn9V9/918-stop-stepfactory-from-raising-sentry-alerts
=> Remove obsolete exception handling for StepFactory

app/views/question/_address.html.erb, app/views/question/_date.html.erb, app/views/question/_name.html.erb, app/views/question/_national_insurance_number.html.erb
The application helper that called before these `.html_safe` already calls `.html_safe`
https://github.com/alphagov/forms-runner/blob/3575a7b3122d3f327ad2f4d90a936c1e64d15b33/app/helpers/application_helper.rb#L31
Trello card:
=> Remove unnecessary calls to html_safe

app/helpers/application_helper.rb, config/i18n-tasks.yml, spec/helpers/application_helper_spec.rb
This refactor addresses a few concerns.
1. `question_text_with_optional_suffix` application helper, used `html_safe` on both question text (supplied by form creators i.e user input) and mode_string. This meant that form creators could use script tags to create XSS attacks to any user of their form. Instead, we should only use `html_safe` on markup that we completely control and never trust data supplied by users
2. `question_text_with_optional_suffix` was doing a lot of extra work apart from just adding `(optional)` suffix to the question text. It was also responsible for adding what mode the question should read out to screenreaders. It was easier to split out adding mode span which could be useful to other parts of the application and not just this helper.
Trello card:
=> Prevent question text from injecting custom html tags (Security concern)

app/helpers/application_helper.rb, app/views/forms/page/show.html.erb, spec/helpers/application_helper_spec.rb
Preview draft/live were outputing escaped html for the mode which should have been visually hidden.
Trello card:
=> Fix escaping of html in the question page heading

app/components/question/base.rb, app/components/question/text_component/view.html.erb, app/components/question/text_component/view.rb, app/helpers/application_helper.rb, app/views/forms/page/show.html.erb, app/views/question/_long_text.html.erb, app/views/question/_single_line.html.erb, app/views/question/_text.html.erb, spec/components/question/text_component/text_component_preview.rb, spec/components/question/text_component/view_spec.rb
As part of this refactor it will mean that this answer type can now be easily ported to other apps because it doesn't rely on specific application specific code. There is only one dependency for it which is the govuk form builder gem.
Trello card: https://trello.com/c/mGqPIFkV/237-switch-the-runner-to-use-components-rather-than-partials
=> Convert text question partial to view component

app/components/question/national_insurance_number_component/view.html.erb, app/components/question/national_insurance_number_component/view.rb, app/views/forms/page/show.html.erb, app/views/question/_national_insurance_number.html.erb, spec/components/question/national_insurance_number_component/national_insurance_number_component_preview.rb, spec/components/question/national_insurance_number_component/view_spec.rb, spec/components/question/number_component/number_component_preview.rb
As part of this refactor it will mean that this answer type can now be easily ported to other apps because it doesn't rely on specific application specific code. There is only one dependency for it which is the govuk form builder gem.
Trello card:  https://trello.com/c/mGqPIFkV/237-switch-the-runner-to-use-components-rather-than-partials
=> Convert National Insurance Number to component

Gemfile, Gemfile.lock, app/components/main_component/view.rb, app/controllers/component_preview_controller.rb, app/views/forms/check_your_answers/show.html.erb, app/views/forms/page/show.html.erb, app/views/forms/privacy_page/show.html.erb, app/views/layouts/application.html.erb, app/views/layouts/base.html.erb, config/application.rb, config/environments/test.rb, config/settings.yml, spec/components/form_header_component/form_header_component_preview.rb, spec/components/main_component/main_component_preview.rb, spec/features/components/preview_components_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb, spec/support/axe_feature_helpers.rb, spec/support/capybara_headless_chrome.rb
- Adds axe-core-rspec for running automated accessibilty checks in our tests (see gem info below)
- Adds a feature tests to our existing components, which runs against the component previews and checks for accessibility issues. 
- Adds a couple of convenience methods:
- Inside an `it "..." do` block within a feature test, you can use the methods `expect_page_to_have_no_axe_errors(page)` and `expect_component_to_have_no_axe_errors(page)` to assert that the page or component the browser is currently on doesn't have any errors.
- Adds a `base` layout which all component previews now use by default. The `application.html.erb` layout now inherits from this base layout
Trello card: https://trello.com/c/BARdutlj/916-explore-adding-automated-accessibility-tests
This PR adds a new gem, …
=> Add automated accessibility tests

app/components/question/phone_number_component/view.html.erb, app/components/question/phone_number_component/view.rb, app/views/forms/page/show.html.erb, app/views/question/_phone_number.html.erb, spec/components/question/phone_number_component/phone_number_component_preview.rb, spec/components/question/phone_number_component/view_spec.rb
As part of this refactor it will mean that this answer type can now be easily ported to other apps because it doesn't rely on specific application specific code. There is only one dependency for it which is the govuk form builder gem.
Asa separate commit, I also refactored this component to use `type="tel"` rather than `type="text"` as recommended by GOV.UK Design System https://design-system.service.gov.uk/patterns/telephone-numbers/
Trello card: https://trello.com/c/mGqPIFkV/237-switch-the-runner-to-use-components-rather-than-partials
=> Convert phone field to component

Dockerfile
Node is used to compile the front end assets in the first stage of the docker build process. Pin to the version 18 major release but allow pulling of the current minor and patch based upon that available in the Alpine package repo.
Fixes failing docker build https://github.com/alphagov/forms-runner/actions/runs/5598875560/jobs/10239113773?pr=371#step:3:60
Note that 18.16 is no longer available: https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.18&repo=&arch=&maintainer=
Correctly installs 18.17 https://github.com/alphagov/forms-runner/actions/runs/5598999056/jobs/10239396992?pr=376#step:3:91
It seems appropriate to pin to the major version but flex on minor and patches to the latest available on Alpine.
=> Bump Node Version

README.md, app/lib/event_logger.rb, app/lib/json_log_formatter.rb, config/application.rb, config/environments/production.rb, spec/lib/event_logger_spec.rb, spec/lib/json_log_formatter_spec.rb, spec/requests/forms/base_controller_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/requests/forms/submit_answers_controller_spec.rb
Changes the log format to be entirely JSON format. This aids searching and reporting in Splunk since it is able to understand the structured log format and automatically extract each key for use. It also formats the log event with syntax highlighting making it simpler to understand.
Before the change:
After the change in dev:
This also permits simpler splunk queries that make direct reference to any key without needing to first `rex` out content from the log event. E.g. 
```
index="*forms*" source="*forms-runner-dev*" event=form_submission
| stats count by form
```
- The first commit refactors the specs so that the request specs expect on the higher level logging functions without making direct reference to the output format which is an implementation detail from their concern.
-  The …
=> Structured logging

app/components/question/organisation_name_component/view.html.erb, app/components/question/organisation_name_component/view.rb, app/views/forms/page/show.html.erb, app/views/question/_organisation_name.erb, spec/components/question/organisation_name_component/organisation_name_component_preview.rb, spec/components/question/organisation_name_component/view_spec.rb
As part of this refactor it will mean that this answer type can now be easily ported to other apps because it doesn't rely on specific application specific code. There is only one dependency for it which is the govuk form builder gem.
Trello card: https://trello.com/c/mGqPIFkV/237-switch-the-runner-to-use-components-rather-than-partials
=> Convert organisation name field to component

package-lock.json, package.json
Adds the missing `@babel/preset-env` npm package. Without this, the jest tests will break if you don't have babel installed globally on your machine.
Copy of @chao-xian's change in forms-admin yesterday (https://github.com/alphagov/forms-admin/pull/547)
=> Add babel/preset-env

.github/workflows/setup_rails/action.yml, .github/workflows/test.yml, jest.config.js
Having the different bits of the `build_and_test` task run in parallel should speed them up (since they're not running in series) and make it clearer which task(s) are failing.
To accomplish that, this PR:
- Moves the linting / static analysis tasks into a new job `lint`
- Adds the jest tests to the `build_and_test` job (we don't have any Jest tests in this repo yet, because we haven't written any custom JS here, so there's no point it having its own action)
- Allows the `build_and_test` and `lint` jobs to run in parallel, which should make them slightly quicker 
- Creates a new [composite workflow](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) `build/action.yml` which allows us to run the common rails setup tasks before jobs rather than write them out …
=> Parallelize test and lint actions

app/views/application/accessibility_statement.html.erb
The link to https://submit.forms.service.gov.uk goes to a 404. 
The purpose of this URL is to make it clear what the accessibility statement applies to, rather than being a link people need to follow.
So this change makes that clearer and removes the active link.
Trello card:https://trello.com/c/6sHINqj1/971-fix-broken-link-on-accessibility-statement-for-individual-forms
=> Remove 404 link from accessibility_statement.html.erb

app/components/question/base.rb, app/controllers/forms/check_your_answers_controller.rb, app/helpers/application_helper.rb, app/models/question/question_base.rb, app/views/question/_address.html.erb, app/views/question/_name.html.erb, app/views/question/_selection.html.erb, config/locales/en.yml, spec/components/question/date_component/date_component_preview.rb, spec/components/question/date_component/view_spec.rb, spec/components/question/email_component/email_component_preview.rb, spec/components/question/email_component/view_spec.rb, spec/components/question/national_insurance_number_component/national_insurance_number_component_preview.rb, spec/components/question/national_insurance_number_component/view_spec.rb, spec/components/question/number_component/number_component_preview.rb, spec/components/question/number_component/view_spec.rb, spec/components/question/organisation_name_component/organisation_name_component_preview.rb, spec/components/question/organisation_name_component/view_spec.rb, spec/components/question/phone_number_component/phone_number_component_preview.rb, spec/components/question/phone_number_component/view_spec.rb, spec/components/question/text_component/text_component_preview.rb, spec/components/question/text_component/view_spec.rb, spec/helpers/application_helper_spec.rb, spec/models/question/selection_spec.rb, spec/support/shared_examples/question_models.rb
As part of the refactoring of the components we forgot to add "(optional)" to the question label if the question is optional. This is because before  partials were responsible for calling a helper method which worked out whether or not to add "(optional)" suffix and view mode. This is a lot for a helper method. The components are "dumb" and just handle simple presentation. Manipulating data or business logic is best controlled outside a component.
This moves the business logic of whether or not to add "(optional)" from the helper method to the question model instead. It makes testing this code a lot easier for both the helper method and the new model method.
Trello card: https://trello.com/c/mGqPIFkV/237-switch-the-runner-to-use-components-rather-than-partials
=> Fix missing optional copy in labels from components

Gemfile, Gemfile.lock
Webdrivers isn't necessary with selenium-webdrivers of version 4.10 and higher. Webdrivers cannot currently install and manage v115 of Chromedriver.
Gets CI running again
There is more information about the webdrivers issues and their recommendation to remove webdrivers and use selenium-webdrivers + 4.10 https://github.com/titusfortner/webdrivers/issues/247
=> Remove webdrivers

Dockerfile
We have two sets of node dependencies in our package.json - `dependencies` which are packages we need to ship with our app, and `devDependencies` which we need to build our app (or develop locally) but don't need to ship with our app at run time. We have many more `devDependencies` than we do `dependencies`.
In our Docker builds we install our devDependencies so that we can run the frontend asset build. We then copy the entire `app` folder into our runtime environment. Shipping these extra dependencies at run time increases our app's attack surface, so we should remove them once we no longer need them. 
In this PR, I'm running `npm ci --only=production` at the end of the build stage, which will clear out our node_modules file and install only our production dependencies. This means none …
=> Use npm ci and remove devDependencies after build

spec/components/question/date_component/view_spec.rb, spec/components/question/email_component/view_spec.rb, spec/components/question/national_insurance_number_component/view_spec.rb, spec/components/question/number_component/view_spec.rb, spec/components/question/organisation_name_component/view_spec.rb, spec/components/question/phone_number_component/view_spec.rb, spec/components/question/text_component/view_spec.rb
Rspec was alerting the following warning:
`Checking for expected text of nil is confusing and/or pointless since it will always match. Please specify a string or regexp instead.`
This was result of refactoring we did in https://github.com/alphagov/forms-runner/pull/385 to move the logic of adding (optional) to the question text to be part of the question model.
=> Component view spec not using correct attributes in test

spec/components/question/date_component/view_spec.rb, spec/components/question/email_component/view_spec.rb, spec/components/question/national_insurance_number_component/view_spec.rb, spec/components/question/number_component/view_spec.rb, spec/components/question/organisation_name_component/view_spec.rb, spec/components/question/phone_number_component/view_spec.rb, spec/components/question/selection_component/selection_component_preview.rb, spec/components/question/text_component/view_spec.rb
Preview components were failing in dev but not on localhost
NameError
uninitialized constant Question::SelectionComponent::SelectionComponentPreview::DataStruct (NameError)
ref: https://govuk-forms.sentry.io/issues/4355784060/?project=6576261&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=0
=> Replace DataStruct with OpenStruct

app/components/question/address_component/view.rb, app/components/question/base.rb, app/components/question/date_component/view.html.erb, app/components/question/email_component/view.html.erb, app/components/question/name_component/view.rb, app/components/question/national_insurance_number_component/view.html.erb, app/components/question/number_component/view.html.erb, app/components/question/organisation_name_component/view.html.erb, app/components/question/phone_number_component/view.html.erb, app/components/question/selection_component/view.rb, app/components/question/text_component/view.html.erb, app/lib/question_register.rb, app/models/question/question_base.rb, spec/components/question/address_component/view_spec.rb, spec/components/question/date_component/view_spec.rb, spec/components/question/email_component/view_spec.rb, spec/components/question/national_insurance_number_component/view_spec.rb, spec/components/question/number_component/view_spec.rb, spec/components/question/organisation_name_component/view_spec.rb, spec/components/question/phone_number_component/view_spec.rb, spec/components/question/selection_component/view_spec.rb, spec/components/question/text_component/view_spec.rb, spec/factories/models/pages.rb, spec/factories/models/question/address.rb, spec/factories/models/question/selection.rb, spec/lib/question_register_spec.rb
- refactors how we set answer type view components tag and font size
- passes page_heading/additional_guidance_markdown to the QuestionRegister so we can use it on the page and components.
- adjust all the answer type view components to toggle between using heading and native legend/labels
Trello card: https://trello.com/c/R5aZ0LWX/950-update-forms-runner-to-display-additional-guidance-to-form-fillers
=> Toggle page headings depending on if question has guidance

app/components/question/text_component/view.html.erb, spec/components/question/text_component/view_spec.rb
Trello card: https://trello.com/c/yzKobeRo/977-single-line-text-inputs-should-be-wider
We want the width of the input to be at least two-thirds the width of the page. This commit just removes the `one-half` width qualifier, so the input fluidly fills the space available. As the form group is in a two-thirds grid column, this fulfils the requirement.
<details>
<summary><h3>Screenshots of changes</h3></summary>
</details>
I went through the all question types form by hand and checked that only the single line of text question was affected.
=> Increase width of single line of text input

Dockerfile, Gemfile, Gemfile.lock, app/components/guidance_component/view.html.erb, app/components/guidance_component/view.rb, app/lib/markdown_scrubber.rb, app/views/forms/page/show.html.erb, spec/components/guidance_component/guidance_component_preview.rb, spec/components/guidance_component/view_spec.rb, spec/lib/markdown_scrubber_spec.rb
Trello card: https://trello.com/c/bfw5T1Ny/975-create-guidance-component-in-forms-runner
Adds a new component for displaying the page heading and rendering the markdown guidance.
As part of that I've installed the [govuk-forms-markdown](https://github.com/alphagov/govuk-forms-markdown) gem and added git to our Docker build.
Note that this doesn't actually add the new component to the view - that'll be done either as part of https://trello.com/c/R5aZ0LWX/950-update-forms-runner-to-display-additional-guidance-to-form-fillers or in a separate PR once that one's merged.
=> Add guidance component

package.json
Runs the JS and style linting sequentially instead of in parallel. Running them in parallel meant that the linting tasks wouldn't break the build unless _both_ lints failed, so we saw issues being missed in forms-admin (see https://github.com/alphagov/forms-admin/pull/605).
The time saving from running them in parallel is negligible, so there shouldn't be any noticeable drawbacks to changing this.
=> Run linting tasks sequentially

Gemfile, Gemfile.lock
Trello card: https://trello.com/c/16f0EohC/984-add-validations-warnings-to-govuk-forms-markdown-gem
=> Bump govuk-forms-markdown gem from 0.2.1 to 0.3.0

config/puma.rb
Trello card: [](https://trello.com/c/YyrG1YHG/114-investigate-502-between-alb-and-forms-api)
This PR adds a persistent_time of 75 to the puma config so that it is higher than the ALB idle time as this was causing 502s
=> add persistent timout of 75 to puma

Gemfile, Gemfile.lock
The web-console gem is never used. It simply provides a Rails console in the browser. It also seems to be throwing an error:
```
Web Console is activated in the test environment. This is
usually a mistake. To ensure it's only activated in development
mode, move it to the development group of your Gemfile:
gem 'web-console', group: :development
If you still want to run it in the test environment (and know
what you are doing), put this in your Rails application
configuration:
config.web_console.development_only = false
```
since we put everything into the [default rake task](https://github.com/alphagov/forms-runner/pull/386) but can't work out why so removing for now rather than wasting more time on debugging. 
- …
=> Remove web-console gem

app/views/forms/check_your_answers/show.html.erb, config/locales/en.yml
Trello card: https://trello.com/c/eyM4iBwz
PR fixes two small things on the 'Check your answers' page:
<details><summary>Screenshots</summary>
Before:
After:
</details>
<details><summary>Screenshots</summary>
Before:
After:
</details>
=> Content fixes

Gemfile, Gemfile.lock, app/controllers/forms/submit_answers_controller.rb, app/services/cloud_watch_service.rb, app/services/log_event_service.rb, spec/requests/forms/submit_answers_controller_spec.rb, spec/services/cloud_watch_service_spec.rb, spec/services/log_event_service_spec.rb
Trello card: https://trello.com/c/sSoCpSfL/1059-save-as-a-metric-in-cloudwatch-when-a-form-is-submitted
This PR contains a couple of changes:
* Refactoring the LogEventService to incorporate the EventLogger for for submissions. This involved moving the EventLogger call into here. 
* Adding a call to cloudwatch event logging. This is triggered when a form is submitted, and sends an event to Cloudwatch. 
This is a bit of a pain to test locally, but it can be done. You'll need to run the app with AWS credentials, which is doable from the command line with something like `$ gds-cli aws forms-dev-admin -- bundle exec rails s`. This will start the app up with the appropriate credentials to enable Cloudwatch logs. When you submit a form, it will send the form_id as part of a metric to …
=> 1059 increment metric in cloudwatch when a form is submitted

app/lib/event_logger.rb, spec/lib/event_logger_spec.rb
To make it easier to correlate log messages from `event_logger` with other log messages, add the `form_id` to the log message. In our lograge configuration we use the form ID instead of the form name.
=> Log form_id with events

app/controllers/application_controller.rb, app/lib/step_factory.rb, app/models/page.rb, config/application.rb
When searching Splunk for requests related to a particular page of a form it would be nice to be able to construct a query with `page_id=n`.
This PR adds the page ID to the log event JSON payload so that this will be possible in future.
=> Log page ID and slug with requests

package.json
Trello card: None
Our current [browserslist](https://browsersl.ist/) query unintentionally includes IE11, which does not support CSS grid but does support a vendor prefixed version with a different API. 
This means that when we use CSS grid syntax, Autoprefixer will automatically generate CSS using IE11's vendor prefixed grid syntax. This can cause broken layouts when we rely on CSS grid's automatic placement, which isn't supported in the IE11 implementation. In this commit we add 'and not dead' to the query to exclude unsupported browsers like IE11.
In forms-admin this change is included in https://github.com/alphagov/forms-admin/pull/663
- Are there …
=> Fix browserslist config to prevent unwanted Autoprefixer styles

app/controllers/forms/base_controller.rb, app/services/cloud_watch_service.rb, app/services/log_event_service.rb, spec/requests/forms/base_controller_spec.rb, spec/services/cloud_watch_service_spec.rb, spec/services/log_event_service_spec.rb
Trello card: [1072-save-as-a-metric-in-cloudwatch-when-a-form-is-started](https://trello.com/c/W2bh0Wgq/1072-save-as-a-metric-in-cloudwatch-when-a-form-is-started)
This introduces logging in CloudWatch for forms getting started. It's piggybacking on what used to be the existing EventLogger trigger, which has now been refactored into the LogEventService.
Very similar to the form submission logging. 
=> 1072 save as a metric in cloudwatch when a form is started

app/frontend/entrypoints/application.scss
Trello card: none
This message is appearing because ie8 support is deprecated in govuk-frontend. We don't support Internet Explorer 8 anyway, so we can suppress this warning.
Test this by running `bin/setup` or `bin/vite build` and observing that the FE build no longer gives us the following warning: 
> The govuk-if-ie8 mixin is deprecated and will be removed in v5.0. To silence this warning, update $govuk-suppressed-warnings with key: "ie8"
I've also made this change in forms-admin (https://github.com/alphagov/forms-admin/pull/688) and forms-product-page (https://github.com/alphagov/forms-product-page/pull/85).
- Do the commit messages explain why the changes were …
=> Suppress IE8 warning

app/controllers/forms/page_controller.rb
This was caused by a recent refactor where the "Edit question" page url was changed
I dont think we can write a unit test for this because ultimately we would need to test if the url actually works and returns the edit page we expecting to see. I think this would need to be done as part of the end-to-end tests, 
See:
[alphagov/forms-admin@`5a482b5` (#659)](https://github.com/alphagov/forms-admin/pull/659/commits/5a482b5449f6f2bb770bbc2806eca47ce6dff6f6)
Trello card: https://trello.com/c/ZVmsaTwq/1115-edit-this-question-returning-404
- Has all relevant documentation …
=> Fix broken "edit this question" link

app/controllers/forms/submit_answers_controller.rb, app/services/form_submission_service.rb, spec/services/form_submission_service_spec.rb
We have one method which we call to email form submissions but we
want to add other functionality to form_submission_service. eg
once form has been submitted then send confirmation email to form
filler. This PR is the groundwork for these enhancements
Trello card: https://trello.com/c/A7YmTtGq/1104-send-confirmation-email-to-form-filler
=> refactor form_submission_service to have a main method to called

app/controllers/forms/check_your_answers_controller.rb, app/mailers/form_submission_confirmation_mailer.rb, app/mailers/form_submission_mailer.rb, app/services/form_submission_service.rb, config/settings.yml, spec/config/settings_spec.rb, spec/factories/models/forms.rb, spec/mailers/form_submission_confirmation_mailer_spec.rb, spec/mailers/form_submission_mailer_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb
- Adds new email template id for confirmation emails
- Introduces a new mailer to send confirmation emails to form fillers
- Calls the new mailer from form_submission_service. if the feature flag is enabled and form filler provided a confirmation email
- refactors form submission service to accept a form_object instead of single params being passed in.
- fixes the time format used in e-mails to not include seconds and to use 12-hour clock
Trello card: https://trello.com/c/A7YmTtGq/1104-send-confirmation-email-to-form-filler
- Has all relevant documentation been …
=> Send confirmation email to form fillers

app/services/form_submission_service.rb, spec/services/form_submission_service_spec.rb
Currently, if a form is missing "What happens next" or support contact email the attempt to send an email will fail and give the user a 500 error. We want to handle this more gracefully because it should only occur when a draft form hasn't been fully completed. We will do this by not calling the email confirmation mailer.
- fixes https://govuk-forms.sentry.io/issues/4570951866/?project=6576261
Trello card: https://trello.com/c/A7YmTtGq/1104-send-confirmation-email-to-form-filler
=> dont send confirmation email if forms "what happens next" or "support contact details" missing

app/components/support_details_component/view.html.erb, app/lib/context.rb, app/services/form_submission_service.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb
Adds phone number and online contact methods if they are setup for the form
Trello card: https://trello.com/c/r4RTqUPa/1143-add-all-support-contact-detail-methods-to-confirmation-email
=> Adding Support contact details for phone and online methods

app/controllers/forms/check_your_answers_controller.rb, app/services/log_event_service.rb, spec/requests/forms/check_your_answers_controller_spec.rb
Trello card: https://trello.com/c/g4Z4kg6e/1135-we-log-a-new-event-so-we-can-tell-how-many-users-requested-confirmation-emails
Adds a new splunk log event for tracking confirmation email requests.
When a user submits their answers, pass whether they opted in to the confirmation email into the LogEventService. If they did opt in, log a new event `requested_email_confirmation` to Splunk, so that we can understand how useful this feature is.
=> Log confirmation email opt-ins

Gemfile, Gemfile.lock
We are using config gem instead of dotenv-rails [[1]], so we should remove it.
[1]: https://github.com/alphagov/forms-admin/commit/3ffbf1598871e36332d75fa200d62aaf4e0d60f1
=> Remove dotenv-rails gem

app/services/log_event_service.rb, spec/services/log_event_service_spec.rb
Trello card: https://trello.com/c/Zhxsdx7i/1170-fix-completion-rate-metric
Moves the CloudWatch form started event so that's it's triggered when the first page of the form is saved. This will help avoid metrics going wonky when linking to the first page of a form directly, as this bypasses the form_start event.
=> Move the CloudWatch form start to first page save event

app/components/question/base.rb, spec/components/question/base_spec.rb
Trello card: 
Fixes an issue with the wrong heading size and tag being returned for a question with an empty string as its `page_heading`. We think this arises when a page has detailed guidance which is subsequently removed.
=> Use blank? instead of nil? in heading size check

app/controllers/application_controller.rb, config/application.rb
https://trello.com/c/VCUrEL0y/1172-log-hash-of-session-id
It's difficult to trace users behaviour over multiple pages.
Individual page requests aren't linked by any values.
Guessing based on URLs and client IP is the only way to reconstruct user's journeys through forms.
This commit adds a hash of the user's session id to the request logs.
This value is will be stable across individual page request so can be used to connect multiple requests.
We don't log the session id directly as it would leak information that could be used to retrieve user's data.
The session id is a random string of lowercase hex digits, for example, 'ffdc96b6cd5a8f8601f6b11352e6d9c2'.
It's stored directly inside the cookie sent to the form-filler's browser when they visit the service. We use it as the key when …
=> Log hash of session.id if session exists

Dockerfile
[Trello card](https://trello.com/c/S3jDIsp0/243-update-app-docker-images)
This PR updates the docker alpine version from 3.17 to 3.18
This has been deployed to dev and is working as expected. 
=> Bump Docker Alpine version to 3.18

config/application.rb, config/initializers/logging.rb, spec/config/initializers/logging_spec.rb
Move the logging configuration from application.rb to an initializer. This makes it easier to apply it to test and production but not development environment.
The desired effect is that when developing locally, the default Rails logger is used. Our default logger, lograge, outputs structured log messages that are optimised for machine readability, rather than human readability.
If a developer wants to see what the production logging looks like they can change the RAILS_ENV environment variable or comment out the conditional in the initializer.
This also means we can be aware of what we are missing in our lograge configuration that we could be getting from Rails.
- …
=> Use default Rails logger for development

app/services/cloud_watch_service.rb, config/settings.yml, spec/config/settings_spec.rb, spec/services/cloud_watch_service_spec.rb
Trello card: https://trello.com/c/eGLh3RTp/1184-prevent-forms-runner-and-forms-admin-cloudwatch-requests-when-in-unsuitable-environments
Now that https://github.com/alphagov/forms-deploy/pull/435 is in, we can make use of the environment variable that it's set to turn off metrics in dev and user research. 
This PR makes the CloudWatchService check the environment variable `cloudwatch_metrics_enabled` before it continues making CloudWatch requests, and breaks early if they're disabled. 
=> 1184 prevent forms runner and forms admin cloudwatch requests when in unsuitable environments

app/controllers/forms/check_your_answers_controller.rb, app/form_objects/email_confirmation_form.rb, app/mailers/form_submission_confirmation_mailer.rb, app/services/form_submission_service.rb, app/views/forms/check_your_answers/show.html.erb, spec/factories/form_objects/email_confirmation_form.rb, spec/form_objects/email_confirmation_form_spec.rb, spec/mailers/form_submission_confirmation_mailer_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
Trello card: https://trello.com/c/bnWjTvpU/1197-add-an-e2e-test-to-cover-adding-confirmation-email-being-filled-in-on-forms 
We want to be able to find the confirmation email for a form filler in the GOV.UK Notify API. This is currently for our end to end tests, so we can check that a notification is actually queued.
This commit adds a notification reference for the confirmation email, similar to how we already have a notification reference for the email with the submission. To make it easier for any humans looking at the Notify logs to associate the two emails together, we give them both the same random prefix, and differentiate with a human readable suffix.
- Do …
=> Add notification reference for confirmation email

app/controllers/forms/check_your_answers_controller.rb, app/services/form_submission_service.rb, app/services/log_event_service.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/services/log_event_service_spec.rb
We'd like to monitor submissions of preview forms in case form previews are not being used as intended. This PR refactors existing submission logging into the FormSubmissionService, and adds logging of preview form submissions separately from live form submissions, so that we can setup alerts off the logs.
Trello card: https://trello.com/c/g4FkBxx8
=> Add logging of submission of form previews

app/components/preview_banner_component/view.html.erb, app/components/preview_banner_component/view.rb, app/views/layouts/base.html.erb, config/locales/en.yml, spec/components/preview_banner_component/preview_banner_component_preview.rb, spec/components/preview_banner_component/view_spec.rb
For both live and draft previews, show a notification banner telling the user not to enter personal information. This is a mitigation for the use of trial accounts to collect information via form previews, even though they can't make forms live.
This is implemented using a separate `PreviewBannerComponent` rather than making changes to the `PreviewComponent` to keep them isolated from one another, but if people would prefer I'm open to merging the components into one.
Trello card: https://trello.com/c/6ZGD5RAE
=> Add notification banner for form previews

config/environments/development.rb
During the [upgrade to Rails 7.1.1](https://github.com/alphagov/forms-runner/pull/445/files#diff-d3c4b3f41072daa416f1920511e9b2e26caea8c5cec0a14cb9508589a4dafa47L62-L64) we removed config for `unsafe_session_storage` from our dev environment. This meant that without a `REDIS_URL` set, you weren't able to get things running locally. 
With this change, you can either run the server with a `REDIS_URL` set, which will store things in redis - or you can not set it and store stuff in cookies. 
This only seems to be an issue when running the server with `bundle exec rails s`, and not with `bin/dev` - unless you didn't have a `.env` file with a `REDIS_URL` set, in which case you may have seen it with `bin/dev`.
=> Adding config for unsafe_session_storage for local dev

app/models/question/date.rb, config/locales/en.yml, spec/models/question/date_spec.rb
Year fields should not accept two digits. Instead of checking the length of year which would mean that 0000 to 0999 would be valid dates, I instead check that year is between 1000 and 9999. This isn't exactly ideal. Having checked this with a designer, we decided to do this check and allow us to later add more refined validations which could be configured by form creators.
This follows the GOV.UK Design System pattern to ensure years are 4-digit numbers https://design-system.service.gov.uk/components/date-input/#if-the-date-is-incomplete
Trello card: https://trello.com/c/QAyMX8OZ/1224-year-input-for-the-date-answer-type-allows-user-to-only-enter-2-digits
- Do the …
=> enforce 4-digit year field for date answer types

spec/features/fill_in_and_submit_form_spec.rb, spec/support/axe_feature_helpers.rb
Trello card: https://trello.com/c/BP0bsQOf/1171-add-beginnings-of-missing-feature-tests-to-the-runner
This adds a basic feature test that covers filling in and submitting a form. 
There's also a change to our Axe check helper, which skips checking radio buttons for the `aria-allowed-attr` rule. This is a rule that probably shouldn't be catching our use of `aria-expanded="false"` as explored in [this thread](https://github.com/alphagov/govuk-frontend/issues/979).
I've opted to turn the email confirmation feature on in this test, as it's currently off by default. I kind of got most of the way through writing the tests before realising I'd turned it on locally, and it felt a bit pointless removing the opt-out-of-email-confirmation step in the test just because we haven't removed the feature …
=> Add fill and submit form feature test

spec/spec_helper.rb
The `--only-failures` and `--next-failure` options in RSpec make it much quicker to re-run tests that have failed, however they need the `example_status_persistence_file_path` configuration to be set [[1]].
This commit tells RSpec to save a file `examples.txt` into the a new folder in the Rails app's `tmp` folder; this seems like as good a place as any, as it's already ignored by git and docker, and is clearly named.
[1]: https://rspec.info/features/3-12/rspec-core/command-line/only-failures/
=> Configure RSpec to allow the --only-failures CLI option

Gemfile, Gemfile.lock, app/mailers/form_submission_confirmation_mailer.rb, app/models/form.rb, app/services/form_submission_service.rb, app/views/forms/submitted/submitted.html.erb, spec/factories/models/forms.rb, spec/lib/context_spec.rb, spec/mailers/form_submission_confirmation_mailer_spec.rb, spec/models/form_spec.rb, spec/requests/forms/base_controller_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/views/forms/submitted/submitted.html.erb_spec.rb
Trello card: 
Removes some of the code that was added for the `what_happens_next_text` -> `what_happens_next_markdown` switchover. Mostly consists of renaming or removing references to `what_happens_next_text`, but also includes:
- removing a redundant method from the form model
- removing an unused gem
See individual commits for details.
=> Clean up what happens next markdown changes

app/form_objects/email_confirmation_form.rb, app/services/form_submission_service.rb, app/views/forms/check_your_answers/show.html.erb, config/settings.yml, config/settings/development.yml, spec/config/settings_spec.rb, spec/features/email_confirmation_spec.rb, spec/features/fill_in_and_submit_form_spec.rb, spec/form_objects/email_confirmation_form_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
Trello card: https://trello.com/c/bXjqCIVe/1192-remove-confirmation-email-feature-flag
This feature is enabled in all of our environments, and we've seen from our analytics that it's very popular, so we can safely remove the feature flag.
Still to come:
-   removing the flag variables from forms-deploy
=> Remove email_confirmations_enabled feature flag

app/controllers/forms/page_controller.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/requests/forms/privacy_page_controller_spec.rb, spec/requests/forms/submitted_controller_spec.rb
Trello card: https://trello.com/c/9sjKA9FO/238-form-runner-improve-request-tests
Adds request specs for missing scenarios in the controllers. Includes:
- test for the check your answers page's error handling
- validation tests for the page controller
- privacy page controller request specs
- submitted controller request specs
Also includes a fix for a missing status code that was highlighted by one of the new tests:
- Fix missing HTTP status on page controller 
=> Improve request test coverage

app/components/form_header_component/view.rb, spec/components/form_header_component/view_spec.rb
Trello card: https://trello.com/c/VeOkfpZv/1250-update-forms-runner-to-govuk-frontend-v5
In #535 we updated the tags to reflect the new tag casing rules in version 5 of govuk-frontend. Unfortunately, the 'production' text was not updated to 'Production' everywhere, so the logic for hiding the environment tag in production broke.
This PR fixes the problem, and updates the 'production' check to look at the translation directly, so that the environment check will stay up to date with any future changes to this text.
=> Fix visible production environment tag

app/components/form_header_component/_index.scss, app/components/preview_component/view.rb, spec/components/preview_component/view_spec.rb
Trello card: https://trello.com/c/RFWi2tB5/1401-update-draft-and-live-tags
Changes the colour of 'live' tags to turquoise, and 'draft' tags to yellow. Also:
- adds the tag selector to the tests, so we can check the right colours are appearing.
- updates the colour of the bar under the header to match the  tag.
Live preview:
Draft preview:
=> Change live and draft tag colours

config/application.rb, config/environments/production.rb
Making logging consistent across our apps.
Otherwise every environment was getting debug output in the stdout. Also this is closer to how Rails is set up, which hopefully means we have less diversion to help with future upgrades.
=> Move stdout logging back to prod as the default

config/settings.yml, spec/config/settings_spec.rb
Update the example value for `Settings.forms_api.auth_key` to match what's currently in our local Docker Compose configuration [[1]].
[1]: https://github.com/alphagov/forms-deploy/blob/4fc8d5060990772e095200e534bdf6a0554f0739/local/docker-compose.yml#L43
=> Fix example forms-api auth key

config/routes.rb, spec/requests/application_controller_spec.rb
rails 7.1 introduced a health check endpoint by default. This default endpoint is called `/up`. Instead of returning 200 with the body response of `PONG`, it will return 200 if the app is healthy and it will output a html page with the background color set to green. If there is an issue it will return 500 error and the html page will have a red background.
We will need to update our infrasture to use /up instead `/ping` and to check the response code instead of the response body of PONG
see https://github.com/rails/rails/blob/f481353150c100dbd944d5aa84f2480264cd723c/railties/lib/rails/health_controller.rb
Trello card: https://trello.com/c/J0l5SpeE/1417-use-rails-default-healthcheck-endpoint
- Is it …
=> replace custom health check with rails default

Gemfile.lock
Running `bundle install` on main modified the gemfile.lock by adding this missing platform.
Trello card: 
=> add darwin-23 to platforms in gemfile.lock

app/components/form_header_component/view.rb, spec/components/form_header_component/view_spec.rb
Trello card: https://trello.com/c/LtOJrgEO/1173-make-govuk-home-page-link-go-to-my-forms-in-preview 
=> Change header hompage link to forms-admin homepage when in preview mode

app/controllers/application_controller.rb, config/application.rb, spec/requests/application_controller_spec.rb
We want to be able to correlate our Elastic Load Balancer logs with app logs. This is particularly useful when there is a `460` error because the client has closed the connection for taking too long.
This PR adds the `X-Amzn-Trace-Id` header [[1]] to our request logging.
[1]: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html
=> Add AWS application load balancer trace ID to logs

app/controllers/forms/page_controller.rb, spec/requests/forms/page_controller_spec.rb
The `question_number` field was omitted during the recent refactor to logging[[1]]. This adds it back in. Note that `question_number` is the sequential position of the question with reference to the form (e.g. the first or second question in the form) and the `page_id` is the unique identifier of the page in our records.
[1]: https://github.com/alphagov/forms-runner/pull/598
Puts question_number back into the logs to help with analytics.
I have run this locally and seen that `question_number` appears as expected.
=> Log Question_Number

app/components/support_details_component/view.html.erb, spec/components/support_details_component/view_spec.rb
Trello card: https://trello.com/c/72qe9ctA/1373-bug-with-find-out-about-call-changes-link 
The link to "Find out about call charges" was missing a href due to a typo. This commit fixes the component template and adds a test to prevent regression.
=> Fix call charges link

app/controllers/application_controller.rb, app/controllers/forms/check_your_answers_controller.rb, spec/controllers/application_controller_spec.rb
We want to log exceptions that happen in the `submit_answers` action even if we rescue them.
Unfortunately I couldn't find an easy way to hook into the standard Rails exception logging mechanisms at the same time as using `rescue` or `rescue_from`; so this commit adds a new method to our application controller that has the same behaviour.
=> Add exception logging to submit your answers action

app/lib/event_logger.rb
`tap` mutates the hash and then returns it. This meant that the additional event data was being added to the logging_context and logged by LogRage as well as the additional log line created by the EventLogger [[1]]. This is a quick fix to prevent the additional event context being logged twice which is causing problems for Anne's analysis.
I think we should explore removing the EventLogger and just adding the event data to the logging_context and let LogRage log it; this however requires more refactoring and I'd like to fix this for Anne before it causes too much bother.
[1] https://github.com/alphagov/forms-runner/blob/main/app/lib/event_logger.rb#L3
Prevents duplicate `event=page*` entries which causes some issues for Anne's reporting. An example of this can be found by searching for …
=> Prevent Duplicate Event Logs

app/controllers/forms/check_your_answers_controller.rb, spec/requests/forms/check_your_answers_controller_spec.rb
We want to be able to correlate logs in GOV.UK Notify with logs in our system; to do this we can use the notification references.
This commit adds the notification references for submission emails and confirmation emails to the log messages for the `submit_answers` action.
=> Add notification references to logging context for form submission

app/controllers/forms/check_your_answers_controller.rb, app/form_objects/email_confirmation_form.rb, app/services/form_submission_service.rb, app/views/forms/check_your_answers/show.html.erb, spec/factories/form_objects/email_confirmation_form.rb, spec/form_objects/email_confirmation_form_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
Rename `notify_reference` to `submission_email_reference`.
This better describes the attribute, and disambiguates it from the confirmation email reference.
Because this change affects the end to end tests, we use the 'expand and contract' pattern to keep the old name around where necessary. There is also an associated change in alphagov/forms-e2e-tests#41 to rename the reference ID. That PR can be merged after this PR has been deployed.
- Has all relevant documentation been …
=> Rename submission email reference attribute

app/views/forms/check_your_answers/show.html.erb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
This fails WCAG 1.3.5 Identify Input Purpose, because this field should have an autocomplete=”email” attribute. The other aspects - type=”email” and spellcheck=”false” - aren’t WCAG failures, but they’ll help users enter their email addresses more easily, and it makes sense to implement them at the same time.
The field should have the following attributes:
- `type=”email”`
- `autocomplete=”email”`
- `spellcheck=”false”`
This commit adds a test to check the attributes are present and changes the code to include them.
=> Add attributes to the confirmation_email input

app/views/forms/check_your_answers/show.html.erb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
This reverts commit 9cc142311769e0feb9fe0a03031f0d7aa3ec67ef.
Now that [alphagov/forms-e2e-test#41](https://github.com/alphagov/forms-e2e-tests/pull/41) has been merged we don't need to have `#notification-id` in our app.
=> Clean-up after #634

Dockerfile, Gemfile
This means we only have 1 file to update (and means I can update this [script](https://github.com/alphagov/forms-deploy/blob/main/support/update_app_versions.sh#L70) to not bother with updating the Gemfile)
=> Update Gemfile to use file reference for Ruby version

jest.config.js, package.json, postcss.config.js
Trello card: https://trello.com/c/4WGWwZRU/1496-resolve-vite-deprecation-warning
The CommonJS build of Vite will no longer be supported as of v6.
None of our served JS files in this repo are CommonJS anyway, so we can safely add `"type": "module"` to our package.json file to fix this.
However, two of our config files (jest.config.js and postcss.config.js) were in CommonJS format. This change also updates them to use ES module format.
=> Fix Vite CommonJS deprecation warning

app/services/form_submission_service.rb, config/environments/test.rb, config/initializers/mailers.rb, lib/govuk_notify_rails/test_mailer.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/support/govuk_notify_rails_helpers.rb
Log notification IDs after call to GOV.UK Notify is made, to make it easier to lookup the notification in their database.
To make it possible to have this code run under test, I had to introduce a new test mailer, as with the default Rails test mailer `govuk_notify_response` attribute isn't populated.
=> Log notification IDs for form submission

app/controllers/application_controller.rb, app/controllers/forms/check_your_answers_controller.rb, app/controllers/forms/page_controller.rb, app/lib/context.rb, app/lib/form_context.rb, app/services/form_submission_service.rb, app/views/forms/submitted/submitted.html.erb, config/locales/en.yml, config/settings.yml, spec/config/settings_spec.rb, spec/features/fill_in_and_submit_form_spec.rb, spec/lib/context_spec.rb, spec/lib/form_context_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/views/forms/submitted/submitted.html.erb_spec.rb
Trello card: https://trello.com/c/44ZcfuuB/1360-generate-a-reference-for-form-submissions
This PR generates a reference number and adds it to the confirmation page.
To do this we:
- generate an 8 digit alphanumeric reference number and store it in a special bit of the session which doesn't get cleared on submit
- read the stored reference number on the confirmation page
- move the `email_sent` flag into the session, and rename it to make it clearer
- add the submission reference to the logging context
- clear the submission details from the session when the user restarts the form and saves the first question.
- feature flag the logging and display of the reference, so that we can turn it on after the email work is complete.
There's additional context on each commit message.
- pass the …
=> Add reference number to confirmation screen

app/form_objects/email_confirmation_form.rb, app/mailers/form_submission_confirmation_mailer.rb, app/mailers/form_submission_mailer.rb, app/services/form_submission_service.rb, spec/mailers/form_submission_confirmation_mailer_spec.rb, spec/mailers/form_submission_mailer_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb
Trello card: https://trello.com/c/dm8jKunt/1361-generate-a-reference-for-form-submissions-email-work
Adds two new variables to the Notify personalisation for the submission email (sent to processors) and confirmation email (sent to form fillers, if requested):
- include_submission_reference: this is a boolean controlled by the `reference_numbers_enabled` feature flag.
- submission_reference: the reference number itself.
This means that once this is merged and deployed, we can add the variable to the Notify templates in the format `((INCLUDE_SUBMISSION_REFERENCE??Your reference number is ))((SUBMISSION_REFERENCE))`. When the feature flag is off, this will return nothing, so the email will be the same as it was previously. But when the flag is on, it will return `Your reference is …
=> Add reference numbers to email

app/frontend/entrypoints/application.scss, app/frontend/styles/_app-panel.scss, app/mailers/form_submission_confirmation_mailer.rb, app/mailers/form_submission_mailer.rb, app/models/form.rb, app/services/form_submission_service.rb, app/views/forms/submitted/_submitted_panel.html.erb, app/views/forms/submitted/submitted.html.erb, config/locales/en.yml, spec/factories/models/forms.rb, spec/mailers/form_submission_confirmation_mailer_spec.rb, spec/mailers/form_submission_mailer_spec.rb, spec/models/form_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/views/forms/submitted/submitted.html.erb_spec.rb
https://trello.com/c/Gfqxj8yV/1358-enable-taking-payments-in-forms-via-runner
Adds payment stuff when there is a `payment_url` for a given form. This adds content and modifies the `form_submitted` page. 
It also adds content to form submission and confirmation emails. This all relies on the reference number feature flag being turned on, as it's necessary for payments. When there isn't a `payment_url` for a given form, no content relating to payments should appear. 
In order for this to fully function, the gov.uk/notify templates will need to be updated so that they accept the additional fields. We have templates that contain the appropriate content, but they'll need to replace the main ones in order for this to fully go live!
=> 1358 enable taking payments in forms via runner

app/services/form_submission_service.rb, app/services/reference_number_service.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/services/reference_number_service_spec.rb
https://trello.com/c/4lWx25f7/1426-update-form-reference-number-generation-logic
We want to try and match [GOV.UK Pay's reference number generation](https://github.com/alphagov/pay-products/blob/master/src/main/java/uk/gov/pay/products/util/RandomIdGenerator.java#L34), as these will be user facing numbers and we want to avoid any user unfriendly results. 
This should generate a 10 character reference, with the 3rd and 7th character always being a number. The characters `Z, I, 1, O and 0` are excluded as they're too confusable with each other (Z and 2 except keeping 2 is alright). 
Suggestions on how to make this more readable are welcome!
- Do the commit messages …
=> Generate user friendly reference numbers

config/locales/en.yml
Following user feedback, this changes the hint about how we use the email address you provide for a confirmation email to make it ever so slightly more specific. This is to help avoid people thinking that their email address won't be used for something else if it's been collected earlier in the form. 
We need to think about this a bit more to improve it further but this should help a bit for now.
Trello card: no trello
=> Update en.yml to make confirmation email hint more specific

app/views/forms/check_your_answers/show.html.erb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
Trello card: https://trello.com/c/hv6KQQUr/1224-check-your-answers-page-width
We have logic to make the summary list full width if the form contains a long text question. This is intended, but the original implementation made the _whole page_ full width, rather than just the summary list.
This PR puts the summary list in a separate grid row from the other elements on the page, and applies the full width logic to this row only. 
=> Stop elements other than summary list going full width

app/controllers/forms/check_your_answers_controller.rb
Trello card: https://trello.com/c/x8aQr5Y6/ 
We have found that in some scenarios users can POST to the check answers page with an incomplete session. We're not yet sure how best to deal with these scenarios, but adding specific logging will let us get an idea of how often this is happening.
This has been tested in dev, see [Splunk][1], [Sentry][2].
[1]: https://gds.splunkcloud.com/en-GB/app/gds-543-forms/search?q=search%20index%3D%22gds_dsp_dev_forms%22%20source%3D%22*forms-runner*%22%20time%3D%222024-04-26T08%3A06%3A45.268%2B00%3A00%22&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=-30m%40m&latest=now&sid=1714119042.839292
[2]: https://govuk-forms.sentry.io/issues/5259524304/
- Does it work when …
=> Log event if form submission occurs with incomplete session

app/controllers/forms/check_your_answers_controller.rb, app/input_objects/email_confirmation_input.rb, app/mailers/form_submission_mailer.rb, app/services/form_submission_service.rb, app/views/forms/check_your_answers/show.html.erb, config/locales/en.yml, spec/factories/input_objects/email_confirmation_input.rb, spec/input_objects/email_confirmation_input_spec.rb, spec/mailers/form_submission_mailer_spec.rb, spec/requests/errors_controller_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
The suffix "Form" for form objects which represent the input fields on a HTML form was difficult to work with, as we have a "Form" entity represing a GOV.UK Forms form, which is used throughout the application.
Use the suffix "Input" for form objects, to hopefully avoid this point of confusion.
=> Rename form objects to have suffix "Input"

Gemfile, Gemfile.lock, README.md, lib/tasks/pause_pipelines.rake
Trello card: https://trello.com/c/HFSmspAf/381-automatically-deploy-to-dev-environments-after-production
We're beginning to automatically deploy changes that are OK in production into dev environment(s). This means that dev environment pipelines will get run much more frequently, and the chances our test changes in the environment will get overridden are much higher. To counteract this we intend to pause the pipelines when we've deployed dev changes. 
This PR adds 3 Rake tasks to help with that:
* `rake pipeline:ENV:pause`
* `rake pipeline:ENV:unpause`
* `rake pipeline:ENV:status`
- Are there all the unit …
=> Introduce Rake tasks for pausing, unpausing, and getting the status of pipelines

config/settings.yml, spec/config/settings_spec.rb
Trello card: https://trello.com/c/Meo1LbpG/1875-add-a-feature-flag-for-google-analytics-in-the-runner
Adds a new feature flag, ``analytics_enabled`. This will allow us to implement the cookie consent and the analytics snippet separately, and then turn them on at the same time.
=> Add analytics feature flag

config/settings.yml, spec/config/settings_spec.rb
Trello card: https://trello.com/c/Meo1LbpG/1580-add-a-feature-flag-for-google-analytics-in-the-runner
Reverts the previous PR (#784) and reimplements it as a top-level setting in settings.yml, rather than a feature flag. This is because we think it would be useful to retain the ability to turn this feature off later, even after the feature is mature, whereas we've typically treated our feature flags as temporary. We already do the same thing for switching Cloudwatch metrics on and off.
=> Make google analytics feature into setting

app/frontend/entrypoints/application.js, app/frontend/javascript/google-tag/index.js, app/frontend/javascript/google-tag/index.test.js, app/views/layouts/base.html.erb, package-lock.json, package.json, spec/features/analytics/analytics_spec.rb
Trello card: https://trello.com/c/7jvfS18K/1585-add-google-analytics-4-to-forms-runner
This card adds Google analytics to any page, as long as the flag (`Settings.analytics_enabled`) is `true`.
Largely copied from the analytics work Tom did in the product pages. In future tickets we'll also copy over the cookie consent stuff from that repo, but this ticket/PR is limited to adding the snippet and putting it behind the flag.
You can test whether GA is running on a particular page by opening your browser console and seeing if typing `window.dataLayer` returns anything - if it returns `undefined` it isn't running, if it returns an array of event objects it is running.
- …
=> Add Google Analytics snippet

config/routes.rb
Trello card:[add-well-known-securitytxt](https://trello.com/c/SuTQEt4S/186-add-well-known-securitytxt)
This adds a  /.well-known/security.txt in line with[ the gds way](https://gds-way.digital.cabinet-office.gov.uk/standards/vulnerability-disclosure.html#vulnerability-disclosure), which helps people report vulnerabilities to cyber.
It does this by redirecting to alphagov's security.txt from `/security.txt.html` and `/.well-known/security.txt.html`
I have tested this locally, and we are redirected to the [security.txt](https://vdp.cabinetoffice.gov.uk/.well-known/security.txt) as expected when visiting the following urls:
- http://localhost:3001/.well-known/security.txt.html
- http://localhost:3001/security.txt.html
- Does it work when run on …
=> Add /security.txt.html to routes

Gemfile.lock
Main build was failing due to a CVE
https://github.com/ruby/rexml/security/advisories/GHSA-4xqq-m2hx-25v8 which is fixed in rexml version 3.3.2
=> Bump rexml from 3.3.1 to 3.3.2

config/application.rb, lib/generators/custom_component/USAGE, lib/generators/custom_component/custom_component_generator.rb, lib/generators/custom_component/templates/_index.scss, lib/generators/custom_component/templates/index.js, lib/generators/custom_component/templates/index.test.js, lib/generators/custom_component/templates/preview.rb.tt, lib/generators/custom_component/templates/view.html.erb, lib/generators/custom_component/templates/view.rb.tt, lib/generators/custom_component/templates/view_spec.rb.tt, spec/generator/custom_component_generator_spec.rb, spec/rails_helper.rb
Trello card: https://trello.com/c/gEvClwPP/24-add-a-component-generator-utility
Adds a new generator, `CustomComponentGenerator`, to the app to allow us to create new viewcomponents easily. Has flags for generating empty CSS and Javascript files in the componenty folder.
There's already a `ComponentGenerator` builtin to the ViewComponent gem, but it doesn't support the file structure we're using for our components.
Usage: `bin/rails generate custom_component Thing` with optional `--css` and `--javascript` flags.
=> Add custom component generator

app/frontend/javascript/utils/google-analytics/index.js
Trello card: https://trello.com/c/qAojecL7/1602-enable-google-analytics-in-admin-and-runner
For some reason we had the wrong google tag, so our analytics events aren't being logged properly. This updates it to use the correct value (which is the same as the one we already had in forms-product-page).
=> Update Google tag ID

app/frontend/entrypoints/application.js, app/frontend/javascript/utils/google-analytics/index.js, app/frontend/javascript/utils/google-analytics/index.test.js
Trello card: https://trello.com/c/qAojecL7/1602-enable-google-analytics-in-admin-and-runner
We previously added and enabled google analytics in admin and runner, but events aren't coming through in GA. THis is because we weren't actually pushing the events we care about into the dataLayer.
This PR does that. The events we're pushing are:
- page views - every time a user views a page, we push an event containing some basic data about the page to GA
- external link clicks - every time a user clicks a link without a relative URL, we log some information about that URL to GA
This should be essentially identical to https://github.com/alphagov/forms-admin/pull/1362. 
Firstly:
- Set `analytics_enabled: true` in your `development.yml` file
- login as a non-super admin user
- open the broswer …
=> Push pageview and external link events to GA

Gemfile, Gemfile.lock, app/services/form_submission_service.rb, app/services/submission_csv_service.rb, config/settings.yml, spec/config/settings_spec.rb, spec/services/form_submission_service_spec.rb, spec/services/submission_csv_service_spec.rb
Trello card: https://trello.com/c/BjjG6uTU/1666-generate-csv-data-for-a-submission
If the `attach_csv_to_submission_email` feature flag is enabled, write the submission to a CSV in a temporary file.
In future, we will send the CSV to form processors using Notify.
We will also enhance the feature flag so it can be enabled on a form by form basis later.
The first column is the form reference, followed by a column per question where the header is the question name.
This uses the Ruby "csv" library, which offers basic CSV reading/writing functionality.
The outputted CSV file will use the default unix line endings and UTF-8 encoding.
1. Comment out the `file.unlink` line in `app/services/form_submission_service.rb` locally so the temporary file we write the CSV to is not immediately deleted
2. …
=> Generate CSV data for a submission

app/services/form_submission_service.rb, app/services/submission_csv_service.rb, spec/services/submission_csv_service_spec.rb
Trello card: https://trello.com/c/BjjG6uTU/1666-generate-csv-data-for-a-submission
Include column with header "Submitted at", which contains the timestamp the form was submitted at as an ISO 8601 string. The time will match the timezone of the date/time in the submission email,  which is set to UK Local time in the app configuration.
Example CSV output:
```
Reference,Submitted at,What’s your name?,What’s your phone number?
NP44K96S,2024-08-06T13:09:25+01:00,Mike Forms,01134960000
```
=> Include submitted at timestamp in CSV

README.md, app/services/feature_service.rb, spec/services/feature_service_spec.rb
This commit allows features to be toggled on a per form basis in addition to the global feature flag. This is done in a similar way as per org switching in forms-admin. You can override the default value of a feature flag by providing key value pairs under a forms object, where the key is the form ID. For example:
```
features:
flag_test:
enabled: false
forms:
"123": true
```
We'd like to use this to do some user research for additional submission types with specific forms.
Trello card: https://trello.com/c/5xPfvcTJ
=> Allow FeatureService to switch features per form

app/services/form_submission_service.rb, spec/services/form_submission_service_spec.rb
There was no need for these methods to be public, but they were called directly in tests.
Modify the tests to just call the `submit` method whilst maintaining the same tests for sending the submission/confirmation email.
**NOTE**: Hiding whitespace changes will make this PR a lot easier to review because contexts were moved around in the tests so indentation changed.
=> Make methods in form_submission_service private

Gemfile.lock, app/mailers/form_submission_mailer.rb, app/services/form_submission_service.rb, app/services/log_event_service.rb, spec/mailers/form_submission_mailer_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/services/log_event_service_spec.rb
Trello card: https://trello.com/c/hjGOVjVL/1669-send-a-csv-with-submission
This PR attaches a CSV file to the submission email we send using Notify if the `attach_csv_to_submission_email` feature flag is enabled.
Have setup a test template in Notify that I tested this with - https://www.notifications.service.gov.uk/services/edf2d8fd-35d4-49fd-98b7-eb2738dafc98/templates/9948c208-dade-4600-b75f-b052be659204
The template looks like this:
All the content for the "Data processing" section is optional, so it will appear as it does now for submissions without a CSV file attached. The email sent looks like this:
The link in the email asks the user to enter the email address the file was sent to. It shows that the retention period is 7 days:
The CSV file generated looks like this:
The file name …
=> Send a CSV file with submission

spec/requests/forms/base_controller_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb
Currently the feature tests call URL helpers, like form_page_path, with a mix of positional and keyword arguments .
An example of a positional argument call:
form_page_path("preview-draft", 2, form_response_data.form_slug, 1)
An example of a keyword call:
form_page_path(mode: "preview-draft", form_id: 2, form_slug: form_response_data.form_slug, page_slug: 1)
This is fine, but inconsistent.
This PR changes all calls to use the keyword form. This makes it clearer
which arguments are for which routing segment. The keyword argument is
clearer because there are 4 arguments which makes it hard to get right.
It also allows adding new optional parameters to the calls, which will
be useful in the future.
There maybe a better way to do this in general, rather than using the helpers with all params …
=> Change all url helpers to use keyword arguments

README.md, app/services/feature_service.rb, app/services/form_submission_service.rb, app/services/log_event_service.rb, config/settings.yml, spec/config/settings_spec.rb, spec/services/feature_service_spec.rb, spec/services/form_submission_service_spec.rb, spec/services/log_event_service_spec.rb
This commit changes per form feature flagging to accept a comma separated list of form IDs for which a feature is enabled. This only applies if the feature flag itself is disabled.
This is to facilitate feature flagging per form separately in different environments.
All environment variables are strings, and because we want to be able to test the CSV submissions with users imminently we will just do the string parsing in the feature service for now.
It might be possible to persuade Terraform to provide an array to the application such that it is parsed as an array. We'll look at this next.
Trello card: https://trello.com/c/9XvRKwdK
- Do the commit messages explain …
=> Accept an array of form IDs for per form feature flagging

app/controllers/forms/add_another_answer_controller.rb, app/controllers/forms/base_controller.rb, app/controllers/forms/check_your_answers_controller.rb, app/controllers/forms/page_controller.rb, app/input_objects/add_another_answer_input.rb, app/lib/flow/context.rb, app/lib/flow/journey.rb, app/lib/flow/step_factory.rb, app/models/repeatable_step.rb, app/models/step.rb, app/views/forms/add_another_answer/show.html.erb, app/views/forms/page/show.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/models/pages.rb, spec/features/fill_in_single_repeatable_form_spec.rb, spec/input_objects/add_another_answer_input_spec.rb, spec/lib/flow/context_spec.rb, spec/lib/flow/step_factory_spec.rb, spec/models/repeatable_step_spec.rb, spec/requests/forms/add_another_answer_controller_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/views/forms/add_another_answer/show.html.erb_spec.rb
Trello card: https://trello.com/c/3nMdZ3Pa/1676-13-implement-add-another-answer-in-forms-runner-for-single-question-only-13
There is a lot to consider in this branch and I'm trying to do it with minimal disruption/refactoring of the current code.
=> Add a single repeatable step

app/controllers/forms/add_another_answer_controller.rb, app/input_objects/add_another_answer_input.rb, app/models/repeatable_step.rb, app/views/forms/add_another_answer/show.html.erb, config/locales/en.yml, spec/input_objects/add_another_answer_input_spec.rb, spec/models/repeatable_step_spec.rb, spec/requests/forms/add_another_answer_controller_spec.rb, spec/views/forms/add_another_answer/show.html.erb_spec.rb
Trello card: https://trello.com/c/qAJNULMm/1718-stop-form-fillers-from-adding-more-than-x-answers
When adding another answers, you should hit a limit that's set in `RepeatableStep::MAX_ANSWERS` now. This will alter the add_another_answer form so that it only submits with "no", thus continuing to the next question. 
This felt like the simplest way of getting users onto the next question, as it mimics them selecting 'no' to adding another answer, and removes the 'yes' option. 
=> 1718 stop form fillers from adding more than x answers

app/models/question/name.rb, app/models/question/question_base.rb, app/models/step.rb, app/services/submission_csv_service.rb, spec/models/question/address_spec.rb, spec/models/question/date_spec.rb, spec/models/question/email_spec.rb, spec/models/question/name_spec.rb, spec/models/question/national_insurance_number_spec.rb, spec/models/question/number_spec.rb, spec/models/question/organisation_name_spec.rb, spec/models/question/phone_number_spec.rb, spec/models/question/selection_spec.rb, spec/models/question/text_spec.rb, spec/services/submission_csv_service_spec.rb, spec/support/shared_examples/question_models.rb
Trello card: https://trello.com/c/PhJ9djZ7/1732-tweak-csv-output-so-the-name-fields-are-separated-as-expected
Separates out the name field into separate columns in thge CSV output. To do this it adds a new method `show_answer_in_csv` to the question model. This returns a hash with one key/value pair per column. 
Touches quite a few files but most of those are adding tests.
=> Separate name fields in csv

app/models/question/phone_number.rb, spec/models/question/phone_number_spec.rb
Trello card: https://trello.com/c/PoAbnOwy/1730-make-phone-number-show-correctly-in-csv-file
Adds logic to tweak the CSV output for phone numbers. This is to work around the default Excel behaviour, which is to interpret purely numeric phone numbers as numbers rather than strings when opening the CSV fileand format them without any leading zeroes at the beginning.
The CSV will now display the number with a space after the 5th digit for any numbers which are:
- entirely numeric (i.e. don't have any spaces, extensions or '+' characters), and
- begin with a zero
This will force Excel to interpret the numbers as strings, which will preserve their formatting.
- Do the …
=> Add space to some phone numbers in CSV output

app/mailers/form_submission_mailer.rb, spec/mailers/form_submission_mailer_spec.rb
Trello card: 
Notify has a limit of 100 characters for filenames for files attached to emails. We include the form name in the filename, which caused an exception to be thrown for long form names that would cause the filename length to exceed 100 characters.
Truncate the filename so it will be less than or equal to 100 characters. Truncate the filename at the last full word in the form name rather than partway through a word.
=> Limit Notify attachment filename to 100 characters

app/services/form_submission_service.rb, config/environments/development.rb, config/environments/production.rb, spec/services/form_submission_service_spec.rb
Trello card: https://trello.com/c/myozrQtS/1743-bug-notify-error-due-to-csv-filename-exceeding-100-characters
When the NotificationClient raises a `Notifications::Client::BadRequestError` upon attempting to deliver the submission email when a CSV file is attached, try the request again without the CSV file attached.
The intention of this is to allow submissions to go through if there is an unexpected error with the CSV file attachment. This could be due to the file failing a virus scan, or another unanticipated issue with the file we have attached.
Send the exception to Sentry and log at error level when this happens, as we want to be notified if we fail to attach the CSV file.
- Is it clear what the …
=> Retry sending submission email without file upon error

app/controllers/forms/add_another_answer_controller.rb, app/controllers/forms/check_your_answers_controller.rb, app/controllers/forms/page_controller.rb, app/lib/flow/context.rb, app/models/repeatable_step.rb, app/models/step.rb, spec/models/repeatable_step_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb
If a question is optional and can be answered multiple times we want the form filler to skip over the add another answer page if they do not answer the question the first time they are presented with it.
We also need the "Not answered" text to show up on the check your answers page, which isn't happening currently.
This PR is based on commits by @thomasiles in #900, with some extra tests and a bunch of refactors to the changed spec files.
=> Update check your answers page and next page logic to handle optional repeatable questions

app/models/repeatable_step.rb, spec/models/repeatable_step_spec.rb, spec/views/forms/add_another_answer/show.html.erb_spec.rb
The current limit of ten answers for a single repeatable question is
being increased from 10 to 50.
This figure has been chosen to cover most use cases for form creators.
This commit changes the MAX_ANSWERS constant from 10 to 50 and fixes the
tests which also need to change.
The tests could be changed to not break when changing this constant.
We are unlikely to change this number often. The tests have been kept as
explicitly checking the text and value.
There will be another ticket to update the text used in the admin to tell form creators about the limit.
Trello card: https://trello.com/c/7unK4mxB/1775-53dev-iterate-designs-for-single-repeatable-question-mvp-following-ur
- Is it clear what the code is …
=> Change max number answers for repeatable_step

app/controllers/errors_controller.rb, app/models/form.rb, app/models/page.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/forms_api_deprecations.rb, config/routes.rb, spec/factories/models/pages.rb, spec/models/form_spec.rb, spec/models/page_spec.rb
Trello card: https://trello.com/c/7unK4mxB/1775-53dev-iterate-designs-for-single-repeatable-question-mvp-following-ur 
We want to be certain that forms-runner is not using any of the `/forms/:id`, `/forms/:id/pages`, or `/forms/:form_id/pages/:id` API endpoints.
This is because we plan to deprecate those endpoints as part of moving to version 2 of the API (see [ADR 034]).
This PR adds a deprecation warning to the `.find` methods for the `Page` and `Form` class.
Note that this also causes a warning when `Form.find#pages` is used if the form response doesn't include the pages; however apart from one explicit test I don't think we call API endpoints that don't include the pages (but we'll find out when we release this change!).
[ADR 034]: …
=> Add deprecation warnings for API endpoints that we think we don't use

app/controllers/forms/base_controller.rb, app/services/api/v1/form_snapshot_repository.rb, spec/services/api/v1/form_snapshot_repository_spec.rb
Trello card: https://trello.com/c/OOYCWoTa/1779-8-change-forms-runner-to-use-v2-api 
This PR adds an extra layer of abstraction around how we retrieve forms from the forms-api app.
The thinking behind this is that it will make swapping out the method used for getting those forms easier (which we do in https://github.com/alphagov/forms-runner/pull/946). It also lets us in future decouple our models from the way we get the data, which is different to how ActiveResource does things but might be preferable.
=> Add service object for getting v1 form snapshots

app/views/forms/add_another_answer/show.html.erb, config/locales/en.yml, spec/views/forms/add_another_answer/show.html.erb_spec.rb
Trello card: https://trello.com/c/CzswSAoa/1725-3-review-form-filler-content-for-single-repeatable-step
This PR updates the content for the add another page.
[Charlotte has said that the text should be "Select yes if you need to add another answer" and that other instances of this pattern should be updated to remove the capitalisation and quotes around yes](https://trello.com/c/CzswSAoa/1725-3-review-form-filler-content-for-single-repeatable-step#comment-66eaa040002be7b1a7af359e). I've changed the text for this error and the one which appears on the submission email form.
Updated screenshots of both:
**Note** the trello card gave the text as "Select yes if you need to add another answer". I've capitalised and add quotes around _yes_. This makes it match the error the form filler sees if …
=> Update add another title and error text

app/services/feature_service.rb, app/services/form_submission_service.rb, config/settings.yml, spec/config/settings_spec.rb, spec/factories/models/forms.rb, spec/services/feature_service_spec.rb, spec/services/form_submission_service_spec.rb
Trello card: https://trello.com/c/DQCipW8q
This PR refactors the form submission service to use the `submission_type` stored on the Form model instead of the per form CSV submission feature flag. Since the per form feature flagging is no longer needed and we recommend not using it in future, we've removed it from the feature service.
We'll remove associated terraform from forms-deploy in a subsequent PR.
=> Use submission type on form

app/models/repeatable_step.rb, spec/factories/models/question/text.rb, spec/factories/models/repeatable_steps.rb, spec/factories/models/steps.rb, spec/models/repeatable_step_spec.rb, spec/services/submission_csv_service_spec.rb
Trello card: https://trello.com/c/n6Jpj46Q/1822-support-add-another-single-answer-into-csv-processor
When there is a repeated step in the completed form - i.e. when a question that allows multiple answers has been answered multiple times, include a column in the submission CSV for each repeated answer. The column header is suffixed by the answer index, like ' - Answer 1'.
For example,
'What is the meaning of life - Answer 1, What is the meaning of life - Answer 2'
When the question has separate attributes for different parts of the answer, like a name type question can, the suffix comes after the suffix for the attribute name.
For example,
'What is your name - First name - Answer 1, What is your name - Last name - Answer 1'
- Does it work when …
=> Support repeated answers in submission CSV

app/models/question/name.rb, app/models/question/phone_number.rb, app/models/question/question_base.rb, spec/models/question/address_spec.rb, spec/models/question/date_spec.rb, spec/models/question/email_spec.rb, spec/models/question/name_spec.rb, spec/models/question/national_insurance_number_spec.rb, spec/models/question/number_spec.rb, spec/models/question/organisation_name_spec.rb, spec/models/question/phone_number_spec.rb, spec/models/question/selection_spec.rb, spec/models/question/text_spec.rb, spec/models/repeatable_step_spec.rb, spec/services/submission_csv_service_spec.rb
Trello card: https://trello.com/c/n6Jpj46Q
This PR makes it so that we always include columns for optional questions in the submission CSV, with a blank value if they are unanswered.
For optional questions that can have multiple answers, if no answer is given, we want to include columns for the first answer, with the suffix " - Answer 1" and with blank value, to mirror what we do in the email.
=> Display optional questions in CSV

app/models/form.rb, config/settings/test.yml, lib/data_struct.rb, spec/factories/models/pages.rb, spec/factories/v2_form_document.rb, spec/factories/v2_step.rb, spec/features/email_confirmation_spec.rb, spec/features/fill_in_and_submit_form_spec.rb, spec/features/fill_in_single_repeatable_form_spec.rb, spec/models/form_spec.rb, spec/models/page_spec.rb, spec/requests/errors_controller_spec.rb, spec/requests/forms/add_another_answer_controller_spec.rb, spec/requests/forms/base_controller_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/requests/forms/privacy_page_controller_spec.rb, spec/requests/forms/remove_answer_controller_spec.rb, spec/requests/forms/submitted_controller_spec.rb
Trello card: https://trello.com/c/OOYCWoTa/1779-8-change-forms-runner-to-use-v2-api 
Update our specs to use the v2 API where appropriate.
=> Default to using v2 API in specs

app/lib/flow/journey.rb, app/models/question/question_base.rb, spec/lib/flow/journey_spec.rb, spec/models/question/question_base_spec.rb
Trello card: https://trello.com/c/mOvI9EEw/43-allow-form-preview-to-skip-to-a-specific-question 
As part of firebreak, I ended up having to play around with the `Journey` class that we use to hold the steps that a form filler has followed while filling out a form.
I wanted to create a subclass that tweaked the behaviour slightly, but I found this class a bit hard to wrap my head around, with a lot of tight logic wrapped up into one method.
This PR does a big refactor with the aim of making the class easier to understand (at least, I think it is easier to understand now). I also added some comments trying to explain what I think the class is for. I also added a bunch more tests, so I could feel confident that the refactor retained the essential behaviour.
- Ensure that you consider the …
=> Refactor Journey class to be easier to understand and extend

Gemfile, Gemfile.lock, app/services/csv_submission_service.rb, app/services/form_submission_service.rb, app/services/s3_submission_service.rb, config/settings.yml, spec/factories/models/forms.rb, spec/services/csv_submission_service_spec.rb, spec/services/form_submission_service_spec.rb, spec/services/s3_submission_service_spec.rb
Trello card: https://trello.com/c/ToXPf8zb/
Implement uploading file containing submission data to an S3 bucket specified for a form if the `submission_type` is `s3`. 
To do this, we assume an AWS role that is defined per environment. We expect the bucket to have granted write permissions for this AWS role.
1. Update `aws_s3_submissions.iam_role_arn` in the settings.yml file to be the ARN of the role with permissions to upload to the s3 bucket in the deploy environment.
2. Run the forms-api rake task to configure one of your local forms to send submissions to S3:
```
rake "forms:set_submission_type_to_s3[1, deploy-account-bucket-name, deploy-account-id]"
```
3. Start form-runner locally in an authenticated aws shell for the dev environment. This allows the app to assume the AWS role for …
=> Implement submission to s3

spec/models/step_spec.rb
To add support for branching questions with two branches to the Forms Runner, the #next_page_after_routing method needs to be changed.
This PR adds a spec file for the Step model.
Trello card: https://trello.com/c/vKfjfFSA/1922-add-support-for-branching-question-with-two-branches-to-forms-runner
The Step model doesn't currently have any unit tests.
This makes changing the class harder:
- it's tricky to know we haven't broken something the code relies on
- new methods are less likely to have tests written for them if there is no existing spec file to add to
This commit adds a spec file for the Step model.
The tests are written to match the existing code and the functionality it currently has.
There are ways we could improve the Step model in the future which would make the tests easier to …
=> Add tests for Step model

app/lib/flow/step_factory.rb, app/models/step.rb, spec/factories/models/repeatable_steps.rb, spec/factories/models/steps.rb, spec/models/repeatable_step_spec.rb, spec/models/step_spec.rb
Steps belong to forms and have a page. Currently we keep the IDs of these associated objects as attributes in a step, along with some other bits of data from those records that we need, but this isn't super helpful if we need other details about those other objects.
Given that in forms-runner we will always fetch the form and build the question before instantiating a step, we can just keep references as an instance attribute, with little downside.
=> Change Step to keep a reference to its associated models

app/services/form_submission_service.rb, app/services/s3_submission_service.rb, spec/services/form_submission_service_spec.rb, spec/services/s3_submission_service_spec.rb
Trello card: https://trello.com/c/ToXPf8zb/
Change the key name so that:
- The root folder is pluralized to "form_submissions/"
- If the form is a preview, the root folder is "test_form_submissions/"
- The form ID is a folder rather than a prefix to the filename
- The timestamp is in UTC and does not contain any special characters, as colons (:) and plus signs (+) are not in AWS's list of safe characters for key names.
=> Change key name for submission uploaded to s3

app/views/forms/submitted/_submitted_panel.html.erb
When the submission type of a form is S3, we save the form to a specified bucket, using the submission reference number as part of the key. When running end to end tests, we want to be able to submit a form, then look into an S3 bucket to find the submission.
Adding an ID here allows the end to end tests to easily find the reference number and use it to look for the submitted form in S3.
[Trello card](https://trello.com/c/64CM50hZ/1921-add-an-e2e-test-for-s3-submissions)
this relates to this PR: https://github.com/alphagov/forms-e2e-tests
- Has all relevant …
=> Add id to submission reference number

app/components/question/file_component/view.html.erb, app/components/question/file_component/view.rb, app/lib/flow/question_register.rb, app/models/question/file.rb, spec/components/question/file_component/file_component_preview.rb, spec/components/question/file_component/view_spec.rb, spec/models/question/file_spec.rb
Trello card: https://trello.com/c/8v2L1Cd7/2042-build-an-add-file-component-to-embed-in-a-form-for-form-fillers-%F0%9F%A6%B4?filter=label:Feature%20team%20one
Adds:
- a component for rendering a file upload input in a form. 
- a vvery basic question model to enable rendering the input
Doesn't include any file handling or validation logic.
To test this, you'll need to create a question with `answer_type: "file"`. To do that you  need to:
- enable the `file_upload_enabled` flag for a group on your local machine (`rake groups:enable_file_upload[<group_external_id>]`
- create a new question in a form within that group
- choose the 'file' answer type
- Do the commit …
=> Add basic file upload component

spec/features/components/preview_components_spec.rb
Trello card: 
It's possible for changes to our build to cause assets not to be built properly. One of the problems this causes is a failure to load the GDS Transport font.
This commit adds a test which will fail if the GDS Transport font is referenced in a font-face declaration but fails to load.
See also:
- original forms-admin PR (https://github.com/alphagov/forms-admin/pull/1658)
- accompanying forms-runner PR: https://github.com/alphagov/forms-product-page/pull/574
=> Add a test for GDS Transport font loading

app/models/question/file.rb, app/models/question/question_base.rb, app/models/step.rb, config/settings.yml, spec/features/fill_in_file_upload_question_spec.rb, spec/models/question/file_spec.rb, spec/models/step_spec.rb
Trello card: https://trello.com/c/7CmjPY64/
Add a new `update_answer` method to question_base to set the answer attributes on the question. This is overridden by the `file` model to perform the upload to S3 when the answer is saved.
We do not want to save the file itself to the session, so we set this to `nil` on the model as this model is used to set the answer data on the session. Instead, set `original_filename` which is the name the file was uploaded with and `uploaded_file_key` which is the S3 object key on the session.
Make it so that we display the `original_filename` back to the user on the "Check your answers" page.
We generate a unique key for the file in S3 using UUID to ensure there is no chance of 2 files being uploaded with the same key.
- Ensure that you consider the wider …
=> Upload to s3 for file upload questions

app/controllers/forms/page_controller.rb, app/models/step.rb, app/views/errors/goto_page_before_routing_page.html.erb, app/views/errors/goto_page_routing_error.html.erb, config/locales/errors.yml, spec/models/step_spec.rb, spec/requests/forms/page_controller_spec.rb
Trello card: https://trello.com/c/rYsaVrIn/2040-bug-routing-question-with-no-go-to-question-leads-to-server-error-when-previewing-form
This PR changes the runner to be able to preview pages with multiple conditions and possibly missing goto_pages.
Different errors are displayed based on the error:
- No goto_page in the condition at all, probably because the goto_page has been deleted
- a goto_page before the selection question, which would cause a loop
In both cases the user is given the option to return to admin routes page to correct the issue.
The error is based on only the first error on a page. It's possible for a question to have multiple conditions associated with it if it's a secondary skip question which is itself a condition.
We have another card to consider all error messages …
=> Fix issue in runner displaying forms with incomplete routes

app/mailers/aws_ses_form_submission_mailer.rb, app/models/question/file.rb, app/services/aws_ses_submission_service.rb, spec/factories/models/question/file.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb, spec/models/question/file_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/JEWV7ew5/
Attach files for file upload questions to the email when sending the email using SES. This gets the file from S3 using the key stored against the answer in the session.
Files are stored in memory before the email is sent, but this is unavoidable as we need to read the raw content of the file to pass to ActionMailer to construct the raw email.
This assumes that all files are uploaded with unique filenames - which may not be the case in reality. We will need to ensure that files have unique names but this is not addressed in this PR.
It is currently only possible to test this by pushing the branch to the dev environment. I have tested this and got an email with the file attached:
- Does it work when …
=> Attach file uploads to emails

app/controllers/forms/page_controller.rb, app/models/question/file.rb, app/models/question/question_base.rb, app/models/step.rb, app/services/aws_ses_submission_service.rb, config/locales/en.yml, spec/factories/models/question/file.rb, spec/models/question/file_spec.rb, spec/models/step_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/7qrLP1gH/2067-restrict-file-uploads-to-5-questions-of-7mb-each
Add validations for file upload questions to validate that:
- A file has been selected
- The file size does not exceed 7 Megabytes.
The point at which we upload the file to S3 has had to change to make validations work. See individual commit messages for details.
Also allow for file upload questions to be optional, and don't try to upload/download from S3 when the question is skipped.
It's possible to test the validations locally, but you will see an error if the validations pass as you are not able to upload to S3. I've tested this PR by pushing the branch to the development environment and testing there.
The question is shown as not completed on the "Check your answers" page:
The question is …
=> Add file size validation for file upload questions

app/components/question/file_component/view.html.erb, config/locales/en.yml
Trello card: https://trello.com/c/7qrLP1gH/2067-restrict-file-uploads-to-5-questions-of-7mb-each
=> Add content about file upload size limit

app/models/question/file.rb, spec/models/question/file_spec.rb
Trello card: https://trello.com/c/7qrLP1gH/2067-restrict-file-uploads-to-5-questions-of-7mb-each
Add logging when a file is uploaded to S3 for a file upload question, or when validation fails due to a file being too big.
This information can help us analyse what file types people are attempting to or successfully uploading and do analysis of the file sizes.
=> Add logging for file upload

Gemfile.lock, app/frontend/entrypoints/application.scss, vite.config.js
Trello card: https://trello.com/c/pfzCTVnB/2066-investigate-asset-building-issue-with-modern-sass-api
We were seeing [an issue with assets failing to build properly using the 'modern' Sass API](https://trello.com/c/pfzCTVnB/2066-investigate-asset-building-issue-with-modern-sass-api). After investigating this appears to be caused by a bug in the Vite internal sass importer (https://github.com/vitejs/vite/issues/19196). 
This PR:
- uses the sass NodePackageImporter to import govuk-frontend, which bypasses that bug and also offers us some other advantages (see commit message for more details)
- updates to use the modern API
- uses a more compact API for setting the asset paths
- Do the commit messages explain why …
=> Switch to modern Sass API

app/controllers/forms/check_your_answers_controller.rb, app/views/forms/check_your_answers/show.html.erb, spec/views/forms/add_another_answer/show.html.erb_spec.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb
Trello card: https://trello.com/c/2vKEI8SL/2473-add-get-help-link-to-the-cya-page 
The "Check your answers" page was missing the link to get help, which was surfaced during accessibility testing.
=> Add missing Help link on Check Your Answers page

app/lib/csv_generator.rb, app/lib/flow/context.rb, spec/features/fill_in_and_submit_form_with_csv_spec.rb, spec/lib/csv_generator_spec.rb, spec/lib/flow/context_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/GxKKN67X/2038-implement-csv-formatting-for-routing?filter=member:tomiles3
This PR changes the CSV output for notify and S3 to include headers for all questions in a form. For questions which the filler has not answered (because they have taken other routes through a form with routing) the value will be blank.
The teams using CSV output have been told and have agreed that we can go ahead and release this change.
See the trello ticket for more details.
=> Stable csv columns

app/lib/csv_generator.rb, spec/features/fill_in_and_submit_form_with_csv_spec.rb, spec/lib/csv_generator_spec.rb
This reverts commit ec8588c3a3b5bbed3939a3ab53406a2eefcfddc0.
Errors submitting production forms indicate that this change is responsible.
This PR reverts the commit which changes the CSV generator to use all questions within a form, even if they haven't been answerd.
At first glance, it looks like empty selection questions are causing the errors to be thrown.
Trello card: 
=> Revert "Change CsvGenerator to use all_steps"

app/components/question/file_component/view.html.erb, app/models/question/file.rb, config/locales/en.yml, spec/components/question/file_component/view_spec.rb, spec/features/fill_in_file_upload_question_spec.rb, spec/models/question/file_spec.rb
Trello card: https://trello.com/c/Nr7OQkk2/2092-limit-the-file-types-that-can-be-uploaded
Adds:
- backend validation to restrict the files we accept to the following MIME types:
- text/csv (.csv)
- image/jpeg (.jpg, .jpeg)
- image/png (.png)
- application/rtf (.rtf)
- text/plain (.txt)
- application/pdf (.pdf)
- application/json (.json)
- application/vnd.openxmlformats-officedocument.spreadsheetml.sheet (.xlsx)
- application/msword (.doc)
- application/vnd.openxmlformats-officedocument.wordprocessingml.document (.docx)
- application/vnd.oasis.opendocument.text (.odt)
- an `accept` attribute on the file input with the same MIME types above. This will provide hints to the user's operating system on what kinds of files they should choose.
If you want to bypass the `accept` attribute on a Mac …
=> Add file type validation

Gemfile, Gemfile.lock, README.md, config/initializers/aws_role_usage.rb
Trello card: https://trello.com/c/l4CIGYi2/596-help-ft-team-1-test-upload-email-locally
In Amazon ECS, forms-runner has credentials for an IAM role that grants it permission to do things like upload files to S3 and send emails via AWS SES. Doing these things locally requires the same set of permissions.
To attain those permissions, developers can now assume the same role as is used by Amazon ECS in the development account by starting the Rails server with the ASSUME_DEV_IAM_ROLE environment variable.
I've not been able to test this much beyond starting the server successfully, so I'd appreciate if somebody with a working `forms-runner` setup could give it a quick prod.
I'm reasonably sure it's all correct from seeing the server start up correctly. Setting environment variables is all …
=> Enable starting the Rails server using the AWS IAM role for forms-runner

app/controllers/application_controller.rb, app/models/current_logging_attributes.rb, spec/models/current_logging_attributes_spec.rb, spec/requests/application_controller_spec.rb, spec/requests/forms/base_controller_spec.rb
Rename the "host" logging field to "hostname". An additional "host" field is added to the logs that go to Splunk for Kenesis. This means we end up with 2 values for "host" making it difficult to filter searches by it.
=> Rename host logging field

app/components/question/file_component/view.html.erb, app/views/forms/page/show.html.erb, config/locales/en.yml, spec/views/forms/page/show.html.erb_spec.rb
Trello card: https://trello.com/c/Nr7OQkk2/2092-limit-the-file-types-that-can-be-uploaded
Makes some tweaks to the content we show to form fillers on file upload questions:
- alphabetises the list of file types in the validation message
- adds some new guidance around what file types the user can supply
- puts the new guidance and the existing guidance on file size together in one details component
=> Update content around file type validation

app/components/question/file_review_component/view.html.erb, app/components/question/file_review_component/view.rb, app/components/success_banner_component/view.html.erb, app/components/success_banner_component/view.rb, app/controllers/application_controller.rb, app/controllers/forms/page_controller.rb, app/controllers/forms/review_file_controller.rb, app/lib/flow/context.rb, app/models/question/file.rb, app/services/aws_ses_submission_service.rb, app/views/forms/review_file/show.html.erb, app/views/layouts/base.html.erb, config/locales/en.yml, config/routes.rb, spec/components/question/file_review_component/file_review_component_preview.rb, spec/components/question/file_review_component/view_spec.rb, spec/factories/models/question/file.rb, spec/features/fill_in_file_upload_question_spec.rb, spec/models/question/file_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/requests/forms/review_file_controller_spec.rb, spec/views/forms/review_file/show.html.erb_spec.rb
Trello card: https://trello.com/c/mfhj3ufe/2068-play-back-what-file-has-been-uploaded-to-users-and-allow-them-to-change-file
This PR adds a review file page that allows a form filler to view the file they have uploaded, and optionally remove it. This is implemented usinga new `ReviewFileController` with new routes for showing the page and removing the file. This also requires tweaking the redirects in the `PageController` to take the user to the review file page:
- after uploading a file
- when editing an answer from check your answers
- when navigating to the file upload question directly with a file already uploaded
This PR will be followed by one which alters the flow slightly, to add a confirmation of removal screen. This will allow us to use the summary list component as intended by …
=> Play back what file has been uploaded to users, and allow them to change file

app/components/question/file_remove_component/view.html.erb, app/components/question/file_remove_component/view.rb, app/components/question/file_review_component/view.html.erb, app/components/question/file_review_component/view.rb, app/controllers/forms/review_file_controller.rb, app/input_objects/remove_file_input.rb, app/views/forms/review_file/confirmation.html.erb, app/views/forms/review_file/show.html.erb, config/locales/en.yml, config/routes.rb, spec/components/question/file_remove_component/file_remove_component_preview.rb, spec/components/question/file_remove_component/view_spec.rb, spec/components/question/file_review_component/file_review_component_preview.rb, spec/components/question/file_review_component/view_spec.rb, spec/input_objects/remove_file_input_spec.rb, spec/requests/forms/review_file_controller_spec.rb, spec/views/forms/review_file/confirmation.html.erb_spec.rb
Trello card: https://trello.com/c/mfhj3ufe
This PR adds a confirmation page for removing an uploaded file. This allows us to use a summary list in the review file page, and better fits with patterns used elsewhere in GOV.UK Forms (e.g. add another answer). This necessitates updating the delete action in `ReviewFileController` to accept an input object and conditionally delete the file.
There are a couple of refactoring bits I'd like to do, but probably in a subsequent PR unless reviewers think it should be done in this one:
- tidying up translation names and reducing duplication
- reducing duplication in `ReviewFileController`
- refactoring remove file and remove answer input objects into a single input object used by both
- suggestions by @stephencdaly:
- fix back link on confirmation …
=> Add remove file confirmation

app/controllers/forms/review_file_controller.rb, spec/requests/forms/review_file_controller_spec.rb
The back link on the file removal confirmation page previously linked to the upload file page, when it should link to the review file page. This PR fixes this. I've also added a `setup_confirmation` method to reduce code duplication.
Trello card: https://trello.com/c/mfhj3ufe
=> Fix back link on file removal confirmation page

app/lib/file_upload_logger.rb, app/models/question/file.rb, app/models/question/file/virus_scan.rb, app/services/question/file_upload_s3_service.rb, spec/models/question/file_spec.rb, spec/services/question/file_upload_s3_service_spec.rb
It's useful to log the S3 object key when we log operations on files uploaded for a file upload question so that we can link together operations on the object during is lifecycle if we ever need to track what happened to an object.
Additionally, log when a file is deleted from S3 or retrieved to be attached in an email so we have greater visibility over the object lifecycle.
Added `FileUploadLogger` to ensure that we always log these operations with the `s3_object_key` field.
=> Log more information about S3 operations

app/models/question/file.rb, app/views/aws_ses_form_submission_mailer/submission_email.html.erb, app/views/layouts/mailer.html.erb, config/environments/development.rb, config/locales/en.yml, spec/mailers/aws_ses_form_submission_mailer_preview.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/MD1dVOix/2070-update-ses-email-template-to-match-designs-for-file-upload
Updates the SES email template to match the latest designs.
This PR:
- configures ActionMailer preview to make developing templates easier
- uses Notify's template HTML in the mailer layout so that we get the same header and styles as our Notify emails
- adds some content from the design:
-  '(attached to this email)' suffix to file questions
-  'Check that this data looks safe' text
- also includes a couple of some small cleanup changes to the markup
See individual commit messages for more details.
- …
=> Update SES email template with GOV.UK branding and content

Gemfile, Gemfile.lock, app/frontend/entrypoints/application.scss, package-lock.json, package.json
Trello card: related to https://trello.com/c/EU0NKwCA/2047-raise-pr-on-accessibility-issue-with-dfe-autocomplete-component
Updates to the latest dfe-autocomplete and makes a small update to the way we import it.
Changes in this release: https://github.com/DFE-Digital/dfe-autocomplete/compare/8e7389ff62a38bc8880323f6c58eed9c8d10f080...1d4cc65039e11cc3ba9e7217a719b8128d0e4d53
=> Update dfe autocomplete

app/services/question/file_upload_s3_service.rb, spec/services/question/file_upload_s3_service_spec.rb
Trello card: https://trello.com/c/ZzVCrkDn/2115-test-policy-on-the-s3-buckets-that-clear-up-files-after-30-days
Log at error level with the logging context field `s3_object_key` when a `NoSuchKey` error is raised by the request to get an object from S3. This will allow us to find out the key for the file that was not found to help us diagnose the cause of this error.
Re-raise the error, which will cause the user to see a generic technical difficulties page, and the error will be sent to Sentry.
We only expect this error to be raised when a user has managed to keep the same form filling session open for 30 days and our lifecycle rules for the S3 bucket have deleted the file.
- Is it clear what the code …
=> Log an error when file upload key is not found in S3

app/lib/csv_generator.rb, app/models/question/selection.rb, spec/features/fill_in_and_submit_form_with_csv_spec.rb, spec/lib/csv_generator_spec.rb, spec/models/question/selection_spec.rb
Trello card: https://trello.com/c/GxKKN67X/2038-implement-csv-formatting-for-routing
This PR makes submission CSVs include headers and values for all questions in a form. It fixes an issue which caused production issues when previously enabling this feature.
See:
[The original PR which caused submissions to fail for a production form](https://github.com/alphagov/forms-runner/pull/1155)
[The PR used during the incident to revert the behaviour](https://github.com/alphagov/forms-runner/pull/1158)
[The incident document](https://docs.google.com/document/d/1M3usd9hEwpnVSnh2WP77Qf6uGak7pASfQqe5AQCIwc4/edit?tab=t.0#heading=h.p99426yo0rbv)
To prevent similar issues happening when deploying this PR the feature test for CSV generation has been adapted to cover the case.
I cloned the production form …
=> Fix CSV generation to include all questions including skipped checkbox questions

app/controllers/forms/check_your_answers_controller.rb, app/lib/flow/context.rb, app/lib/store/session_answer_store.rb, app/mailers/form_submission_confirmation_mailer.rb, app/mailers/form_submission_mailer.rb, app/models/application_record.rb, app/models/submission.rb, app/services/aws_ses_submission_service.rb, app/services/form_submission_service.rb, app/services/notify_submission_service.rb, app/services/s3_submission_service.rb, db/migrate/20250219163804_add_initial_columns_to_submissions.rb, db/schema.rb, spec/factories/submissions.rb, spec/lib/store/session_answer_store_spec.rb, spec/mailers/aws_ses_form_submission_mailer_preview.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb, spec/mailers/form_submission_confirmation_mailer_spec.rb, spec/mailers/form_submission_mailer_spec.rb, spec/services/aws_ses_submission_service_spec.rb, spec/services/form_submission_service_spec.rb, spec/services/notify_submission_service_spec.rb, spec/services/s3_submission_service_spec.rb
Trello card: https://trello.com/c/lW3IqOhY
This PR adds a new `Submission` model, and uses it to store submission data when submission emails are sent via AWS SES. In order to enable this, we also added a method to the `SessionAnswerStore` to retrieve answers from the session.
In future, we may make all submission types asynchronous so may persist submission data for all submission types then, as opposed to just for the `AwsSesSubmissionService`.
=> Store submission data to handle bounced submission emails

app/controllers/forms/page_controller.rb
Fixes `AbstractController::DoubleRenderError` Sentry alert.
@DavidBiddle suggested the root cause of the error:
- visit a repeatable step without filling out the previous questions
- the show action in PageController runs
- [this line](https://github.com/alphagov/forms-runner/blob/e57f658217be19b8a7dc68375eb2f45d162399ed/app/controllers/forms/page_controller.rb#L11) sets up a redirect to the first page in the form, but the action still continues
- the next line calls answered_file_question? , which calls step.question , which errors out on [this line](https://github.com/alphagov/forms-runner/blob/e57f658217be19b8a7dc68375eb2f45d162399ed/app/models/repeatable_step.rb#L49)
- that exception is caught by [this rescue statement](https://github.com/alphagov/forms-runner/blob/e57f658217be19b8a7dc …
=> Add return statements to PageController#show

Gemfile.lock
Update the version of the URI gem to avoid a CVE, see https://www.cve.org/CVERecord?id=CVE-2025-27221
Done without Dependabot because it has an issue.
=> Update URI gem to avoid CVE

app/jobs/delete_submissions_job.rb, app/jobs/send_submission_job.rb, app/lib/flow/journey.rb, app/models/submission.rb, app/services/aws_ses_submission_service.rb, config/database.yml, config/environments/development.rb, config/recurring.yml, config/settings.yml, config/settings/development.yml, db/migrate/20250303163133_add_index_on_updated_at_to_submissions.rb, db/schema.rb, spec/factories/submissions.rb, spec/jobs/delete_submissions_job_spec.rb, spec/lib/flow/journey_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/koB73lTl/
Add a scheduled task which is run by Solid Queue to delete submission which:
* have an `updated_at` date of earlier that 7 days ago
* have a `mail_message_id` present, indicating we have successfully initialised sending the submission email
We are using the `updated_at` date so that when a submission bounces, we will delete it 7 days after the submission is re-attempted. We'll look at ensuring we don't delete bounced submissions until they've been successfully retried in a different PR.
If a submission has answered file upload questions, we delete the uploaded files from S3.
This job will be run on an hourly schedule.
If deleting a submission fails for any reason, we send the error to Sentry and continue deleting other submissions.
To test …
=> Delete submissions after 7 days

lib/tasks/submissions.rake
Trello card: https://trello.com/c/koB73lTl
When we first started storing submissions, we were not storing the `mode`, which is required to retrieve the form from forms-api.
This means that the DeleteSubmissionsJob is failing for these submissions. Add a temporary rake task to set the `mode` on these submissions.
Add another task to list submissions without a mode so we don't miss any.
These rake tasks can be removed as soon as these submission records are fixed.
=> Add temporary rake task to set mode on submissions

config/database.yml
Ensure only migrations in the `db/queue_migrate` directory are run on the Solid Queue database for the development environment by correcting the `migrations_paths` key in the configuration.
=> Fix Solid Queue db configuration for development

app/models/form.rb, app/models/submission.rb, app/services/api/v1/form_snapshot_repository.rb, app/services/form_submission_service.rb, db/migrate/20250310114758_add_form_document_to_submissions.rb, db/schema.rb, spec/factories/models/forms.rb, spec/factories/submissions.rb, spec/features/fill_in_file_upload_question_spec.rb, spec/jobs/delete_submissions_job_spec.rb, spec/jobs/send_submission_job_spec.rb, spec/services/form_submission_service_spec.rb
Trello card: https://trello.com/c/MK2CoKeB/2753-ensure-we-can-send-submission-emails-when-form-is-changed
Store the form document JSON blob on the submission in the database and use this when reading the form to construct the Journey for generating the submission email in the SendSubmissionJob, and for deleting uploaded files from S3 in the DeleteSubmissionsJob.
We need to do this rather than getting the form from forms-api as the form may have been updated after the submission was made, meaning that the answers may no longer match up with the questions in the most recent version of the form.
To account for submissions that currently exist without the form_document stored, read the form from forms-api if the form_document is not present. This fallback can be removed once we have …
=> Store form document on submission

app/lib/flow/journey.rb, app/models/question/file.rb, app/services/aws_ses_submission_service.rb, spec/factories/models/question/file.rb, spec/lib/flow/journey_spec.rb, spec/models/question/file_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/dKAbc0DS/2156-handle-multiple-files-uploaded-with-the-same-name
When more than one file with the same name has been uploaded in the same form journey, we want to disambiguate them by adding a suffix to some of them before attaching them to the SES email.
In this implementation the first file with a given name will keep the original filename, and subsequent files with the same name will be suffixed like so:
- `my_file.png`
- `my_file_1.png`
- `my_file_2.png`
- `my_file_3.png`
We currently only allow 4 files but this implementation should support any number if we increrase that in future.
This PR also includes a change to truncate filenames to 255 characters or fewer - this is the maximum filename macOS supports by default, Windows supports 256 by default …
=> Add number suffix to identical file names

app/models/question/file.rb, spec/models/question/file_spec.rb
Trello card: https://trello.com/c/dKAbc0DS/2156-handle-multiple-files-uploaded-with-the-same-name
Uses the filename suffixes added in https://github.com/alphagov/forms-runner/pull/1252 in the CSV data as well as the email.
This was omitted from the original PR (thanks @stephencdaly for spotting!)
=> Add suffix to filename in CSV

app/models/question/file.rb, spec/models/question/file_spec.rb
Trello card: https://trello.com/c/dKAbc0DS/2156-handle-multiple-files-uploaded-with-the-same-name
The change in #1253 meant that when a user left a file input blank, the CSV generation would break (because it expects a hash but the code was returning `nil`).
This PR updates it and adds some missing tests that would've caught the issue sooner.
=> Support optional file questions in csv

app/controllers/forms/check_your_answers_controller.rb, app/helpers/application_helper.rb, app/models/question/file.rb, app/models/question/question_base.rb, spec/helpers/application_helper_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/support/shared_examples/question_models.rb
Trello card: https://trello.com/c/wMIZWtPX/2160-include-page-heading-in-cya-page-when-guidance-is-present
Adds a caption with the page heading to the Check Your Answers page when the question has guidance.
At the moment this will only show for File questions, but if we're happy with this we can apply t to all questions with guidance in future.
=> Include page heading in Check Your Answers rows for file upload questions

app/services/cloud_watch_service.rb, spec/services/cloud_watch_service_spec.rb
> [!WARNING]  
> https://github.com/alphagov/forms-deploy/pull/1438 must be deployed before this is merged
Trello card: https://trello.com/c/sSfVKcbD/2143-set-up-monitoring-and-observability-for-ses-file-upload-submissions
We're adding additional metrics to monitor the health of our background jobs, and we reviewed the naming conventions of our existing metrics as part of this.
We want to follow the AWS metrics naming conventions by making namespaces, metric names and dimension names all CamelCase.
To do this, we need to start sending new metrics with the desired names alongside the existing metrics. We can then switch over forms-admin to read the new metrics once we have been sending metrics for at least 8 days, as forms-admin only displays metrics for the previous 7 days. Once …
=> Rename CloudWatch metrics to match AWS conventions

app/controllers/forms/exit_pages_controller.rb, app/controllers/forms/page_controller.rb, app/models/step.rb, app/views/forms/exit_pages/show.html.erb, config/routes.rb, spec/features/fill_in_form_with_exit_page_spec.rb, spec/models/step_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/views/forms/exit_pages/show.html.erb_spec.rb
Trello card: https://trello.com/c/pfNYulxC/2151-add-support-for-exit-pages-to-forms-runner
Exit pages are given a url like this: "/preview-live/3/branch-route-form/11/exit". "/exit" is added on to the end of the page_slug.
We can change exit to anything else easily, I'll post something in slack and we make the change in another PR. It's just changing the route definition, so shouldn't be hard.
This PR doesn't add events when an exit page is viewed. I'll create another card which captures that so we can discuss what's best with Anne.
Note: I mucked up the markdown in the API seed for the exit pages. The above will only show correctly in the preview when[ the PR for fixing the seed](https://github.com/alphagov/forms-api/pull/713) is merged into the API.
- Ensure that you consider the wider …
=> Show exit pages

app/jobs/delete_submissions_job.rb, app/jobs/queue_metrics_job.rb, app/jobs/send_submission_job.rb, app/services/cloud_watch_service.rb, config/queue.yml, config/recurring.yml, spec/jobs/queue_metrics_job_spec.rb, spec/services/cloud_watch_service_spec.rb
Trello card: https://trello.com/c/sSfVKcbD/2143-set-up-monitoring-and-observability-for-ses-file-upload-submissions
This PR:
* Assigns all jobs to named queues.
* Adds a job to send a metric for the length of the submissions queue to CloudWatch. This job runs as the highest priority to ensure we are sending regular metrics.
I did consider adding a separate worker for running background jobs so these would not block sending submissions if there was a bug that caused them to be long-running. However, we run a minimum of 6 forms-runner ECS tasks on production so it is unlikely we'd run into capacity issues. We have alerts that will tell us if we're struggling to keep up with demand.
I've tested this by connecting my local environment to the AWS dev account:
- Ensure that you consider the …
=> Add background job to send queue metrics

.github/workflows/test.yml
We are seeing intermittent failures when feature tests run in github actions. These failures are related to selenium and chromedriver. They are false positives and do not mean the code is broken.
This commit copies the solution gov.uk applied to their codebase.
https://github.com/alphagov/publisher/pull/2596/commits/68adc8858782949a1a38f4eb582a17462eb0e51c
This change should only be needed until the chromedriver/chrome version issue is fixed.
Trello card: 
=> Use chromedriver v128 in github actions

app/lib/ses_email_formatter.rb, app/mailers/aws_ses_form_submission_mailer.rb, app/services/aws_ses_submission_service.rb, app/views/aws_ses_form_submission_mailer/submission_email.html.erb, app/views/aws_ses_form_submission_mailer/submission_email.text.erb, config/locales/en.yml, spec/features/fill_in_file_upload_question_spec.rb, spec/lib/notify_template_formatter_spec.rb, spec/lib/ses_email_formatter_spec.rb, spec/mailers/aws_ses_form_submission_mailer_preview.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/2DMKRjiO/2170-include-plain-text-version-for-emails-sent-using-ses
Updates the SES mailer template with a plaintext template, so that the email will be a multipart email with HTML and plaintext parts.
You can use the mailer preview (http://localhost:3001/rails/mailers/aws_ses_form_submission_mailer/submission_email) to see how the email should look in HTML and plaintext forms.
If running the product in a local AWS shell, you can see the real thing by submitting a file upload form. In Gmail you can then use '[Show original](https://support.google.com/mail/answer/29436?hl=en-GB#zippy=)' to check whether you can see the plaintext content in the email code.
The content should look something like this:
```
This is a completed “Form 1” form.
This form was …
```
=> Add plain text part to submission email

app/jobs/delete_submissions_job.rb, spec/factories/submissions.rb, spec/jobs/delete_submissions_job_spec.rb
Trello card: https://trello.com/c/Qf0gkFUE
This amends the DeleteSubmissionsJob to prevent deletion of submissions where the `mail_status` has been set to "bounced". This will allow us to replay bounced submissions later, once the delivery issues have been resolved.
=> Retain bounced submissions

db/queue_schema.rb
These are just the results of running `rails db:migrate`, which should be committed.
This is probably because setting up Solid Queue created this schema in the first place, and we never ran migrate on that database afterwards to generate these changes.
=> Add generated changes to db/queue_schema.rb

app/jobs/send_submission_job.rb, lib/tasks/submissions.rake, spec/jobs/send_submission_job_spec.rb, spec/lib/tasks/submissions.rake_spec.rb
Add a rake task to retry submissions sent via SES that bounced. This accepts a form id as a parameter, and will enqueue each submission for that form that has a mail status of "bounced".
Trello card: https://trello.com/c/Qf0gkFUE
=> Add rake task to retry bounced submissions

app/jobs/receive_submission_bounces_and_complaints_job.rb, app/jobs/receive_submission_deliveries_job.rb, spec/jobs/receive_submission_bounces_and_complaints_job_spec.rb, spec/jobs/receive_submission_deliveries_job_spec.rb
Trello card: https://trello.com/c/sSfVKcbD/2143-set-up-monitoring-and-observability-for-ses-file-upload-submissions
Add a metric that sends a count every time the job is run for both the ReceiveSubmissionBouncesAndComplaintsJob and the
ReceiveSubmissionDeliveriesJob. We will use this to alert if these jobs aren't run in the expected timeframe.
=> Add metric when jobs for processing SQS messages are run

app/jobs/delete_submissions_job.rb, app/jobs/send_submission_job.rb, db/migrate/20250325180020_add_sent_at_to_submissions.rb, db/migrate/20250325180117_remove_index_on_updated_at_from_submissions.rb, db/schema.rb, spec/jobs/delete_submissions_job_spec.rb, spec/jobs/send_submission_job_spec.rb, spec/services/form_submission_service_spec.rb
Trello card: https://trello.com/c/Qf0gkFUE/2155-handle-bounced-submission-emails
We were relying on the updated_at to decide when to delete a Submission. However, we're now updating the Submission record when we get notification via SNS that a submission has been successfully delivered. We don't know how long it will take to get and process this notifaction, and we don't want to delay deleting submission past our 7 day retention period.
Instead, store a `sent_at` date and use that to decide when to delete submissions.
=> Use sent at date for deleting submissions

app/controllers/submission_status_controller.rb, app/models/submission.rb, config/routes.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, spec/controllers/submission_status_controller_spec.rb, spec/models/submission_spec.rb
Trello card: https://trello.com/c/ZKseq4XJ/2157-add-e2e-test-for-sending-file-as-an-email-attachment
Adds an endpoint that returns if a submission was emailed (via SES) for a given reference.
As part of e2e testing of File Upload. We have no way of checking that the email with attachment was sent from the e2e testing point of view. 
Having a way to check the status of submissions could also feed into monitoring.
=> Attachment sent status

config/application.rb
Trello card: N/A
Rails uses [prepared statements](https://www.postgresql.org/docs/current/sql-prepare.html) to query the database. By default these use wildcard select statements.
This commonly causes issues when adding new columns - the new column will cause postgres to throw an error  cached plan must not change result type`.
In Rails 7, a new config setting, `enumerate_columns_in_select_statements`, was added. This replaces the wildcard  select statements with explicit calls to each column. See [the Rails PR](https://github.com/rails/rails/pull/41718) for details.
This means that the prepared statements will be regenerated every time a column is added, so postgres won't throw the error.
This PR turns that config setting on for our ActiveRecord models.
We've already done this in …
=>  Prevent ActiveRecord errors when adding columns

.github/PULL_REQUEST_TEMPLATE.md
This PR should have the same changes as https://github.com/alphagov/forms-admin/pull/1870.
We occasionally have cases where the end to end tests need to be changed to deploy changes because they rely on content in the app. It helps to think about this before merging a PR, so this commit adds a reminder to the PR review checklist to think about it.
=> Add checking end to end tests to PR review checklist

app/mailers/aws_ses_form_submission_mailer.rb, app/views/aws_ses_form_submission_mailer/submission_email.html.erb, app/views/aws_ses_form_submission_mailer/submission_email.text.erb, config/locales/en.yml, spec/mailers/aws_ses_form_submission_mailer_preview.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb
Trello card: https://trello.com/c/C8KYvyW8
This PR does most of the work to align the submission emails sent via AWS SES with the Notify submission email template, excluding adding content when a CSV is attached. This will follow in a subsequent PR.
=> Align submission emails sent via SES with Notify template

app/services/form_submission_service.rb
This method isn't called anywhere. The "submit_via_aws_ses" method is used instead of SES submissions.
=> Remove unused aws_ses_submission_service method from FormSubmissionService

app/services/form_submission_service.rb, config/settings.yml, spec/config/settings_spec.rb, spec/services/form_submission_service_spec.rb
Trello card: https://trello.com/c/C8KYvyW8
This PR adds a `ses_submissions` feature flag, which when enabled sends all submission emails via AWS SES rather than via Notify. 
This PR shouldn't be merged until the CSV related content in the submission emails is updated.
=> Add SES submissions feature flag

app/mailers/aws_ses_form_submission_mailer.rb, app/services/aws_ses_submission_service.rb, app/views/aws_ses_form_submission_mailer/submission_email.html.erb, app/views/aws_ses_form_submission_mailer/submission_email.text.erb, config/locales/en.yml, spec/mailers/aws_ses_form_submission_mailer_preview.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/C8KYvyW8
We need to add CSV related info to the submission emails sent via AWS SES, so that forms that are receiving answers in CSV files receive submission emails with the right content once we switch over to using AWS SES for all submission emails.
<details><summary>Mailer previews</summary>
HTML:
Plain-text:
```
This is a test of the “Form 1” form.
This form was submitted at 9:15am on 14 April 2025
GOV.​UK Forms reference number: GKCW5J8V
You can check that a payment has been made by using this reference number to search transactions within GOV.​UK Pay.
Check that this data looks safe before you use it
---
forms@example.gov.uk
---
CSV file of these answers
my_answers.csv (attached to this email)
---
You cannot reply to this email
If you need to contact …
```
=> Add CSV file information to submission emails

app/lib/flow/journey.rb, app/models/question/file.rb, app/services/aws_ses_submission_service.rb, spec/features/fill_in_file_upload_question_spec.rb, spec/jobs/delete_submissions_job_spec.rb, spec/lib/flow/journey_spec.rb, spec/models/question/file_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/QTeGemP4/2173-add-the-submission-reference-number-to-the-uploaded-files
Appends the submission reference to the filenames of email attachments.
Includes:
- Adding a new attribute to the Question::File model to store the filename for the email.
- Adding a new `populate_email_filename` method to the file model, which populates the new attribute.
- Adding a check so that we're alerted if the number of files we pass to the mailer is wrong
See individual commit messages for details.
- Upload a file on any form with a file upload question
- submit the form
- check that the filename written in the email matches the filename on the attached file
- check that the filename ends with a submission reference
- check that the submission reference on the filename …
=> Append submission reference to filenames

app/lib/csv_generator.rb, app/models/question/file.rb, app/models/question/name.rb, app/models/question/phone_number.rb, app/models/question/question_base.rb, app/models/repeatable_step.rb, app/services/aws_ses_submission_service.rb, app/services/notify_submission_service.rb, app/services/s3_submission_service.rb, spec/lib/csv_generator_spec.rb, spec/models/question/file_spec.rb, spec/models/repeatable_step_spec.rb, spec/services/aws_ses_submission_service_spec.rb, spec/services/notify_submission_service_spec.rb, spec/services/s3_submission_service_spec.rb, spec/support/shared_examples/question_models.rb
Trello card: https://trello.com/c/hqPJsvS9/2194-support-file-upload-for-submissions-to-s3
When the `submission_type` is set to `s3` for a form, and the form has answered file upload questions, send the uploaded files to the s3 bucket set on the form.
Do this by copying the files to the target bucket and then deleting them from our S3 bucket. Do not copy the object tagging when we do the copy as the form processor does not need the tag added by GuardDuty and to copy the tagging we would need to ask form processors to allow the s3:PutObjectTagging permission for our IAM role.
Copy the files before uploading the submission S3 to the target bucket so that form processors are able to add automations on the CSV file being added and be sure that any uploaded files referenced in the CSV are …
=> Send uploaded files with S3 submissions

app/models/current_request_logging_attributes.rb, app/models/question/question_base.rb, spec/requests/forms/page_controller_spec.rb
Trello card: https://trello.com/c/UcS768Hz/2175-log-validation-error-messages-in-admin-and-runner
Log input validation errors for all questions. The intention is so we can track which validation errors occur regularly that we might want to re-assess.
Examples of fields added to log lines when there are validation errors:
`"validation_errors":["number: not_a_number"]`
`"validation_errors":["text: blank"]`
=> Log question valdation errors

app/models/step.rb, spec/models/step_spec.rb
This bypasses a quirk with how we stored our condition answer values for "None of the above" answers. Intead of storing the answer text, we've been storing `none_of_the_above`, which has meant that the answer value check used during conditional routing hasn't been working correctly.
This fixes it so that it will work when the answer value for a condition is `none_of_the_above`, and the answer given to the selection list question is "None of the above".
https://trello.com/c/2H6cVned/2228-routes-based-on-none-of-the-above-answers-do-not-work
It's a little fiddly to test, but you'd want to create a form which has a condition that's based on a "None of the above" selection. You should notice in admin that the answer value for the condition is displayed erroneously as `none_of_the_above` - …
=> Enable none of the above condition triggers

app/models/current_request_logging_attributes.rb, app/models/question/file.rb, spec/models/current_request_logging_attributes_spec.rb, spec/models/question/file_spec.rb, spec/requests/forms/page_controller_spec.rb
Trello card: https://trello.com/c/UcS768Hz/2175-log-validation-error-messages-in-admin-and-runner
Add an `answer_metadata` logging attribute to log lines, and populate this for `file` questions with the file_type and file_size attributes for the answer. We can then consume our standard request logs for the request to submit a file upload answer, which also now includes any validation errors rather than needing to add explicit logging for file upload in order to extract and report on this data.
Remove the explicit logging that is no longer needed.
- Do the end to end …
=> Remove explicit file upload validation logging

app/models/question/file.rb, config/locales/en.yml, spec/features/fill_in_file_upload_question_spec.rb, spec/models/question/file_spec.rb, spec/requests/forms/page_controller_spec.rb
Trello card: https://trello.com/c/VB6S8I1d/2197-add-error-messages-for-form-fillers-if-the-file-they-select-is-empty
Validate that files aren't empty, and if they are show a validation error to the user.
=> Show error message if the file is empty

app/services/cloud_watch_service.rb, spec/services/cloud_watch_service_spec.rb
Trello card: https://trello.com/c/yxarCr91/2241-use-new-cloudwatch-metrics-in-forms-admin
We've added new metrics that have a different name, namespace and dimensions for displaying the form metrics to form creators and were sending these alongside the old metrics. The new metrics better conformed to the CloudWatch naming conventions. Forms-admin is now using the new metrics, so we can stop sending the old metrics.
Forms-admin was changed to read the new metrics in https://github.com/alphagov/forms-admin/pull/1929
- Do the end to end tests need updating before these …
=> Stop sending old form started/submitted metrics

config/application.rb, config/i18n-tasks.yml, config/locales/en.yml
Trello card: https://trello.com/c/I7wLHZQd/2240-spike-investigate-steps-needed-to-localise-dependency-content
Add defaults for GOVUK Design System Form Builder
In order to support Welsh translations, add configuration for the govuk_design_system_formbuilder gem to set default content for the components we can configure it for.
The documentation for govuk_design_system_formbuilder suggests adding this in a Rails initialiser file. However, if we try to set this configuration during initialization using translations, the localization has not yet been initialized so loading the translations fails. Due to this, we are setting the configuration in an after_initialize callback.
If translations were to fail to load, this would break our feature tests - so these test we are doing the …
=> Add defaults for GOVUK Form Builder

app/jobs/receive_submission_bounces_and_complaints_job.rb, app/jobs/receive_submission_deliveries_job.rb, app/models/current_job_logging_attributes.rb, spec/jobs/receive_submission_bounces_and_complaints_job_spec.rb, spec/jobs/receive_submission_deliveries_job_spec.rb
Log the timestamp for SNS messages we receive for email deliveries and bounces and complaints from the SQS queues. This information is useful because if we get both a bounce and a delivery notification, we will be able to work out which notification was sent first.
=> Log SNS message timestamp

app/services/form_submission_service.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/services/form_submission_service_spec.rb
Currently the form-filler email confirmation includes a link to the call charges page when the form has a contact phone number set.
This link has text but no URL. This is because the email confirmation uses an incorrect attribute for the support_details, which returns an empty string. It's sent to notify as:
```
[Find out about call charges]()
```
When notify converts the markdown to the HTML for the email it becomes:
```
<a style=3D"word-wrap: break-word; color: #1D70B8;" href=3D"http://">Find out about call charges</a>
```
In gmail it displays as:
In outlook it shows as:
It seems the attribute was always wrong and the tests written to expect a link with no URL, which I think must be a mistake.
This commit changes the attribute to the correct value and updates the tests.
Trello card: 
- …
=> Fix email confirmation link to call charges

app/jobs/send_submission_job.rb, app/models/submission.rb, spec/jobs/send_submission_job_spec.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb
Trello card: https://trello.com/c/4EnxrmLq/2864-submitted-at-time-is-in-utc-in-submission-emails-after-switching-to-ses
Emails sent using SES were displaying the submitted at time in UTC rather than in local time. This is because we are using the created_at time for the submission when processing the SendSubmissionJob, which is stored as UTC.
We need to convert the UTC time to the time we've configured to display submissions in, which is London time.
=> Display submitted at time in local time

Gemfile, Gemfile.lock, app/models/submission.rb, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/settings/development.yml, config/settings/test.yml
Answers provided by users and stored in our database are now encrypted using Rails built in ActiveRecord feature.
When I tested locally, I could see that the database encrypted the `answers` blob.
I've also deployed to Dev with the corresponding infrastructure change. I filled in a form and received the submission fine.
Related PR https://github.com/alphagov/forms-deploy/pull/1554
Trello card: https://trello.com/c/jPL9tJkh/2174-switch-on-activerecord-encryption-for-runners-database-that-stores-user-submission-data 
- Do the end to end tests need updating before these …
=> Enable ActiveRecord encryption on Answers

app/frontend/entrypoints/application.js, app/frontend/javascript/utils/google-analytics/index.js, app/frontend/javascript/utils/google-analytics/index.test.js
Trello card: https://trello.com/c/0mqWd67h/2177-log-when-what-files-can-i-upload-details-component-is-clicked
Adds a new tracker for Gogle Analytics that will push an event to the dataLayer if a details component is clicked:
```js
{
event: 'details_opened',
url: "https://submit.forms.service.gov.uk/form/5616/apply-for-a-juggling-licence-advanced/24586",
text: "What files can I upload?"
}
```
This will help us see how often these bits of guidance are being used.
- Has all relevant documentation been …
=> Log when file upload details component is clicked

.github/workflows/test.yml, config/database.yml, config/environments/test.rb, lib/tasks/submissions.rake, spec/factories/models/solid_queue/failed_executions.rb, spec/factories/models/solid_queue/jobs.rb, spec/lib/tasks/submissions.rake_spec.rb
Trello card: https://trello.com/c/6W6mqNEj/2251-add-rake-task-to-retry-failed-submission
Add rake tasks to:
- retry an individual failed job to send a submission
- retry all failed jobs to send submissions
=> Add rakes task to retry failed submission jobs

app/jobs/delete_submissions_job.rb, app/jobs/queue_metrics_job.rb, app/jobs/receive_submission_bounces_and_complaints_job.rb, app/jobs/receive_submission_deliveries_job.rb, app/jobs/send_submission_job.rb, app/services/cloud_watch_service.rb, app/services/log_event_service.rb, spec/jobs/delete_submissions_job_spec.rb, spec/jobs/queue_metrics_job_spec.rb, spec/jobs/receive_submission_bounces_and_complaints_job_spec.rb, spec/jobs/receive_submission_deliveries_job_spec.rb, spec/jobs/send_submission_job_spec.rb, spec/services/cloud_watch_service_spec.rb, spec/services/log_event_service_spec.rb
Methods that were responsible for recording CloudWatch Metrics used the verb "log", which is confusing as "logs" are a different and distinct of observation signal to metrics.
=> Fix naming for methods to record CloudWatch metrics

app/components/cookie_banner_component/view.html.erb, app/controllers/forms/check_your_answers_controller.rb, config/locales/en.yml
Trello card: https://trello.com/c/I7wLHZQd/2240-spike-investigate-steps-needed-to-localise-dependency-content
So that we can add Welsh translations, localize the content for components that came from the defaults
=> Add localization for design system component defaults

app/components/question/selection_component/view.html.erb, app/helpers/application_helper.rb, config/locales/en.yml, spec/helpers/application_helper_spec.rb
Trello card: https://trello.com/c/8M8ZYBYu/2271-localise-autocomplete-in-forms-runner
Explicitly passes in translations to the autocomplete component. The text being passed in matches the existing default text included in accessible-autocomplete. 
Also removes some unused parameters from the init_autocomplete_script helper.
=> Add translations for autocomplete text

app/jobs/receive_submission_deliveries_job.rb, app/services/cloud_watch_service.rb, app/services/s3_submission_service.rb, spec/jobs/receive_submission_deliveries_job_spec.rb, spec/services/cloud_watch_service_spec.rb, spec/services/s3_submission_service_spec.rb
This adds a new "SubmissionDeliveryLatency" metric that show the latency for delivery times for all submission types. This differs from "TimeToSendSubmission" as it records the latency for the submission until we confirmation that submission has been delivered, instead of when we just "sent" the submission to be delivered.
This metric supports both S3 and Email delivery methods.
This metric will support work to build service level indicators about the delivery latency and the user experience of the submission process.
=> Record submission delivery latency metrics

bin/jobs
Trello: https://trello.com/c/f7js82Cm/635-run-solid-queue-as-its-own-ecs-task
We want to run the Solid Queue worker as a separate ECS task (see this PR: https://github.com/alphagov/forms-deploy/pull/1558). The worker ECS task needs a healthcheck to verify the task is running ok. 
This pull requests implements a "lifecycle hook" that creates a `healthcheck` file when Solid Queue starts and removes the file when the process stops. 
According to the Solid Queue README a lifecycle hook is the encouraged approach for this type of scenario (see [README](https://github.com/rails/solid_queue?tab=readme-ov-file#lifecycle-hooks)).
Thanks to @lfdebrux's research I've implemented something similar to SideKiq's file-based readiness probe (see …
=> Create SolidQueue healthcheck process

app/frontend/javascript/utils/google-analytics/index.js, app/frontend/javascript/utils/google-analytics/index.test.js
Trello card: https://trello.com/c/0mqWd67h/2177-log-when-what-files-can-i-upload-details-component-is-clicked
Followup to #1394, updates the Google Analytics event to use the event_data format, so that it can be picked up by the event logic.
- open the javascript console
- click a details component (e.g. 'What files can I upload?') on a file upload question page
- type `dataLayer` into the console and observe that the array contains an item int he format:
```js
{
event: 'event_data',
event_data: {
event_name: 'details_opened',
url: "http://localhost:3001/preview-draft/33/test-a-new-feature/87",
text: "What files can I upload?"
}
}
```
- Do the commit messages …
=> Update event structure for details_opened GA event

.review_apps/README.md
The whole directory was copied from `forms-admin` as a starting point, and we forgot to update the README file.
=> Correct references to "forms-admin" in .review_apps/README.md

Gemfile, Gemfile.lock, app/input_objects/email_confirmation_input.rb, app/validators/email_address_validator.rb, config/application.rb, lib/notifications_utils/formatters.rb, lib/notifications_utils/recipient_validation/email_address.rb, lib/notifications_utils/recipient_validation/errors.rb, spec/input_objects/email_confirmation_input_spec.rb, spec/lib/notifications_utils/formatters_spec.rb, spec/lib/notifications_utils/recipient_validation/email_address_spec.rb, spec/support/custom_matchers.rb
Trello card: https://trello.com/c/tf6aUbYa/2266-make-email-address-validation-consistent 
We've been seeing errors in production from the GOV.UK Notify API from invalid email addresses [[1]]:
```
ValidationError: email_address Not a valid email address (Notifications::Client::BadRequestError)
```
This is happening because when we ask form fillers for an email address for their confirmation email, the validation we do to check whether the email address is valid is much simpler than the validation done by Notify themselves.
It's preferable that we pre-validate the emails on our servers rather than rely on Notify to validate for us, especially if we want to start sending confirmation emails asynchronously.
So we need to have the same validation logic for email addresses as Notify. …
=> Use code from GOV.UK Notify for validating email addresses in our email confirmation input object

Gemfile, Gemfile.lock, app/mailers/form_submission_confirmation_mailer.rb, config/i18n-tasks.yml, config/settings.yml, spec/config/settings_spec.rb, spec/mailers/form_submission_confirmation_mailer_spec.rb, spec/support/shared_context/locale.rb
Trello card: https://trello.com/c/7RWlFifj/2299-make-confirmation-email-send-in-welsh-for-welsh-forms
Adds code to send a different email template (written in Welsh) when the locale of the request is set to Welsh.
Includes:
- configuring the new template
- Making the month part of the date appear in Welsh (adds the [rails-i18n](https://github.com/svenfuchs/rails-i18n/) gem to do this easily)
- A new support file which should make testing locale-related features easier
I've also added a new template in Notify for this.
- Do the end to end tests need updating before …
=> Add Welsh confirmation email

config/i18n-tasks.yml
Now that we're adding welsh translations, we need our tests to tell us when a translation is missing in one of the locales translations files. To do this, the configuration for i18n needed to be updated to allow it to read all files in the config/locales directory.
Trello card: https://trello.com/c/MJPwz0Qb/2297-enforce-that-welsh-translation-exists-for-new-content-in-forms-runner
=> update i18n config to read check all locales files against each other

app/helpers/application_helper.rb, app/views/layouts/base.html.erb, spec/features/fill_in_and_submit_form_spec.rb, spec/helpers/application_helper_spec.rb
Trello card: https://trello.com/c/tuKLpQLL/2685-fix-encoding-so-characters-appear-correctly-in-browser-title-bar
Single quotes were appearing as HTML escaped (&#39;) in the page title as it seemed we were double HTML escaping it. This fixes that.
=> Fix single quote escaped in page title

app/components/question/date_component/view.html.erb, config/locales/cy.yml, config/locales/en.yml
Trello card: https://trello.com/c/CbwtWUHk
This PR adds translations for:
- hidden error prefix for inline error messages
- segment names for date fields
=> Add translations for form builder gem

app/components/footer_component/view.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/components/footer_component/view_spec.rb
Trello card: https://trello.com/c/NOWquTsH/2283-update-govuk-components-gem-to-allow-html-in-the-metalicence-attribute
This PR localises the licence in the footer, using a `meta_licence_html` block passed into the govuk-footer.
=>  Localise licence in footer

app/jobs/application_job.rb, app/jobs/delete_submissions_job.rb, app/jobs/receive_submission_bounces_and_complaints_job.rb, app/jobs/receive_submission_deliveries_job.rb, app/models/current_job_logging_attributes.rb, spec/jobs/delete_submissions_job_spec.rb, spec/jobs/receive_submission_bounces_and_complaints_job_spec.rb, spec/jobs/receive_submission_deliveries_job_spec.rb
Trello card: https://trello.com/c/krMtjVAf/2344-add-extra-information-for-submission-email-bounce-notifications 
This PR adds logging about bounced emails so we can better diagnose issues we see.
I've tested this in dev with a [bounce test form](https://submit.dev.forms.service.gov.uk/preview-draft/14519/bounce-test-form), you can see logs in Splunk by searching for [index="gds_dsp_dev_forms" "submission_bounced"](https://gds.splunkcloud.com/en-GB/app/gds-543-forms/search?earliest=1750248000&latest=1750251600&q=search%20index%3D%22gds_dsp_dev_forms%22%20%22submission_bounced%22&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&sid=1750324171.63441_EF514FC9-3E4E-4E40-A55A-64CE41D26AAF) or looking at the latest events in Sentry at …
=> Add logging of information about email bounces

app/views/forms/privacy_page/show.html.erb, config/locales/cy.yml, config/locales/en.yml
Trello card: https://trello.com/c/P8O3hZsI/2347-change-cabinet-office-to-department-of-science-innovation-and-technology-in-relevant-places-in-runner-admin-and-product-site
Updating privacy notices to say DSIT instead of Cabinet Office. 
After discussing with Stephen, I've put English content into the Welsh privacy notice so that it is obvious we need to get an updated translation before we make that feature live. 
=> Privacy notice update

app/models/question/address.rb, app/models/question/email.rb, app/models/question/name.rb, app/models/question/number.rb, config/locales/cy.yml, config/locales/en.yml, spec/models/question/address_spec.rb, spec/models/question/email_spec.rb, spec/models/question/name_spec.rb, spec/models/question/number_spec.rb
Trello card: https://trello.com/c/ocGdtU52/2360-add-character-limit-validation-to-all-user-inputs-in-forms-runner
Add validations for maximum lengths for question inputs that previously had no length validation:
- Name
- Number
- UK address
- International address
- Email address
For email address questions, we are now using the full email address validation that matches the validation that Notify does.
=> Add input length validations

app/components/form_header_component/view.rb, config/locales/cy.yml, config/locales/en.yml, spec/components/form_header_component/view_spec.rb
Adds a link back to Admin on preview pages. The link is part of the Service Navigation, and will send you to different Admin screens depending on whether the preview is Live or Draft.
Trello card: https://trello.com/c/T1i3CZo7/2361-help-users-get-back-to-your-questions-list-view-when-in-previewing-journey
https://github.com/user-attachments/assets/2b9816d6-3371-4880-aeee-9bce5597a308
https://github.com/user-attachments/assets/80a40675-e7ee-4412-bc63-3c72cad271ab
- Has all relevant documentation …
=> Add link back to Admin for Draft and Live Previews

app/components/form_header_component/view.rb, config/locales/cy.yml, config/locales/en.yml, spec/components/form_header_component/view_spec.rb
Reverts alphagov/forms-runner#1524
This link to Admin is also appearing for Live forms
=> Revert "Add link back to Admin for Draft and Live Previews"

app/jobs/delete_submissions_job.rb, app/jobs/send_submission_job.rb, app/models/submission.rb, db/migrate/20250710153418_update_submission_fields.rb, db/schema.rb, spec/factories/submissions.rb, spec/jobs/delete_submissions_job_spec.rb, spec/jobs/receive_submission_bounces_and_complaints_job_spec.rb, spec/jobs/receive_submission_deliveries_job_spec.rb, spec/jobs/send_submission_job_spec.rb, spec/lib/tasks/submissions.rake_spec.rb, spec/models/submission_spec.rb
This PR adds new columns "delivery_status" and "last_delivery_attempt" to rename "mail_status" and "sent_at". The new names are to generalise the Submission model to allow it to be used to store submission data for all delivery methods (including S3). Therefore needed to remove direct references to the email delivery method.
This is first part of the migration to rename these columns. Here we are adding the columns with the new names, changing the code to use them over the old columns, but also support data in the old columns. 
Future PRs will be raised to migrate existing data in the old columns to the new columns, dropping support for using the columns and the dropping the columns all together.
This also adds an additional "delivered_at" column to represent the timestamp for when a …
=> Add new renamed columns to generalise the Submission model

.github/workflows/dependabot-auto-approve.yml, .github/workflows/lint_workflows.yml, .github/workflows/review_apps_on_pr_change.yml, .github/workflows/review_apps_on_pr_close.yml
We want to set up a flow to to auto-approve some dependabot PRs. PRs will only
be approved if:
- they are not `npm` updates, and
- the update is only a version patch
[Trello card](https://trello.com/c/2Nj1ipbb/2571-automate-patch-dependency-updates)
It would be great to sense check the workflow against what we're trying to achieve.
The workflow is configured to approve and merge a PR **only** if:
- The PR was raised by Dependabot
- The PR is a patch version and not part of an NPM package
- All checks have passed 
Otherwise, those steps will be skipped and the PR goes through the regular review process. You can see this in action in this PR, where all there a bunch of skipped checks relating to the auto-approving and auto-merging.
**General things to consider**
- Is there enough debug …
=> Conditionally auto-approve dependabot PRs

.github/dependabot.yml
We want to trial automatic updates for ruby packages.
Currently, we have dependabot gem updates on Sundays, when no one is working.
This commit changes the day of week for dependabot gem updates from Sunday to Tuesday.
The next Tuesday which is a holiday is [boxing day 2027](https://www.gov.uk/bank-holidays).
This change should keep us going until then whilst we refine how the updates are scheduled.
See the [dependabot
documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#day) for more information.
=> Change day of week for dependabot gem updates

app/lib/ses_email_formatter.rb, app/views/aws_ses_form_submission_mailer/submission_email.html.erb, app/views/aws_ses_form_submission_mailer/submission_email.text.erb, app/views/layouts/mailer.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/lib/ses_email_formatter_spec.rb, spec/mailers/aws_ses_form_submission_mailer_preview.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/c47REcDy/2400-apply-govuk-rebrand-to-ses-email-templates and https://trello.com/c/cq3w8qdB/2965-implement-structure-improvements-to-the-completed-form-email-and-let-users-know
Copies across the rebrand changes from the Notify template and also makes various other structural improvements aimed at make processing forms easier. See individual commit messages for details.
=> Rebrand and restructure SES email template

app/jobs/delete_submissions_job.rb, app/jobs/send_submission_job.rb, app/models/submission.rb, spec/factories/submissions.rb, spec/jobs/delete_submissions_job_spec.rb, spec/jobs/receive_submission_bounces_and_complaints_job_spec.rb, spec/jobs/receive_submission_deliveries_job_spec.rb, spec/jobs/send_submission_job_spec.rb, spec/lib/tasks/submissions.rake_spec.rb, spec/models/submission_spec.rb, spec/services/form_submission_service_spec.rb
These columns had be deprecated and the existing data replicated into the new columns "delivery_status" and "last_delivery_attempt".
This removes the use of the columns from the code base in preparation for the column to be dropped.
=> Stop use of "mail_status" and "sent_at" in Submissions model

app/lib/ses_email_formatter.rb, app/views/aws_ses_form_submission_mailer/submission_email.html.erb, app/views/aws_ses_form_submission_mailer/submission_email.text.erb, app/views/layouts/mailer.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/lib/ses_email_formatter_spec.rb, spec/mailers/aws_ses_form_submission_mailer_preview.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb, spec/services/aws_ses_submission_service_spec.rb
Trello card: https://trello.com/c/c47REcDy/2400-apply-govuk-rebrand-to-ses-email-templates and https://trello.com/c/cq3w8qdB/2402-implement-structure-improvements-to-the-completed-form-email-and-let-users-know
We previously made some changes to the structure of the submission email, including changes to bring it in line with the rebrand (#1540).
Due to an incident with emails not displaying properly in Outlook Classic, we reverted those changes in #1560.
This PR:
- reapplies the original changes (reverts #1560)
- adds a missing closing conditional comment (fixing the issue that caused the incident)
- makes some slight formatting changes
You'll need to:
- Have an email account set up in Outlook classic
- you could use your VDI for this
- either use your DSIT email or add your old CO email …
=> Reapply email rebrand changes

app/jobs/receive_submission_bounces_and_complaints_job.rb, spec/jobs/receive_submission_bounces_and_complaints_job_spec.rb
Trello card: https://trello.com/c/iG4lt8a0/2350-bug-investigate-bounced-email-alerts
Since we switched delivering submissions from Notify to AWS SES we have received around 10 bounce notifications.
We need to track failed deliveries to learn more about the cause of failures.
We log to sentry when a submission is bounced. This is useful for debugging submissions but produces a lot of alerts.
We've learned that submission email addresses which have an auto-reply will trigger a transient bounce and a successful delivery on every form submission.
To prevent this we have asked form creators to stop sending auto-replies from submission addresses. We also plan to make changes to our MOU.
We still want to keep an eye on bounced submissions because it's such an important part of the service.
We …
=> Add form_id to Sentry msg for bounced submissions

.github/workflows/lint_workflows.yml
Optimize CI by triggering workflow linting only when .github/workflows
files are modified, reducing unnecessary runs on unrelated changes.
=> Run actionlint only on workflow file changes

app/controllers/forms/add_another_answer_controller.rb, app/controllers/forms/check_your_answers_controller.rb, app/controllers/forms/exit_pages_controller.rb, app/controllers/forms/page_controller.rb, app/controllers/forms/remove_answer_controller.rb, app/controllers/forms/remove_file_controller.rb, app/controllers/forms/review_file_controller.rb, app/lib/flow/journey.rb, app/lib/flow/step_factory.rb, app/models/step.rb, app/services/log_event_service.rb, app/views/forms/add_another_answer/show.html.erb, app/views/forms/remove_answer/show.html.erb, spec/factories/models/repeatable_steps.rb, spec/factories/models/steps.rb, spec/lib/flow/context_spec.rb, spec/lib/flow/step_factory_spec.rb, spec/models/repeatable_step_spec.rb, spec/models/step_spec.rb, spec/services/log_event_service_spec.rb
This removes the separate page_slug instance variable, which was passed into the initializer for Step via the StepFactory. As the original Page object is also passed in, we can reference it directly from that object. 
This helps simplify the code and makes it easier for future refactoring.
=> Access page_slug from page inside Step class

config/puma.rb
Allow disabling solid queue puma plugin via environment variable.
By default loads solid queue plugin in production mode unless
DISABLE_SOLID_QUEUE is set to "true".
This is used to disable the solid queue supervisor process from
our web server ECS tasks. This allows us to test these changes
in non-production environments. This is part of work moving the
solid queue workers into a separate ECS task.
=> Add DISABLE_SOLID_QUEUE environment variable

lib/notifications_utils/recipient_validation/email_address.rb, spec/lib/notifications_utils/recipient_validation/email_address_spec.rb
Trello card: https://trello.com/c/ly9fJyad
The email address validation was allowing email addresses which end with a `.` which is not valid. This was causing an error to be thrown by ActionMailer when trying to send confirmation emails to users.
Disallow email addresses which end with a `.`.
=> Disallow period at end of email address

app/models/question/text.rb, spec/models/question/text_spec.rb
Trello card: https://trello.com/c/rWMe8Qd4
We’re counting line breaks in long text inputs as 2 characters due to carriage returns (CR) as well as line feed characters (LF) being sent in the HTTP request when the form is submitted for line breaks.
Fix this by stripping our carriage returns from the input before doing the length validation.
=> Ensure carriage returns are counted as 1 character for validation

.review_apps/ecs_task_definition.tf, Gemfile, README.md, app/resources/api/v2/form_document_resource.rb, config/settings.yml, spec/config/settings_spec.rb, spec/features/email_confirmation_spec.rb, spec/features/fill_in_and_submit_form_spec.rb, spec/features/fill_in_and_submit_form_with_csv_spec.rb, spec/features/fill_in_autocomplete_question_spec.rb, spec/features/fill_in_file_upload_question_spec.rb, spec/features/fill_in_form_with_exit_page_spec.rb, spec/features/fill_in_single_repeatable_form_spec.rb, spec/requests/errors_controller_spec.rb, spec/requests/forms/add_another_answer_controller_spec.rb, spec/requests/forms/base_controller_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/requests/forms/privacy_page_controller_spec.rb, spec/requests/forms/remove_answer_controller_spec.rb, spec/requests/forms/remove_file_controller_spec.rb, spec/requests/forms/review_file_controller_spec.rb, spec/requests/forms/submitted_controller_spec.rb, spec/resources/api/v2/form_document_resource_spec.rb, spec/services/api/v1/form_snapshot_repository_spec.rb, spec/services/form_submission_service_spec.rb
Trello card: https://trello.com/c/AiSEhwAu
Update configuration to talk to forms-admin rather than forms-api locally.
Stop sending the API key with requests and remove the configuration setting as forms-runner now makes requests to forms-admin rather than forms-api.
forms-admin does not require an API key for requests as the /api/ endpoints are only accessible from within the VPC in our deployed environments.
=> Update configuration for API requests

.github/dependabot.yml
We previously (alphagov/forms-runner#1644) removed npm from our Dependabot configuration in response to the Shai-Hulud npm worm.
This PR readds it since we think the immediate risk has been adequately mitigated.
Reverts alphagov/forms-runner#1644
=> Revert "Stop Dependabot version updates for npm packages"

app/jobs/delete_submissions_job.rb, app/services/cloud_watch_service.rb, config/settings.yml, config/settings/development.yml, spec/factories/submissions.rb, spec/jobs/delete_submissions_job_spec.rb, spec/services/cloud_watch_service_spec.rb
Trello card: https://trello.com/c/5qTHLaAN/
We already delete submissions 7 days after delivery was attempted if we have not received a notification that the email bounced.
We have a retention policy that we will only keep submission data for a maximum of 30 days, so we need to delete submissions after 30 days regardless of whether the email was delivered or not.
Also add a CloudWatch metric with a DeliveryStatus metric so we can see how many bounced submissions we're deleting.
- Has all relevant …
=> Delete all submissions after 30 days

spec/lib/tasks/submissions.rake_spec.rb
Allow the test to pass regardless of the order of the form_ids array in the log line
=> Fix flaky test

Gemfile.lock
Bumps [uri](https://github.com/ruby/uri) from 1.0.3 to 1.0.4.
- [Release notes](https://github.com/ruby/uri/releases/tag/v1.0.4)
- [Commits](https://github.com/ruby/uri/compare/v1.0.3...v1.0.4)
=> Bump uri from 1.0.3 to 1.0.4
