.github/workflows/rubyonrails.yml, Gemfile.lock, app/views/home/index.html.erb, app/views/layouts/application.html.erb, gulpfile.js, package.json, yarn.lock
This includes:
- the work to make the under construction page compliant with the GOV.UK Design System (closes #12 )
- all of the other frontend changes from forms-admin which haven't made it to this repo yet
=> Make the 'Under Construction' page design system compliant

.rubocop.yml, Gemfile, Gemfile.lock, app/services/notify_service.rb
End User needs to be able to press a button that sends an email using Notify, including the title, text input, and submission time. To do this we need to integrate Notify into the runner. 
This PR is a work in progress
relates #21
=> Notify Integration

manifest.yml
=> Add ((vars)) to manifest to set environment vars

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/forms/pages_controller.rb, app/controllers/forms_controller.rb, app/views/forms/index.erb, app/views/forms/pages/new.erb, app/views/forms/pages/show.erb, config/routes.rb
=> Experimental frontend

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/forms/pages_controller.rb, app/mailers/application_mailer.rb, app/models/page.rb, app/services/notify_service.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/active_resource.rb, config/initializers/assets.rb, config/initializers/filter_parameter_logging.rb, config/initializers/sentry.rb, config/puma.rb, config/routes.rb, spec/helpers/forms/pages_helper_spec.rb, spec/helpers/forms_helper_spec.rb, spec/models/form_spec.rb, spec/models/page_spec.rb, spec/rails_helper.rb, spec/requests/forms/pages_spec.rb, spec/requests/forms_spec.rb, spec/spec_helper.rb
Rather than adding each exception one by one, as we're operating within GDS (and also somewhat related to the GOV.UK area) this adds the govuk rubocop config and updates the entire codebase to be inline with it (the gem iteself defines which folders not to lint)
=> Rubocop govuk

package.json, yarn.lock
Bumps [govuk-frontend](https://github.com/alphagov/govuk-frontend) to v4.1.0
=> Update GOV.UK Frontend to v4.1.0

config/application.rb, docker-compose.yaml
Attempts to fix paas redis connection
=> Redis session

config/application.rb
Sets SSL to allow redis connections
=> Set SSL on redis connection

app/controllers/application_controller.rb, spec/requests/forms_spec.rb, spec/requests/page_spec.rb
=> Add X-Robots-Tag header to prevent search indexing

app/models/question/date.rb, app/models/question/phone_number.rb, app/models/question/single_line.rb, app/views/question/_address.html.erb, config/locales/en.yml, spec/models/question/date_spec.rb, spec/models/question/single_line_spec.rb
=> Update page validation content

manifest.yml
Send forms-runner-dev logs to Splunk
=> Bind to PaaS Splunk service

spec/spec_helper.rb
I set the initial limit to 80% for the moment
as we wouldn't want to drop this high coverage
instead we should be focusing on improving it
further when time permits.
This report will be used by sonarcloud when we
finally introduce it.
=> Config simple-cov

config/i18n-tasks.yml, config/locales/en.yml, config/locales/errors.yml
- [ n/a ] I've updated the documentation in (If any documentation requires updating)
- [ n/a ] README.md
- [ n/a ] Elsewhere (please link)
=> Split out errors localisation file

.github/workflows/deploy.yml, app/controllers/forms/page_controller.rb, app/controllers/forms/submit_answers_controller.rb, config/initializers/sentry.rb, manifest.yml, spec/lib/event_logger_spec.rb
- Fixes missing environment variable (which is why we're seeing no errors at all in Sentry
- Passes environment to Sentry
- Sends events to Sentry in some places where they aren't currently logged because we're handling exceptions
Trello card: https://trello.com/c/739XCh0O/368-sentry-updates
=> Fix Sentry and add environment

Gemfile.lock
Sentry UI was complaining that we were using outdated SDK
=> Update sentry-ruby gem version

manifest.yml
Errors in the runner still aren't coming through to Sentry, because the SENTRY_DSN variable isn't being passed through in the manifest.
Relevant Trello card: https://trello.com/c/739XCh0O/368-sentry-updates
=> Add missing SENTRY_DSN variable

app/controllers/heartbeat_controller.rb, config/routes.rb, spec/requests/heartbeat_spec.rb
This endpoint will be used to check whether the service is online
Linked to https://trello.com/c/Mt0kSgWr/59-setup-pingdom-for-project-repos
=> Add /ping endpoint

config/locales/en.yml, spec/requests/page_spec.rb
=> Update privacy policy link copy

app/controllers/home_controller.rb, app/views/home/index.html.erb, config/routes.rb, spec/requests/errors_spec.rb
Users should only come through to our form runner for a specific form.
Relates to https://trello.com/c/yvbWhIgD/68-remove-form-runner-home-page-and-take-them-to-404-page
=> Replace root path with 404

app/views/forms/check_your_answers/show.html.erb
Relates to https://trello.com/c/sqHZPrV1/67-content-updates-to-check-your-answers-page-in-the-runner
=> Update copy on check your answers page

app/controllers/forms/submit_answers_controller.rb, app/services/notify_service.rb
Relates to: https://trello.com/c/CE08AvcE/46-improve-email-sent-from-forms-runner
=> Update formatting of form submission email

Gemfile, app/lib/step_factory.rb, app/models/form.rb, app/models/page.rb, config/initializers/session_store.rb, spec/lib/context_spec.rb, spec/lib/event_logger_spec.rb, spec/lib/redis_config_spec.rb, spec/models/form_spec.rb, spec/requests/check_your_answers_spec.rb, spec/requests/forms_spec.rb, spec/requests/page_spec.rb
This PR updates pages.next to pages.next_page
This PR is related to this: https://github.com/alphagov/forms-api/pull/63
the linter seemed to change a lot on this PR
=> update page.next to page.next_page, and run linter

app/views/forms/submitted/submitted.html.erb, config/locales/en.yml
Related to: https://trello.com/c/dPkXSMNE/66-make-a-proper-form-submitted-confirmation-page-for-the-runner
=> Use GOV.UK Panel component on form submitted page

app/lib/event_logger.rb, spec/lib/event_logger_spec.rb, spec/requests/check_your_answers_spec.rb, spec/requests/forms_spec.rb, spec/requests/page_spec.rb
Trello card: https://trello.com/c/lVs5LXFB/87-remove-user-agent-from-analytics-logs
=> Remove user agent from analytics events

app/helpers/application_helper.rb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/errors/service_unavailable.html.erb, app/views/errors/submission_error.html.erb, app/views/form/show.html.erb, app/views/forms/check_your_answers/show.html.erb, app/views/forms/page/show.html.erb, app/views/forms/pages/new.erb, app/views/forms/submitted/submitted.html.erb, app/views/help/accessibility_statement.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml, spec/helpers/application_spec.rb
- Adds page titles to each view in the runner
- Copies across the title helpers from the admin
- Adds tests for the title helpers
Trello card: https://trello.com/c/OQrBWD3u/84-add-page-titles-to-form-runner
=> Add page titles to form pages

app/views/help/cookies.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml, config/routes.rb, spec/requests/help_spec.rb, spec/requests/page_spec.rb
Adds a cookie page, and links to that page in the footer. Some of the content isn't finalised, so may change, but functionally this should be complete.
Trello card: https://trello.com/c/wLbTy34H/55-draft-and-publish-cookie-information-to-cover-the-product-product-pages-and-forms
=> Add cookies link to footer

app/controllers/errors_controller.rb, app/controllers/form_controller.rb, config/routes.rb, spec/requests/errors_spec.rb, spec/requests/forms_spec.rb
=> Handle 404 returns

app/controllers/forms/submit_answers_controller.rb
Relates to https://trello.com/c/zvdMX6Bh/126-minor-copy-tweaks-to-the-submission-email
=> Remove colon from end of question content

.github/dependabot.yml
This should only check and create PR for production specific dependency. Anything used for local dev/testing etc will need to manually be updated.
=>  Add dependabot to our repo

app/controllers/forms/submit_answers_controller.rb
=> Fix call to notify service

Dockerfile, app/views/forms/submitted/submitted.html.erb
Trello card: https://trello.com/c/gIZzvIUc/196-add-simple-paragraph-formatting-for-what-happens-next-field
=> Use simple_format in what happens next field

Dockerfile, app/lib/question_register.rb, app/models/question/long_text.rb, app/views/question/_long_text.html.erb, config/locales/en.yml, spec/lib/question_register_spec.rb, spec/models/question/long_text_spec.rb
Created a new 5000 character field
API PR https://github.com/alphagov/forms-api/pull/92
=> Added long_text option

config/locales/en.yml
Adding a missing space from one error message and removing a few unnecessary words from another. 
Trello card: none
- [ yup] I've used the pull request template
- [ n/a] I've linked this PR to the relevant issue (if mission work)
- [ nope] I've written unit tests for these changes (if code change)
- [nope ] I've updated the documentation in (If any documentation requires updating)
=> Tiny error message correction

CONTRIBUTING.md, README.md
Adds some documentation about deployments and browser/assistive technology support to get rid of some old `TODO:` comments.
Trello card: none
=> Add missing documentation

Gemfile, Gemfile.lock, app/lib/question_register.rb, app/models/question/name.rb, app/models/question/question_base.rb, app/models/step.rb, app/services/form_submission_service.rb, app/views/question/_name.html.erb, config/locales/en.yml, spec/mailers/form_submission_mailer_spec.rb, spec/models/question/name_spec.rb, spec/services/form_submission_service_spec.rb, spec/support/shared_examples/question_models.rb, spec/views/question/_name.html.erb_spec.rb
Adds the new name input to the runner.
Includes:
- Adding a model for the new fields
- validation for the new input
- a view for the new input
- Some logic to show different output in the email and the Check Your Answers page
Trello card: https://trello.com/c/efuBewje/384-persons-name-implementation-of-autofill-work-in-production
=> Add name input type

.github/workflows/deploy.yml, config/settings.yml, spec/config/settings_spec.rb
=> Fix dev deploy

app/assets/stylesheets/application.scss
Asset imports are relative to the paths in `app/assets/config/manifest.js`, so the existing import path was incorrect. 
Trello card: No card for this yet
=> Fix draft watermark import path

README.md, lib/tasks/code_quality_checks.rake
Adds rake tasks for linting, runnning tests and normalising locales, and a `run code_quality_checks` task to do them all in parallel. This should make it easier to run them all before committing / pushing your code. There's probably a case for running this task in a git hook but that's a task for another PR.
Trello card: none
=> Add rake task for test and linting

app/controllers/forms/privacy_page_controller.rb, app/lib/context.rb, app/views/forms/check_your_answers/show.html.erb, app/views/forms/submitted/submitted.html.erb, spec/views/forms/check_your_answers/show.html.erb_spec.rb, spec/views/forms/submitted/submitted.html.erb_spec.rb
We were not modifying any of these three attributes which we already have as part of the form attribute.
Trello card:
=> Refactor context declaration_text, what_happens_next_text, privacy_policy_url to use context.form version

Gemfile, Gemfile.lock, spec/factories/models/forms.rb, spec/factories/models/pages.rb, spec/requests/errors_controller_spec.rb, spec/requests/heartbeat_controller_spec.rb, spec/spec_helper.rb, spec/support/factorybot.rb, spec/views/forms/check_your_answers/show.html.erb_spec.rb, spec/views/forms/submitted/submitted.html.erb_spec.rb
We need factorybot & faker for testing and have been putting it off for a long period of time. This PR is to get factorybot & faker in and replaces a few tests to show the factories/faker is working but we should refactor as we work on new features.
Trello card:
=> Add factorybot and faker

app/lib/step_factory.rb
=> Remove unused code in StepFactory and tidy up instance vars

app/models/page.rb, app/models/step.rb, spec/lib/context_spec.rb
=> Minor tweaks

app/views/errors/maintenance.html.erb, config/locales/errors.yml
Update maintenance page copy.
Trello card: https://trello.com/c/P9CEz21c/824-test-and-update-holding-page
=> Update maintenance page copy

Gemfile, Gemfile.lock, spec/lib/redis_config_spec.rb, spec/spec_helper.rb
Removed a few dependencies some of which are simple removes but please review this commit specifically that removes a gem which we have included just to test how redis config works e0bd85ca2f8efda92338676325e7bb4e15f6723d
Trello card:
=> Tidy up Gemfile and remove any unnecessary dependency 

app/views/forms/page/show.html.erb
The Failure was on a bit of code that was needed while migrating each question type. It will be removed once all partials have been converted.
I want to get this out ASAP. At the end of converting to partials to components, This bit of code will be removed and I’ll write some tests to make sure this failure doesn’t happen again.
Trello card:
=> Fix typo in Classname

.github/workflows/docker_build.yml, .github/workflows/test.yml
This allows the use of a merge queue to integrate changes from multiple PRs with the main branch, and to test that the integration works before that code lands in the main branch. Read more about merge queues [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)
This should speed up integrating changes with the main branch for repos which have an active main branch, and makes the requirement for a branch to be up to date redundant.
Trello card: https://trello.com/c/aMbPFqoF
- Has all relevant documentation been …
=> Add merge group GitHub workflow trigger

app/controllers/application_controller.rb, app/lib/hosting_environment.rb, app/lib/redis_config.rb, config/application.rb, config/initializers/session_store.rb, config/locales/en.yml, spec/lib/hosting_environment_spec.rb, spec/lib/redis_config_spec.rb
This includes references to VCAP services which are all related to PaaS
Trello card: https://trello.com/c/DIr6jt2R/177-remove-paas-references-in-code-base
This is my naive attempt at doing it. I don't know if it breaks anything and also not 100% how to check if it does
=> Remove references to PaaS

Dockerfile
In commit 49b9b94 we used both the stable and edge repos for Alpine because we wanted both Node 16 and OpenSSL 3 in our app image. However, today we no longer need any version of Node in our deployment image, and OpenSSL 3 is the default version of OpenSSL in Alpine 3.17.0 [[1]]. So we no longer have a need for edge.
With Alpine 3.17 at the time of this PR fetching the edge repo index fails, so `docker build .` fails with the error:
```
Step 24/35 : RUN apk update
---> Running in 247913f7587d
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/aarch64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/main: BAD …
```
=> Remove Apline edge repositories from Dockerfile

app/controllers/application_controller.rb, app/controllers/forms/check_your_answers_controller.rb, app/lib/form_context.rb, app/views/forms/submitted/submitted.html.erb, config/locales/en.yml, spec/features/email_confirmation_spec.rb, spec/lib/form_context_spec.rb, spec/views/forms/submitted/submitted.html.erb_spec.rb
Trello card: https://trello.com/c/ZRNnzzX2/1132-update-to-final-your-form-has-been-submitted-page-content-to-inform-user-to-expect-an-email
Conditionally adds text saying 'We have sent you a confirmation email.' to the confirmation page if the user has opted to receive an email confirmation. This is implemented using a new custom flash message, `email_sent`, which is passed to the view via the redirect from the `submit_answers` action.
Also includes two small fixes:
- A small update to the email confirmation field's hint text content to reflect the latest designs.
- A small change to improve how we check the session to see if the form has been submitted, and improve consistency when retrieving form answers (hat-tip to @aliuk2012). This fixes an issue which caused some confusing test …
=> Add message to submitted page

spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb
=> Update specs to use rails http code list rather than "magic" numbers

app/controllers/application_controller.rb, app/lib/event_logger.rb, app/lib/session_hasher.rb, spec/lib/event_logger_spec.rb, spec/lib/session_hasher_spec.rb
**Trello**: https://trello.com/c/p1TwAzdL/1207-add-sessionidhash-to-custom-events-in-forms-runner
Logs for domain events don't currently include session_id_hash.
This commit adds the hash to the logged JSON for these events.
To keep the hashes consistent, it centralises the code used to hash the session id.
The hash is not stored anywhere so a request with a log event will hash the session more than once.
The digest used to hash the session_id is quick. If performance became an issue, we could use middleware to hash the session_id once and store it in the request object itself.
Adding a new class, SessionHashser, probably isn't the solution to standardising the request logging but keeping the scope of this PR small will make refactoring logging easier in the future.
Sample of logs after …
=> Add session_id_hash to domain logging

spec/rails_helper.rb, spec/spec_helper.rb
Tidying up our rspec/rails helpers and trying to make them consistent across all our applications.
Refer to individual commits.
Trello card: 
=> tidy up rspec/rails helpers

app/models/check_your_answers_step.rb, spec/lib/step_factory_spec.rb
Our URL slugs use dashes `-` instead of underscores `_`, update the 'check your answers' slug to match.
=> Rename check your answers route

spec/requests/errors_controller_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb
While looking at how to improve the amount of information we log related to form submission emails, I noticed a few things that could be improved in our current codebase.
This PR fixes up a few tests to be more robust.
I've raised this a standalone PR, so that it can be reviewed and merged quickly without getting into changes to implementation.
=> Refactor submission error tests

spec/requests/application_controller_spec.rb, spec/requests/forms/base_controller_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/support/action_controller_notifications_helpers.rb
We're using the same bit of code to subscribe to `process_action` notifications and capture the payload in a couple of different tests now, this commit creates a shared helper to reduce duplication.
=> Refactor tests of controller logging context

public/favicon.ico
Trello card: https://trello.com/c/j3LGb3mn/ 
We're seeing a lot of `404`s in our server logs from clients trying to reach `/favicon.ico`. This PR hopefully fixes this by making it so we can serve the favicon from that path.
This PR should have the same changes as alphagov/forms-product-page#242.
=> Add favicon.ico to server root as symlink

config/locales/en.yml
Trello card: https://trello.com/c/sPNwCAJJ/1391-iterate-design-content-for-payment-links-feature-following-testing
Makes a couple of very small content tweaks on the confirmation page. See individual commit messages for details.
=> Tweak reference number related content

app/lib/limited_html_scrubber.rb, spec/lib/limited_html_scrubber_spec.rb
Trello card: https://trello.com/c/NzuHfgMJ/1476-markdown-formatting-for-new-line-not-working-as-expected-on-what-happens-next-page
We were deliberately restrictive when originally implementing our markdown scrubber, so that we could be sure only the necessary HTML tags could be rendered on the site.
Form creators have valid reasons for using `<br>` tags in their markdown - for formatting addresses in particular - so this PR adds `<br>` to the scrubber's allow list.
```markdown
Your juggling licence application has been received and will now be checked. If your application is successful, your licence will be sent in the post.
If you have not received your licence within 30 days, contact the Department of Juggling by post at:
Department of Juggling  
123 Jugglers Elbow  
London  
E1 8QS …
```
=> Render BR tags in Markdown

app/controllers/forms/check_your_answers_controller.rb, app/views/errors/incomplete_submission.html.erb, config/locales/errors.yml, spec/requests/forms/check_your_answers_controller_spec.rb
Trello card: https://trello.com/c/x8aQr5Y6/1501-it-is-possible-to-submit-an-incomplete-form-after-submitting-a-completed-form
It is possible for a user to submit an incomplete form after they have already submitted a form if they duplicate the tab with the  "Check your anwsers" page before submitting. If they then continue to answer at least one question in a new submission, they were able to go back to the already open "Check your answers" page and submit the incomplete form.
One way of reproducing this is as follows:
1. Create a form with more than one question, none of which are optional
2. Fill out the form until the check your answers page
3. Duplicate the browser tab with the check your answers page twice
4. In the last tab, submit the form
5. In the second tab, click change on one …
=> Show error page when user tries to submit incomplete form

app/controllers/application_controller.rb, app/controllers/forms/base_controller.rb, app/controllers/forms/check_your_answers_controller.rb, app/controllers/forms/page_controller.rb, app/lib/application_logger.rb, app/lib/event_logger.rb, app/lib/json_log_formatter.rb, app/models/current_logging_attributes.rb, app/services/form_submission_service.rb, app/services/log_event_service.rb, config/application.rb, config/environments/production.rb, config/environments/test.rb, spec/controllers/application_controller_spec.rb, spec/lib/application_logger_spec.rb, spec/lib/event_logger_spec.rb, spec/lib/json_log_formatter_spec.rb, spec/models/current_logging_attributes_spec.rb, spec/requests/application_controller_spec.rb, spec/requests/forms/base_controller_spec.rb, spec/requests/forms/check_your_answers_controller_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/services/form_submission_service_spec.rb, spec/services/log_event_service_spec.rb
Trello card: https://trello.com/c/tjnJrmjR/7-improve-default-information-we-add-to-logs
We already use Lograge to add attributes about the request context, such as the `request_id`, `form_id` etc to the request logs for incoming requests to the app.
For other application logs, we use a class called EventLogger to log events as JSON, and pass around a `logging_context` object that we store on the `ApplicationController` and add to in various places throughout a request to add useful JSON fields to the log lines.
Simplify this approach by using an implementation of the `ActiveSupport::CurrentAttributes` abstract super class, which provides a thread-isolated attributes singleton, which resets automatically before and after each request. This implementation - `CurrentLoggingAttributes` stores …
=> Use CurrentAttributes to store and populate log context

app/services/form_submission_service.rb
Trello card: https://trello.com/c/BjjG6uTU/1666-generate-csv-data-for-a-submission
Pass in the form to the FeatureService when checking whether the `attach_csv_to_submission_email` feature flag is enabled. This will allow enabling this flag on a form by form basis.
We don't think this requires additional tests - we test the feature flag when it is set globally in `form_submission_service_spec` and we test applying feature flags for specific forms in `feature_service_spec`.
=> Use per form feature flagging for generating CSV

app/frontend/javascript/utils/google-analytics/index.test.js, app/frontend/test/setup.js, vite.config.js
Following https://github.com/alphagov/forms-admin/pull/1389
I encountered it as part of work for:
Trello card: https://trello.com/c/5hB3tP7b/1708-upgrade-our-apps-from-rails-71-to-72
=> Update vitest to not be silent on failure

app/controllers/application_controller.rb
=> Add request ID header to v2 API requests

app/services/form_submission_service.rb, app/services/s3_submission_service.rb, spec/services/form_submission_service_spec.rb, spec/services/s3_submission_service_spec.rb
Trello card: https://trello.com/c/ToXPf8zb/
When using the AWS SDK for Ruby, it is required to provide the bucket region. If the region is different to the region the bucket was created in, we get the following error:
Aws::s3::Errors::PermanentRedirect - The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
https://github.com/alphagov/forms-api/pull/614 stores the s3_bucket_region on the form. Use this when initializing the S3 client so that we make requests to S3 using the region for the bucket.
1. Update `aws_s3_submissions.iam_role_arn` in the settings.yml file to be the ARN of the role with permissions to upload to the s3 bucket for the dev enviornment (you can ask me for this).
2. Run the forms-api …
=> Specify S3 bucket region

app/lib/csv_generator.rb, app/services/form_submission_service.rb, app/services/log_event_service.rb, app/services/notify_submission_service.rb, app/services/s3_submission_service.rb, spec/factories/models/forms.rb, spec/lib/csv_generator_spec.rb, spec/services/csv_submission_service_spec.rb, spec/services/form_submission_service_spec.rb, spec/services/log_event_service_spec.rb, spec/services/notify_submission_service_spec.rb, spec/services/s3_submission_service_spec.rb
We've recently added a fair bit of additional logic to FormSubmissionService to deal with attaching CSV files to emails and also sending submissions to an S3 bucket. Refactor FormSubmissionService and related services to attempt to divide up the concerns into more manageable classes. 
=> Refactor form submission service

Gemfile, Gemfile.lock, app/lib/csv_generator.rb, app/lib/ses_email_formatter.rb, app/mailers/application_mailer.rb, app/mailers/aws_ses_delivery_method.rb, app/mailers/aws_ses_form_submission_mailer.rb, app/mailers/form_submission_mailer.rb, app/models/form.rb, app/services/aws_ses_submission_service.rb, app/services/form_submission_service.rb, app/views/aws_ses_form_submission_mailer/submission_email.html.erb, config/application.rb, config/environments/development.rb, config/environments/test.rb, config/initializers/mailers.rb, config/locales/en.yml, config/settings.yml, config/settings/test.yml, spec/lib/csv_generator_spec.rb, spec/lib/ses_email_formatter_spec.rb, spec/mailers/aws_ses_delivery_method_spec.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb, spec/mailers/form_submission_mailer_spec.rb, spec/models/form_spec.rb, spec/services/aws_ses_submission_service_spec.rb, spec/services/form_submission_service_spec.rb, spec/services/notify_submission_service_spec.rb
Trello card: https://trello.com/c/JEWV7ew5/
This PR adds a custom delivery method for ActionMailer to send emails using AWS SES. This sends a raw email, which allows us to add attachments. The email uses templates we define in the project to construct the email, which use the `layouts/mailer.html.erb` to apply base formatting to the email.
If a form includes a file upload question, we will send the submission using SES rather than Notify. No live forms currently have the ability to add file upload questions, so for now emails will only be sent using SES when we are doing internal testing.
We are not currently applying GOV.UK styling to the email, this will be done in a subsequent PR which will also look at improving how we format the questions and answers in the email.
We are also not yet …
=> Send submissions using ses for file upload

spec/features/fill_in_and_submit_form_with_csv_spec.rb
Trello card: https://trello.com/c/GxKKN67X/2038-implement-csv-formatting-for-routing
In order to support the CSV submission format in forms which use routing, this PR adds a new feature test.
The code which generates CSV files with submission details have unit tests which stub `Context` with `#completed_steps`. These tests cover the `CsvGenerator` code well but don't test how the answers to questions are collected in the rest of the code, particularly the Context class.
Our current feature tests for filling out forms don't cover the form submission at all.
Our policy for feature tests has been to only test values which are externally visible. They stick to what the user would see when using the service.
We don't check the submission email because it's hard to do without accessing objects …
=> Add feature test for checking CSV submissions

app/models/question/file.rb, app/models/question/file/virus_scan.rb, app/models/step.rb, app/services/question/file_upload_s3_service.rb, config/locales/en.yml, config/settings.yml, config/settings/test.yml, spec/features/fill_in_file_upload_question_spec.rb, spec/models/question/file_spec.rb, spec/models/step_spec.rb, spec/requests/forms/page_controller_spec.rb, spec/services/question/file_upload_s3_service_spec.rb
Trello card: https://trello.com/c/VmHYY9jo/2091-scan-files-that-are-uploaded
Immediately after uploading a file to S3 for a file upload question, poll the object in S3 until the GuardDutyMalwareScanStatus is added with the result of the GuardDuty scan. Only show the review file page if the status is "NO_THREATS_FOUND".
If the status is "THREATS_FOUND", show a validation error stating that the file contains a virus. For any other status, or if we reach our configured maximum number of retries, show an error stating that the file could not be uploaded.
Initially, we will attempt polling a maximum of 20 times with a 500 millisecond wait between each attempt. When testing locally it was seen that the tag was usually found after around 4 attempts.
The maximum number of polling attempts and the …
=> Check GuardDuty scan status after uploading file

config/settings/development.yml
Trello card:  https://trello.com/c/xs3nkHZ3/2117-document-testing-file-upload-from-local-to-s3-and-ses
To test file upload locally we need to connect to the AWS dev account by opening an aws shell. This development.yml file adds all the settings required to upload files to S3 and send emails using SES using the aws dev account.
=> Add development.yml file with settings for testing file upload

spec/features/fill_in_file_upload_question_spec.rb
Trello card: https://trello.com/c/VmHYY9jo/2091-scan-files-that-are-uploaded
Add a feature test to make sure that the error message is displayed back to the user correctly when GuardDuty finds a virus in the uploaded file
=> Add feature test for uploading a file with a virus

app/components/question/file_review_component/view.html.erb, app/views/forms/review_file/show.html.erb, config/locales/en.yml, spec/components/question/file_review_component/view_spec.rb, spec/views/forms/review_file/show.html.erb_spec.rb
There were some translations used in multiple places, but with keys that made it seem they were only used once in a specific context, e.g. table heading.
Trello card: https://trello.com/c/mfhj3ufe
=> Tidy up file upload translations

.github/workflows/test.yml, Dockerfile, Gemfile, Gemfile.lock, bin/setup, config/application.rb, config/database.yml, db/migrate/20250212141200_create_submissions.rb, db/schema.rb
Trello card: https://trello.com/c/lW3IqOhY
We need to store submissions in order to be able to replay failed submission deliveries. This PR adds an initial submissions table with timestamps only, so that we can get our pipelines working. The next step is to get the AWS pipelines working as they should.
=> Add initial submissions table

app/models/question/selection.rb
Just an instance of not being Ruby idiomatic
=> Refactor if else to guard clause in Selection

README.md
Trello card: https://trello.com/c/koB73lTl
=> Add instructions for running Solid Queue locally

app/jobs/receive_submission_bounces_and_complaints_job.rb, app/jobs/receive_submission_deliveries_job.rb, config/recurring.yml, spec/jobs/receive_submission_bounces_and_complaints_job_spec.rb, spec/jobs/receive_submission_deliveries_job_spec.rb
Trello card: https://trello.com/c/Qf0gkFUE
This PR adds an Active Job to process delivery notifications from SES. We update the `mail_status` on the `Submission` and logs the successful delivery. There is quite a bit of duplicated code between `ReceiveSubmissionDeliveriesJob` and `ReceiveSubmissionBouncesAndComplaintsJob` which could in future be extracted into an SQS related class at some point in the future, but I decided not to do this at this stage since there are only two uses so far.
=> Handle success notifications

app/components/form_header_component/_index.scss, app/components/form_header_component/view.rb, app/models/mode.rb, spec/components/form_header_component/form_header_component_preview.rb, spec/components/form_header_component/view_spec.rb, spec/rails_helper.rb, spec/services/form_submission_service_spec.rb
Trello card: https://trello.com/c/aCquw1AP 
Version 5.6.0 of the Design System includes a new 'Service navigation' component. And in the newest release GOV.UK Frontend v5.9.0 the service name in the top navigation will be retired.
This PR moves the form name and start page URL into the service navigation component as the service name and service URL, and also changes the border to be full width to match the component design requirements [1].
There are also some refactors to make this easier to do, and I have sneaked in a commit fixing a local development papercut that prevented me from running unit tests locally for a while.
[1]: https://design-system.service.gov.uk/components/service-navigation/
<details>
<summary>
<h3>Screenshots</h3>
</summary>
</details>
- Ensure that you consider the …
=> Implement service navigation in forms-runner

app/components/question/address_component/view.rb, app/controllers/forms/add_another_answer_controller.rb, app/lib/csv_generator.rb, app/lib/notify_template_formatter.rb, app/lib/ses_email_formatter.rb, app/views/application/accessibility_statement.html.erb, app/views/application/cookies.html.erb, app/views/errors/internal_server_error.html.erb, app/views/errors/maintenance.html.erb, app/views/errors/not_found.html.erb, app/views/forms/check_your_answers/show.html.erb, app/views/forms/exit_pages/show.html.erb, app/views/forms/page/show.html.erb, app/views/forms/privacy_page/show.html.erb, app/views/forms/remove_file/show.html.erb, app/views/forms/review_file/show.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml, spec/helpers/application_helper_spec.rb
This localises the smaller bits of unlocalised content. There are still some pages to do where more of the content isn't localised.
=> Localise content

config/settings.yml, config/settings/development.yml, spec/config/settings_spec.rb
To manage the rollout of the GOV.UK Rebrand, we're adding a feature flag to this app to help
Trello card: https://trello.com/c/ROAXJEiF/2270-add-feature-flags-to-product-pages-and-runner-for-rebranding 
=> Add feature flag for rebrand

app/views/application/accessibility_statement.html.erb, config/locales/en.yml
This PR moves unlocalised content in our accessibility statement into the the locale file, ready for addition of the Welsh locale.
Trello card: https://trello.com/c/EFZCq4bK
=> Move unlocalised content for the accessibility statement

.github/workflows/test.yml, Gemfile, Gemfile.lock, package-lock.json, package.json
Combines PRs:
- #1389
- #1390
- #1391
- #1391
- #1392
- #1398
- #1400
- #1402
- #1403
- #1404
- #1405
- #1406
- #1407
=> Batch dependency updates

app/views/application/cookies.html.erb, config/locales/en.yml
This PR moves unlocalised content in our cookie policy into the the locale file, ready for addition of the Welsh locale.
Trello card: https://trello.com/c/EFZCq4bK
=> Move unlocalised content for the cookie policy

app/components/cookie_consent_form_component/view.html.erb, app/views/forms/privacy_page/show.html.erb, config/locales/en.yml
Localises content in the:
- Cookies consent component on the cookies page
- The privacy page
=> Localise more content

app/views/forms/privacy_page/show.html.erb, config/locales/en.yml
=> Localise privacy page title

app/models/repeatable_step.rb, config/locales/en.yml
This content is not seen by form fillers, but as we have localised other headers in the CSV, localise this for consistency.
=> Localise CSV header for repeatable steps

app/services/form_submission_service.rb, spec/services/form_submission_service_spec.rb
This adds a block to `perform_later` which checks whether the job was successfully enqueued, and raises an error if not. This means an error will be shown to the user.
Trello card: https://trello.com/c/vhGJ3gJq
=> Raise an error if enqueueing SendSubmissionJob fails

app/views/forms/check_your_answers/show.html.erb, config/locales/en.yml
=> Localise content on check your answers page

config/settings.yml, config/settings/development.yml, spec/config/settings_spec.rb
We can't really make use of this effectively, so removing it and keeping the rebrand branch updated with rebases.
=> Remove feature flag for rebrand

lib/tasks/submissions.rake, spec/lib/tasks/submissions.rake_spec.rb
Trello card: https://trello.com/c/DYQK8rIb
We have some bounced submissions which have been confirmed by the form-processor as delivered. This means we need to update these submissions' `mail_status` to pending so that they can be cleaned up by the regular submissions deletion job once the retention period (7 days) has elapsed.
This PR adds a rake task to update the `mail_status` to pending for specified submissions, if they are bounced.
=> Add rake task to discard specified bounced submissions

config/locales/cy.yml
Trello card: https://trello.com/c/Jdfnd3hw/2316-put-welsh-translations-into-locale-file-and-notify-template
This PR adds the additional welsh translations that we have got back
=> Add additional welsh translations

config/locales/cy.yml
Trello card: https://trello.com/c/Jdfnd3hw/2316-put-welsh-translations-into-locale-file-and-notify-template
We missed a couple of translations in this file - this PR adds them.
The remaining English text in this file is aimed at form creators and processors, rather than form fillers.
=> Add missing translations for add another answer

lib/tasks/submissions.rake, spec/lib/tasks/submissions.rake_spec.rb
This is to help us debug a failed submission.
Trello card: https://trello.com/c/BNxXI9bk/2371-failed-submission-wd7ky4g2 
=> Add rake task to inpsect a submission

lib/tasks/submissions.rake, spec/lib/tasks/submissions.rake_spec.rb
Trello card: https://trello.com/c/BNxXI9bk/2371-failed-submission-wd7ky4g2 
=> Add outputting answers from user when inspecting submission with rake task

app/lib/ses_email_formatter.rb, app/views/aws_ses_form_submission_mailer/submission_email.html.erb, app/views/aws_ses_form_submission_mailer/submission_email.text.erb, app/views/layouts/mailer.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/lib/ses_email_formatter_spec.rb, spec/mailers/aws_ses_form_submission_mailer_preview.rb, spec/mailers/aws_ses_form_submission_mailer_spec.rb, spec/services/aws_ses_submission_service_spec.rb
This reverts commit 77f761094cb94f1fb6aff5e83395a877c281d0db, reversing changes made to 33f45d8263863a80bdff551c23c27e592a935e43.
Revert the changes to the submission template.
Some processors have reported issues in certain email clients.
=> Revert "Merge pull request #1540"

app/views/application/accessibility_statement.html.erb, config/locales/cy.yml, config/locales/en.yml
This updates the accessibility statement to:
- remove a line that is inaccurate
- fix a typo
- add a line with the date the statement was reviewed and updated
Have added the new line in English to the welsh translation file - we will need to translate this before we release Welsh versioning. 
Trello card: https://trello.com/c/kvFF6LEl/2453-update-accessibility-statements-to-remove-content-referring-to-2024
=> Update accessibility statement

app/controllers/forms/check_your_answers_controller.rb, app/lib/csv_generator.rb, app/lib/ses_email_formatter.rb
This renames the various variable and arguments names where the values are actually step objects, rather than pages.
=> Fix 'page' variable and argument names to step
